export const INGREDIENT_EMOJI: Record<string, string> = {
  chocolate:    "🍫",
  "blue cheese":"🧀",
  strawberry:   "🍓",
  coffee:       "☕",
  vanilla:      "🌿",
  lamb:         "🥩",
  salmon:       "🐟",
  truffle:      "🍄",
  parmesan:     "🧀",
  tomato:       "🍅",
  basil:        "🌿",
  garlic:       "🧄",
  butter:       "🧈",
  caramel:      "🍮",
  lemon:        "🍋",
  rose:         "🌹",
  oyster:       "🦪",
  lavender:     "💜",
  cucumber:     "🥒",
  mint:         "🌱",
};
