#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","lamb","mint",
     "Blue cheese, lamb, and mint share a three-corner relationship: menthol directly suppresses lamb's gamey 4-methyloctanoic acid through olfactory cooling, menthol suppresses blue cheese's ammonia through the same mechanism, and blue cheese's butyric acid connects to lamb's animal fat through shared fatty-acid chemistry. The trio is the flavor of the world's most sophisticated lamb preparation.",
     "Mint Blue Cheese Lamb Meatballs",
     ["Mix ground lamb with crumbled blue cheese, finely chopped fresh mint, garlic, and cumin.",
      "Roll into balls and brown in olive oil until crusted; finish in tomato sauce for 10 minutes.",
      "Serve with yogurt sauce, fresh mint, and warm flatbread."]),
    ("blue cheese","lamb","oyster",
     "Blue cheese, lamb, and oyster share trimethylamine, dimethyl sulfide, and butyric acid — the complete animal-marine-fermented sulfurous compound triad — creating the most intensely savory non-plant combination possible. The three amplify each other's umami while blue cheese's lactic acid provides a brightening contrast.",
     "Blue Cheese Lamb Oyster Stew",
     ["Brown lamb shoulder pieces; add shucked oysters, blue cheese, and stock to the pot.",
      "Simmer gently until lamb is tender and oysters are just cooked through, about 40 minutes.",
      "Finish with fresh herbs and serve with crusty bread to mop the intensely savory broth."]),
    ("blue cheese","lamb","parmesan",
     "Blue cheese, Parmesan, and lamb form a dairy-meat compound where butyric acid spans all three ingredients — fermented dairy fat and animal fat in the same fatty-acid family — while Parmesan's glutamates amplify lamb's umami and blue cheese's phenylacetaldehyde adds rosy depth. The trio creates the richest possible cheese-meat preparation.",
     "Blue Cheese Parmesan Lamb Gratin",
     ["Layer thin-sliced cooked lamb with a blue cheese and Parmesan cream sauce in a baking dish.",
      "Top with a thick crust of grated Parmesan and breadcrumbs; drizzle with butter.",
      "Bake at 375 degrees F until golden and bubbling; rest 5 minutes before serving."]),
    ("blue cheese","lamb","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — the fermented-rosy compound pair — while lamb's 4-methyloctanoic acid is softened by rose's floral aromatic displacement and blue cheese's lactic acid brightens the heavy meat fat. The trio creates a Persian-Provençal lamb preparation where floral notes elevate the savory.",
     "Rose Blue Cheese Lamb Rack",
     ["Rub lamb rack with a paste of blue cheese, rose water, garlic, and fresh thyme.",
      "Rest 30 minutes; roast at 425 degrees F for 20 minutes to medium-rare.",
      "Rest 8 minutes; scatter dried rose petals and serve with a blue cheese rose jus."]),
    ("blue cheese","lamb","salmon",
     "Blue cheese, lamb, and salmon share trimethylamine, dimethyl sulfide, and butyric acid — the animal-marine-fermented sulfurous compound family — creating a surf-and-turf combination where blue cheese bridges meat and fish through its shared compound presence with both. The trio works best when blue cheese is a sauce rather than a primary ingredient.",
     "Blue Cheese Lamb and Salmon Surf and Turf",
     ["Grill lamb chops and salmon fillets separately to their respective ideal doneness.",
      "Make a blue cheese cream sauce with lemon, white wine, and cream.",
      "Plate the two proteins side by side with the blue cheese sauce drizzled over both."]),
    ("blue cheese","lamb","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound — while lamb's gamey notes are suppressed by strawberry's sweetness through sweet-savory contrast. Blue cheese bridges fruit and meat through its fermented butyric acid presence in both animal-fat and dairy-fat territory. The trio creates a Scandinavian-influenced lamb preparation.",
     "Strawberry Blue Cheese Lamb Salad",
     ["Slice grilled lamb thin against the grain; arrange over dressed arugula.",
      "Scatter sliced strawberries and crumbled blue cheese across the warm lamb.",
      "Dress with a balsamic-honey vinaigrette and cracked pepper; serve immediately."]),
    ("blue cheese","lamb","tomato",
     "Blue cheese, lamb, and tomato share acetic acid and dimethyl sulfide — the tart-sulfurous compound pair — while tomato's furaneol sweetness suppresses lamb's gamey notes and blue cheese's fermented depth elevates the classic lamb-tomato pairing into something more complex than standard ragù.",
     "Blue Cheese Lamb Tomato Ragù",
     ["Brown ground lamb with garlic and onion; add crushed tomatoes and red wine.",
      "Simmer 30 minutes until thick; stir in crumbled blue cheese off heat until just melted.",
      "Toss with rigatoni and finish with Parmesan and fresh thyme."]),
    ("blue cheese","lamb","truffle",
     "Blue cheese, lamb, and truffle share dimethyl sulfide and phenylacetaldehyde — the fermented-earthy-animal compound family — creating a three-way luxury savory combination where truffle's anisaldehyde earthiness rounds lamb's fat and blue cheese's lactic acid provides the brightening contrast. The trio is haute cuisine lamb preparation.",
     "Truffle Blue Cheese Lamb Tartare",
     ["Finely chop high-quality lamb loin; season with truffle oil, salt, and white pepper.",
      "Mix with crumbled blue cheese and a drizzle of truffle cream.",
      "Serve in a ring mold topped with shaved truffle and a small fresh herb garnish."]),
    ("blue cheese","lamb","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol and trace vanillin — the rosy-sweet compound pair — while vanilla's vanillin sweetness suppresses lamb's 4-methyloctanoic acid and blue cheese's ammonia simultaneously through sweet aromatic displacement. The trio creates a Moroccan-inspired sweet-funky-savory lamb preparation.",
     "Vanilla Blue Cheese Glazed Lamb",
     ["Make a glaze from vanilla bean, honey, and blue cheese melted together.",
      "Brush over lamb cutlets and roast at 400 degrees F until caramelized and just pink.",
      "Rest 5 minutes; the sweet-funky glaze creates a lacquered crust."]),
    ("blue cheese","lavender","lemon",
     "Blue cheese and lavender share trace linalool — lavender's dominant terpene softening blue cheese's ammonia through floral displacement — while lemon's citric acid cuts through both blue cheese's fat and lavender's oiliness, creating a three-register bright-floral-funky balance used in Provençal fromage preparations.",
     "Lavender Lemon Blue Cheese Tart",
     ["Make a filling of blue cheese, cream, lemon zest, lemon juice, and a pinch of dried lavender.",
      "Pour into a blind-baked tart shell; bake at 325 degrees F until just set.",
      "Cool; glaze with lemon curd and scatter a few lavender buds before serving."]),
    ("blue cheese","lavender","mint",
     "Blue cheese, lavender, and mint share linalool — the floral terpene that all three produce, suppressing blue cheese's ammonia through a triple-terpene olfactory competition — creating a softer, more floral blue cheese experience where the herb combination makes the funk approachable without masking it entirely.",
     "Lavender Mint Blue Cheese Dip",
     ["Beat room-temperature blue cheese with finely chopped fresh mint and a pinch of dried lavender.",
      "Add a drizzle of lavender honey and lemon zest; mix until smooth.",
      "Serve chilled with apple slices, endive leaves, and crusty bread for dipping."]),
    ("blue cheese","lavender","oyster",
     "Blue cheese and oyster share phenylacetaldehyde, dimethyl sulfide, and trimethylamine — the pungent fermented-marine compound set — while lavender's linalool and linalyl acetate provide the floral aromatic lift that softens both ingredients' sharpest notes through olfactory displacement. The trio creates a refined Provençal oyster preparation.",
     "Lavender Blue Cheese Oyster Gratin",
     ["Mix crumbled blue cheese with dried lavender, breadcrumbs, and lemon zest.",
      "Place on each shucked oyster in the half-shell; drizzle with lavender honey.",
      "Broil 3 minutes until golden; the lavender perfumes the brine as it heats."]),
    ("blue cheese","lavender","parmesan",
     "Blue cheese and Parmesan create a doubled dairy umami base — butyric acid, phenylacetaldehyde, dimethyl sulfide at different intensities — while lavender's linalool provides the floral counterweight that makes the intense cheese combination approachable. The trio produces a sophisticated cheese tart or savory crumble.",
     "Lavender Blue Parmesan Cheese Tart",
     ["Make a filling of blue cheese, Parmesan, cream, eggs, and a pinch of dried lavender; whisk smooth.",
      "Pour into a blind-baked tart shell and bake at 325 degrees F until barely set.",
      "Cool; drizzle with lavender honey and scatter a few dried lavender buds."]),
    ("blue cheese","lavender","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — the fermented-rosy compound pair — while lavender reinforces rose's linalool with its own dominant linalool, creating a double-floral displacement of blue cheese's ammonia. The trio is the most fragrant and elegant blue cheese preparation possible.",
     "Rose Lavender Blue Cheese Honey Toast",
     ["Toast thick-cut bread; spread generously with room-temperature blue cheese.",
      "Drizzle with rose-lavender infused honey and scatter crystallized rose petals.",
      "Add a pinch of flaky salt; the floral honey transforms the blue cheese completely."]),
    ("blue cheese","lavender","salmon",
     "Blue cheese, lavender, and salmon share dimethyl sulfide — the sulfurous compound linking fermented dairy, floral terpene-rich herb, and marine fat — while lavender's linalool softens both blue cheese's ammonia and salmon's trimethylamine through floral aromatic displacement. The trio creates an aromatic baked salmon preparation.",
     "Lavender Blue Cheese Baked Salmon",
     ["Mix crumbled blue cheese with dried lavender, lemon zest, and a drizzle of honey.",
      "Spread over salmon fillets and bake at 400 degrees F for 12 minutes until set.",
      "Broil 2 minutes until the cheese crust is golden; serve with lavender-lemon butter."]),
    ("blue cheese","lavender","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound — while lavender's linalool softens blue cheese's ammonia through floral displacement and strawberry's fresh acidity cuts through blue cheese's heaviest fat. The trio creates a sophisticated sweet-floral-funky dessert cheese flavor.",
     "Lavender Strawberry Blue Cheese Tart",
     ["Make a cheesecake-style filling with blue cheese, cream cheese, lavender sugar, and eggs.",
      "Pour over a pastry crust and bake until just set; cool completely.",
      "Top with fresh strawberries macerated in lavender syrup just before serving."]),
    ("blue cheese","lavender","tomato",
     "Blue cheese and tomato share acetic acid — both contributing tartness — while lavender's linalool provides the Provençal floral note that connects blue cheese's funk and tomato's furaneol sweetness into a southern French flavor register. The trio creates an unusual but coherent tomato-cheese preparation.",
     "Lavender Tomato Blue Cheese Galette",
     ["Arrange sliced ripe tomatoes on rough puff pastry; crumble blue cheese generously over.",
      "Sprinkle with dried lavender and a pinch of sugar; fold pastry edges over loosely.",
      "Bake at 400 degrees F until pastry is golden and tomatoes are caramelized."]),
    ("blue cheese","lavender","truffle",
     "Blue cheese and truffle share phenylacetaldehyde, dimethyl sulfide, and anisaldehyde — the luxury fermented-earthy compound set — while lavender's anisaldehyde aligns with truffle's own anise-adjacent aromatics, creating a triple-anise register that blue cheese's funk grounds into a savory rather than sweet-licorice profile.",
     "Truffle Lavender Blue Cheese Compound Butter",
     ["Beat softened butter with blue cheese, truffle paste, and a pinch of dried lavender.",
      "Add a drizzle of lavender honey and a pinch of flaky salt; mix thoroughly.",
      "Roll in plastic wrap, refrigerate until firm; slice over hot steak or pasta."]),
    ("blue cheese","lavender","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol and trace vanillin — rosy-sweet compounds — while lavender reinforces vanilla's floral character with its own dominant linalool and linalyl acetate, creating a triple-floral-sweet register that blue cheese's butyric acid grounds into a rich, sophisticated dessert flavor.",
     "Lavender Vanilla Blue Cheese Ice Cream",
     ["Make a vanilla custard base; infuse with dried lavender and strain before churning.",
      "Add crumbled blue cheese off heat before churning and stir until just incorporated.",
      "Churn and freeze until firm; serve with lavender honey and crushed shortbread."]),
    ("blue cheese","lemon","mint",
     "Blue cheese and lemon share acetic acid — both contributing tartness that reinforces a bright sour register — while mint's menthol provides cooling contrast that suppresses blue cheese's ammonia and refreshes the palate after lemon's sharp citric hit. Together the three create a bright, funky, cooling blue cheese dressing.",
     "Lemon Mint Blue Cheese Dressing",
     ["Blend room-temperature blue cheese with fresh lemon juice, lemon zest, and fresh mint.",
      "Add buttermilk and a drizzle of olive oil; blend until smooth but still slightly chunky.",
      "Season with white pepper and salt; serve over iceberg wedge or grain bowls."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 014 done: inserted {len(TRIPLETS)} triplets.")
