#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("butter","chocolate","coffee",
     "Butter, chocolate, and coffee share dimethyl sulfide, furaneol, and diacetyl — the most complete overlap of fat-soluble Maillard compounds — while butter acts as the fat medium that carries and amplifies both chocolate's fermentation esters and coffee's roasted aromatics simultaneously. The trio is the flavor base of every great mocha cake and coffee toffee.",
     "Mocha Brown Butter Cake",
     ["Brown butter until deeply nutty; dissolve espresso powder and dark chocolate in it while warm.",
      "Beat with eggs and sugar; fold in flour and a pinch of salt to form a smooth batter.",
      "Bake at 350 degrees F until just set; glaze with coffee caramel while still warm."]),
    ("butter","chocolate","cucumber",
     "Butter and chocolate share dimethyl sulfide and furaneol — fat-soluble Maillard compounds — while cucumber's (E)-2-nonenal provides a cool green freshness that contrasts with the warm chocolate-butter richness. Butter carries cucumber's delicate volatile aldehydes more effectively than water.",
     "Dark Chocolate Cucumber Butter Canapés",
     ["Melt dark chocolate and spread thinly on parchment; immediately place cucumber slices on top.",
      "Press a small knob of salted butter onto each cucumber round before the chocolate sets.",
      "Refrigerate until firm; break into pieces with cucumber still adhered as a surprising canapé."]),
    ("butter","chocolate","garlic",
     "Butter and chocolate share dimethyl sulfide — the sulfurous compound linking dairy fat and roasted cacao — while garlic's allicin-derived compounds share this sulfurous family. Butter converts garlic's harshness into sweet roasted notes that chocolate's bitterness complements. The trio drives dark mole sauce flavor.",
     "Dark Chocolate Garlic Butter Sauce",
     ["Sauté sliced garlic in butter until golden; add a square of grated dark chocolate.",
      "Deglaze with red wine and stock; reduce until thick and glossy.",
      "Strain and finish with cold butter; serve over steak or grilled lamb."]),
    ("butter","chocolate","lamb",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while chocolate's phenylacetaldehyde and dimethyl sulfide share the sulfurous-roasy compound family with both. Butter mediates the dairy-animal-cacao triangle by carrying all three ingredients' volatile aromatics in its fat.",
     "Dark Chocolate Butter Braised Lamb",
     ["Brown lamb shoulder pieces; build a braise with red wine, crushed tomatoes, and a square of dark chocolate.",
      "Add cold butter in small pieces to round the sauce; braise covered at 300 degrees F for 3 hours.",
      "Reduce braising liquid until glossy; serve over polenta with fresh herbs."]),
    ("butter","chocolate","lavender",
     "Butter and chocolate share dimethyl sulfide and furaneol — fat-soluble Maillard compounds — while lavender's linalool and linalyl acetate provide the floral counterweight that prevents the rich butter-chocolate from being heavy. Butter carries lavender's volatile aromatics far longer than any water-based preparation.",
     "Lavender Dark Chocolate Butter Truffles",
     ["Heat cream with dried lavender; strain and pour over chopped dark chocolate.",
      "Stir in cold salted butter piece by piece until the ganache is smooth and glossy.",
      "Refrigerate until firm; roll into balls and dust with cocoa powder."]),
    ("butter","chocolate","lemon",
     "Butter and chocolate share dimethyl sulfide and furaneol — fat-soluble Maillard compounds — while lemon's citric acid and geraniol provide the brightness that cuts through the rich butter-chocolate combination and amplifies chocolate's own acidity. Butter emulsifies lemon's acidity into the chocolate, creating a silky bright-rich ganache.",
     "Lemon Chocolate Butter Tart",
     ["Make a ganache with dark chocolate, lemon zest, and warm cream; stir in cold butter until glossy.",
      "Pour into a blind-baked tart shell; refrigerate until set.",
      "Top with lemon curd; the acid sharpens the chocolate into something more vivid."]),
    ("butter","chocolate","mint",
     "Butter and chocolate share dimethyl sulfide and furaneol — fat-soluble Maillard compounds — while mint's 1,8-cineole and menthol provide cooling contrast that butter carries more effectively than water. Butter's fat extends menthol's cool sensation on the palate, making mint-chocolate taste more intensely minty.",
     "Mint Chocolate Butter Ganache",
     ["Heat cream with fresh mint until steaming; steep 20 minutes, strain well.",
      "Pour over chopped dark chocolate; stir in cold salted butter until smooth and glossy.",
      "Pour into a tray and refrigerate until set; cut into squares and dust with cocoa."]),
    ("butter","chocolate","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds linking dairy fat and marine brine — while chocolate's phenylacetaldehyde and dimethyl sulfide share the sulfurous-rosy family with oyster's marine compounds. Butter mediates the marine-cacao gap. The trio is an avant-garde luxury preparation.",
     "Dark Chocolate Butter Oyster Mignonette",
     ["Melt dark chocolate with butter; drizzle thinly onto parchment and let set.",
      "Break into small shards; top each with a freshly shucked raw oyster.",
      "Finish with fleur de sel and white pepper; the chocolate dissolves on the tongue with the oyster."]),
    ("butter","chocolate","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while chocolate's phenylacetaldehyde and furaneol align with Parmesan's own fermentation esters. Butter carries both Parmesan's umami and chocolate's roasted notes as fat-soluble compounds. The trio is Italian patisserie at its most sophisticated.",
     "Parmesan Dark Chocolate Butter Cake",
     ["Brown butter; dissolve dark chocolate in it; beat with eggs, sugar, and a handful of finely grated Parmesan.",
      "Fold in flour and a pinch of salt; pour into a buttered pan.",
      "Bake at 325 degrees F until just set; the Parmesan adds a savory depth to the chocolate."]),
    ("butter","chocolate","rose",
     "Butter and chocolate share dimethyl sulfide and furaneol — fat-soluble Maillard compounds — while rose's 2-phenylethanol is carried and amplified by butter's fat far more effectively than in a water-based preparation. Together the three create a perfumed, luxury chocolate preparation defined by the rosy-floral compound.",
     "Rose Dark Chocolate Butter Cake",
     ["Brown butter until hazelnut-scented; mix with melted dark chocolate, rose water, and eggs.",
      "Add sugar, flour, and a pinch of salt; pour into a springform pan.",
      "Bake at 350 degrees F until set; dust with rose sugar and scatter crystallized rose petals."]),
    ("butter","chocolate","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble compounds connecting dairy and marine fat — while chocolate's dimethyl sulfide shares the sulfurous family. Butter mediates the cacao-fish gap by carrying both ingredients' volatile compounds in its fat. The trio works as a savory mole-style preparation.",
     "Chocolate Butter Mole Salmon",
     ["Make a mole: blend toasted chiles, garlic, and dark chocolate with chicken stock until smooth.",
      "Simmer until thick; finish with cold butter to round the sauce.",
      "Sear salmon and serve with the chocolate mole; the bitterness is tempered by butter's richness."]),
    ("butter","chocolate","strawberry",
     "Butter, chocolate, and strawberry all share furaneol — the sweet-caramel compound — creating a rare triple-furaneol register where all three ingredients reinforce the same key aroma molecule. Butter's fat carries strawberry's delicate esters and chocolate's volatile roasted compounds simultaneously.",
     "Strawberry Dark Chocolate Brown Butter Tart",
     ["Brown butter until deeply nutty; use for a rich pastry crust and a chocolate ganache.",
      "Pour ganache into the shell; let set, then top with fresh sliced strawberries.",
      "Glaze with a strawberry-balsamic reduction; the browned butter unifies chocolate and fruit."]),
    ("butter","chocolate","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while chocolate's furaneol aligns with tomato's own sweet compound. Butter's fat rounds tomato's acidity while chocolate adds a savory-bitter depth to the sweet tomato. The trio creates sophisticated Mexican mole flavor.",
     "Tomato Dark Chocolate Butter Mole",
     ["Roast tomatoes until charred; blend with dark chocolate, ancho chile, and garlic.",
      "Simmer with stock until thick; finish with cold butter to create a glossy sauce.",
      "Serve over chicken or pork; the chocolate deepens tomato's savory sweetness."]),
    ("butter","chocolate","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble aromatics that butter carries far more effectively than water — while chocolate shares these same compounds through its roasted fermentation. Together the three create the most luxurious fat-soluble aromatic combination in cooking.",
     "Truffle Dark Chocolate Butter Sauce",
     ["Make a ganache with dark chocolate, truffle butter, and warm cream; whisk until smooth.",
      "Stir in a few drops of truffle oil to amplify the earthy register.",
      "Drizzle warm over vanilla ice cream or serve as a dipping sauce for warm brioche."]),
    ("butter","chocolate","vanilla",
     "Butter, chocolate, and vanilla share vanillin, furaneol, diacetyl, and 2-phenylethanol — a nearly complete compound overlap that explains why chocolate and vanilla together with butter is the world's most universally appealing dessert combination. Butter's fat carries all three sets of volatile aromatics simultaneously.",
     "Vanilla Dark Chocolate Butter Ganache",
     ["Heat cream with a split vanilla bean; steep 20 minutes, strain and pour over dark chocolate.",
      "Stir in cold salted butter piece by piece until the ganache is glossy and smooth.",
      "Pour into a tray; refrigerate until set, cut into squares and dust with cocoa powder."]),
    ("butter","coffee","cucumber",
     "Butter and coffee share diacetyl and furfural — the buttery-roasted Maillard compound pair — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that resets between the rich butter-coffee combination. Butter carries coffee's volatile aromatics far more effectively than water, creating a concentrated coffee-forward flavor.",
     "Cold Brew Cucumber Butter Canapés",
     ["Make a coffee-butter compound: beat softened butter with cold brew concentrate and a pinch of salt.",
      "Spread onto thin cucumber rounds; top with a small coffee bean or pinch of espresso powder.",
      "Serve immediately chilled; the cucumber's cool freshness contrasts with the warm coffee butter."]),
    ("butter","coffee","garlic",
     "Butter and coffee share diacetyl and furfural — the buttery-roasted Maillard compound pair — while garlic's allicin is transformed by butter's fat into sweet cooked-garlic notes that coffee's bitterness complements. The three create a bold savory spread for steak or roasted meats.",
     "Coffee Garlic Brown Butter",
     ["Brown butter until deeply nutty; add sliced garlic and cook until golden.",
      "Stir in finely ground espresso and a pinch of smoked salt; cook 30 seconds more.",
      "Drizzle immediately over grilled steak, mushrooms, or roasted potatoes."]),
    ("butter","coffee","lamb",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while coffee's furfural and Maillard compounds provide the roasted-bitter crust note that seals lamb's fat-soluble aromatics. Butter carries coffee's volatile compounds into the meat as a basting medium.",
     "Coffee Brown Butter Braised Lamb",
     ["Brown lamb shoulder pieces in butter until deeply caramelized; set aside.",
      "Make a braise with espresso, crushed tomatoes, garlic, and herbs; add the lamb.",
      "Cover and braise at 300 degrees F for 3 hours; finish with cold butter in the reduced sauce."]),
    ("butter","coffee","lavender",
     "Butter and coffee share diacetyl and furfural — the buttery-roasted Maillard compound pair — while lavender's linalool provides the floral counterweight that prevents the rich butter-coffee combination from being too heavy. Butter carries lavender's volatile aromatics far longer than a water-based preparation.",
     "Lavender Coffee Butter Cake",
     ["Brown butter until hazelnut; mix with espresso powder, dried lavender, eggs, and sugar.",
      "Fold in flour and baking powder; pour into a loaf pan and bake at 350 degrees F.",
      "Glaze with a lavender-coffee icing while still warm; scatter dried lavender buds."]),
    ("butter","coffee","lemon",
     "Butter and coffee share diacetyl and furfural — the buttery-roasted Maillard compound pair — while lemon's citric acid sharpens coffee's bitterness into something more alert and cuts through butter's richness simultaneously. The trio creates the flavor of a sophisticated coffee-lemon butter cake or sauce.",
     "Lemon Coffee Butter Cookies",
     ["Cream butter with sugar; add espresso powder and lemon zest; mix well.",
      "Add flour and a pinch of salt; chill dough 30 minutes, then slice into rounds.",
      "Bake at 350 degrees F until golden; glaze with lemon-coffee icing while warm."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 018 done: inserted {len(TRIPLETS)} triplets.")
