#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("butter","lamb","salmon",
     "Butter, lamb, and salmon share dimethyl sulfide, butyric acid, and trimethylamine — the animal-marine-dairy sulfurous compound family — while butter mediates the meat-fish gap by carrying both proteins' volatile aromatics in its fat. The combination works in surf-and-turf preparations where butter acts as the unifying sauce medium.",
     "Butter Basted Lamb and Salmon Surf and Turf",
     ["Sear lamb chops hard in butter until crusted; baste constantly with the foaming butter.",
      "Sear salmon separately in the same butter until crisp-skinned; rest both proteins.",
      "Plate together; drizzle with lemon-butter sauce that bridges both proteins."]),
    ("butter","lamb","strawberry",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while strawberry's furaneol sweetness directly contrasts lamb's 4-methyloctanoic acid gaminess through sweet-savory balance. Butter carries strawberry's volatile esters and amplifies its delicate furaneol against lamb's richness.",
     "Strawberry Brown Butter Lamb Chops",
     ["Make a quick strawberry reduction with balsamic and shallots; finish with cold butter.",
      "Sear lamb chops in butter until deeply crusted on both sides.",
      "Serve lamb with the strawberry butter sauce; the sweetness cuts the gaminess."]),
    ("butter","lamb","tomato",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while tomato's furaneol sweetness and acetic acid provide the sweet-tart contrast that rounds lamb's richness in long braises. Butter's fat rounds tomato's acidity (Marcella Hazan's principle) applied to lamb ragù.",
     "Butter Braised Lamb Tomato Ragù",
     ["Brown ground lamb with onion and garlic until deeply caramelized.",
      "Add crushed tomatoes and a large knob of butter; simmer uncovered 45 minutes.",
      "Finish with cold butter stirred in off heat; toss with pappardelle and Parmesan."]),
    ("butter","lamb","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics that butter amplifies far beyond any other medium — while lamb's dimethyl sulfide and butyric acid align with truffle's sulfurous-earthy character. Butter mediates the meat-fungus luxury pairing.",
     "Truffle Butter Roast Lamb",
     ["Make a compound butter with softened butter and black truffle paste; season well.",
      "Push truffle butter under the lamb's skin and rub the outside generously.",
      "Roast at 325 degrees F for 1.5 hours; the truffle butter perfumes the lamb throughout."]),
    ("butter","lamb","vanilla",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while vanilla's vanillin sweetness suppresses lamb's 4-methyloctanoic acid gaminess through sweet aromatic displacement. Butter carries vanilla's volatile aromatics and bridges the dairy-sweet and animal-fat registers.",
     "Vanilla Butter Braised Lamb Shanks",
     ["Season lamb shanks; sear in butter until deeply caramelized on all sides.",
      "Add a split vanilla bean, white wine, and stock; braise covered at 300 degrees F for 3 hours.",
      "Remove vanilla, reduce braising liquid with cold butter; the vanilla subtly sweetens the lamb."]),
    ("butter","lavender","lemon",
     "Butter and lavender share trace linalool — butter's fat carries lavender's volatile terpenes far more effectively than water — while lemon's geraniol reinforces lavender's floral terpene character and citric acid brightens butter's richness. The trio creates the classic Provençal lemon-lavender butter.",
     "Lavender Lemon Compound Butter",
     ["Beat softened butter with dried lavender, lemon zest, lemon juice, and a pinch of salt.",
      "Roll in plastic wrap to form a log; refrigerate until firm.",
      "Slice over grilled fish, chicken, or asparagus; the lemon brightens the lavender butter."]),
    ("butter","lavender","mint",
     "Butter and lavender share trace linalool — butter's fat carries lavender's volatile terpenes more effectively — while mint's linalool and menthol reinforce lavender's dominant terpene and provide cooling contrast. Butter extends both herbs' volatile aromatics far longer on the palate.",
     "Lavender Mint Butter Shortbread",
     ["Cream butter with powdered sugar, dried lavender, and finely chopped fresh mint.",
      "Mix in flour and a pinch of salt until a cohesive dough forms; chill 30 minutes.",
      "Slice into rounds; bake at 325 degrees F until just set but not browned."]),
    ("butter","lavender","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds — while lavender's linalool provides a floral aromatic counterweight that suppresses oyster's trimethylamine through fragrant aromatic displacement. Butter carries lavender's volatile aromatics and amplifies oyster's aromatic compounds.",
     "Lavender Butter Roasted Oysters",
     ["Make a compound butter with softened butter, dried lavender, lemon zest, and flaky salt.",
      "Place a small knob on each shucked oyster in the half-shell; broil 3 minutes.",
      "Serve immediately; the lavender perfumes the brine as the butter melts."]),
    ("butter","lavender","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while lavender's linalool provides the Provençal floral counterweight that prevents the dairy richness from being heavy. Butter carries lavender's volatile aromatics and bridges herb and cheese.",
     "Lavender Parmesan Butter Shortbread",
     ["Beat cold butter with finely grated Parmesan, flour, dried lavender, and a pinch of pepper.",
      "Press into a tart pan or roll and cut into rounds; chill 20 minutes.",
      "Bake at 350 degrees F until golden; serve with wine and honey as a savory cheese snack."]),
    ("butter","lavender","rose",
     "Butter and lavender share trace linalool — butter's fat carries lavender's dominant terpene far more effectively than water — while rose's 2-phenylethanol and linalool reinforce lavender's floral character. Together the three create the most concentrated floral butter compound possible.",
     "Rose Lavender Compound Butter",
     ["Beat softened butter with dried lavender, rose water, and a drizzle of rose honey.",
      "Add crushed dried rose petals and a pinch of flaky salt; mix until fragrant.",
      "Roll in plastic wrap; refrigerate until firm. Serve on warm brioche or scones."]),
    ("butter","lavender","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatics connecting dairy and marine fat — while lavender's linalool reinforces this shared terpene and suppresses salmon's trimethylamine through floral aromatic displacement. Butter carries lavender's terpenes more effectively than any marinade.",
     "Lavender Butter Poached Salmon",
     ["Make a court bouillon with white wine, dried lavender, and aromatics.",
      "Poach salmon gently at a bare simmer for 10 minutes until just cooked through.",
      "Serve with a warm lavender beurre blanc and a fresh lavender sprig garnish."]),
    ("butter","lavender","strawberry",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while lavender's linalool provides the Provençal floral note that elevates the fruit-butter combination into something more elegant. Butter carries lavender's volatile terpenes and amplifies strawberry's delicate esters simultaneously.",
     "Lavender Strawberry Brown Butter Galette",
     ["Brown butter until deeply nutty; use for a rough puff pastry base.",
      "Toss strawberries with lavender sugar and a drizzle of lemon juice.",
      "Pile onto the pastry, fold edges over; bake at 400 degrees F until golden and fragrant."]),
    ("butter","lavender","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while lavender's linalool provides the Provençal floral note that transforms slow-roasted tomatoes into a southern French preparation. Butter rounds tomato's acidity while lavender adds aromatic complexity.",
     "Lavender Tomato Butter Confit",
     ["Halve cherry tomatoes; arrange in a dish with dried lavender, garlic, and a large knob of butter.",
      "Roast at 250 degrees F for 2 hours until concentrated and jammy.",
      "Use as a sauce over pasta, fish, or spread on toasted sourdough."]),
    ("butter","lavender","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics — while lavender's anisaldehyde aligns with truffle's own anise-adjacent character. Butter carries both lavender's and truffle's volatile compounds simultaneously, creating a luxury compound butter.",
     "Truffle Lavender Compound Butter",
     ["Beat softened butter with truffle paste, dried lavender, and a pinch of flaky salt.",
      "Add a drizzle of lavender honey to round the earthiness; mix thoroughly.",
      "Roll in plastic wrap, refrigerate until firm; slice over warm risotto or pasta."]),
    ("butter","lavender","vanilla",
     "Butter, lavender, and vanilla share linalool, linalyl acetate, and delta-decalactone — overlapping floral-terpene and lactonic compounds — creating a triple-floral-sweet register where butter's fat carries both ingredients' volatiles simultaneously. The trio produces the most perfumed possible sweet butter.",
     "Lavender Vanilla Compound Butter",
     ["Beat softened butter with vanilla bean seeds, dried lavender, and powdered sugar.",
      "Add a drop of lavender water and a pinch of flaky salt; mix until smooth.",
      "Serve on warm scones, brioche, or waffles with lavender honey."]),
    ("butter","lemon","mint",
     "Butter and lemon share diacetyl and trace geraniol — buttery and citrus-adjacent terpene compounds — while mint's menthol provides cooling contrast that butter extends on the palate far longer than in water. Lemon's citric acid brightens butter's richness while mint adds the cool herbal register.",
     "Lemon Mint Brown Butter",
     ["Brown butter until deeply nutty; add finely chopped fresh mint and remove from heat immediately.",
      "Add a generous squeeze of lemon juice and zest; the butter sizzles with the acid.",
      "Spoon over grilled fish, peas, or pasta; serve immediately while fragrant."]),
    ("butter","lemon","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds — while lemon's citric acid suppresses oyster's trimethylamine and geraniol provides floral brightness. Butter emulsifies lemon's acidity and carries oyster's volatile aromatic compounds. The trio defines classic oyster beurre blanc.",
     "Lemon Butter Baked Oysters",
     ["Make a beurre blanc by reducing lemon juice and shallots; whisk in cold butter piece by piece.",
      "Spoon over shucked oysters in the half-shell; broil 3 minutes until just bubbling.",
      "Finish with a final squeeze of lemon and serve immediately with crusty bread."]),
    ("butter","lemon","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while lemon's citric acid cuts through both ingredients' combined fat and brightens the fermentation esters of Parmesan into a more vivid register. The trio drives lemon pasta and risotto finishing.",
     "Lemon Parmesan Brown Butter Pasta",
     ["Brown butter until deeply nutty; toss hot pasta in the butter with pasta water.",
      "Add a generous handful of finely grated Parmesan, lemon zest, and lemon juice.",
      "Toss vigorously until a glossy sauce forms; serve immediately with more Parmesan."]),
    ("butter","lemon","rose",
     "Butter and lemon share trace geraniol — citrus-adjacent terpene — while rose's geraniol and 2-phenylethanol reinforce this connection. Lemon's citric acid brightens butter's richness while butter carries rose's delicate volatile compounds far longer than water. The trio produces an elegant compound butter.",
     "Rose Lemon Compound Butter",
     ["Beat softened butter with rose water, lemon zest, and a drizzle of rose honey.",
      "Add a pinch of flaky salt and crushed dried rose petals; mix until smooth.",
      "Roll in plastic wrap, refrigerate until firm; serve on scones, fish, or warm bread."]),
    ("butter","lemon","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatic compounds connecting dairy and marine fat — while lemon's citric acid suppresses salmon's trimethylamine and geraniol provides floral brightness. Butter emulsifies lemon's acidity into a silky sauce that coats salmon's fat-soluble aromatics.",
     "Lemon Butter Salmon Meunière",
     ["Season salmon; sear in butter over medium-high heat until golden on both sides.",
      "Add lemon juice and zest; baste the salmon with the foaming lemon butter.",
      "Plate; spoon all the lemon butter pan sauce over the salmon and serve immediately."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 021 done: inserted {len(TRIPLETS)} triplets.")
