#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("caramel","chocolate","coffee",
     "Caramel, chocolate, and coffee form the most complete Maillard-compound trio in cooking: all three share furfural, furaneol, acetic acid, and phenylacetaldehyde through caramelization, cacao fermentation, and coffee roasting. Together they create the most harmonious bitter-sweet-roasted register — the Holy Trinity of café pastry.",
     "Mocha Caramel Tart",
     ["Make a dark caramel; whisk in cream, then dark chocolate until smooth ganache forms.",
      "Add a shot of espresso to deepen the bitterness; pour into a blind-baked chocolate shell.",
      "Refrigerate until set; drizzle with coffee caramel and dust with cocoa powder."]),
    ("caramel","chocolate","cucumber",
     "Caramel and chocolate share furaneol and furfural — the Maillard sweet-roasted compound pair — while cucumber's (E)-2-nonenal provides the palate-cleansing cool freshness that resets between the rich sweet-roasted combination. The trio creates a sophisticated contrast canapé.",
     "Dark Chocolate Caramel Cucumber Canapés",
     ["Melt dark chocolate with a drizzle of caramel; spread thinly on parchment and let set.",
      "Break into shards; top each with a small thick cucumber round.",
      "Finish with flaky salt; the cucumber's cool freshness contrasts the sweet chocolate caramel."]),
    ("caramel","chocolate","garlic",
     "Caramel and chocolate share furaneol and dimethyl sulfide — the Maillard sweet-roasted compound pair — while garlic's allicin-derived compounds share the sulfurous family with both. Caramel's sweetness softens garlic's pungency while chocolate's bitterness adds complexity. The trio drives Mexican mole flavor.",
     "Chocolate Caramel Garlic Mole Sauce",
     ["Slowly caramelize sliced garlic in olive oil until deeply sweet and golden.",
      "Add dark chocolate, ancho chile paste, and a drizzle of caramel; stir until melted.",
      "Simmer with stock until thick; serve over chicken or pork as a complex mole-style sauce."]),
    ("caramel","chocolate","lamb",
     "Caramel and chocolate share furaneol and phenylacetaldehyde — Maillard sweet-roasted compounds — while lamb's 4-methyloctanoic acid gaminess is suppressed by caramel's sweetness through sweet-savory balance. Chocolate adds the dark savory depth of mole while caramel glazes the meat.",
     "Chocolate Caramel Glazed Lamb",
     ["Make a glaze from dark caramel, dark chocolate, soy sauce, and garlic.",
      "Sear lamb chops until deeply crusted; brush generously with chocolate-caramel glaze.",
      "Finish under the broiler 2 minutes until lacquered; serve with the remaining glaze."]),
    ("caramel","chocolate","lavender",
     "Caramel and chocolate share furaneol and furfural — the Maillard sweet-roasted compound pair — while lavender's linalool and anisaldehyde provide the Provençal floral counterweight that prevents the rich sweet-roasted combination from being too heavy. The trio creates a sophisticated French confection.",
     "Lavender Chocolate Caramel Truffles",
     ["Heat cream with dried lavender; strain and pour over dark chocolate.",
      "Stir in a spoonful of dark caramel until glossy; refrigerate until firm.",
      "Roll into balls, dip in dark chocolate, and dust with lavender sugar."]),
    ("caramel","chocolate","lemon",
     "Caramel and chocolate share furaneol and furfural — the Maillard sweet-roasted compound pair — while lemon's citric acid cuts through both ingredients' richness and geraniol provides floral brightness that sharpens the sweet-roasted combination into something more vivid and alert.",
     "Lemon Chocolate Caramel Tart",
     ["Make a dark caramel; whisk in cream and dark chocolate until smooth ganache.",
      "Add lemon zest and lemon juice; pour into a blind-baked pastry shell.",
      "Cool until set; top with a thin lemon curd layer and a sprinkle of fleur de sel."]),
    ("caramel","chocolate","mint",
     "Caramel and chocolate share furaneol and furfural — the Maillard sweet-roasted compound pair — while mint's 1,8-cineole and menthol provide cooling contrast that makes the sweet-roasted combination taste brighter and cleaner. The trio is the flavor of After Eight chocolates elevated to restaurant quality.",
     "Mint Chocolate Caramel Layer Cake",
     ["Make a dark chocolate cake; frost with mint-caramel buttercream between layers.",
      "Top with a dark chocolate caramel ganache glaze; let it drip down the sides.",
      "Finish with fresh mint leaves and a caramel drizzle; refrigerate until set."]),
    ("caramel","chocolate","oyster",
     "Caramel and chocolate share furaneol and dimethyl sulfide — the Maillard sweet-roasted compound pair — while oyster's trimethylamine and dimethyl sulfide share the sulfurous-marine family with both ingredients. Together the three create a daring sweet-brine-roasted combination used in avant-garde seafood applications.",
     "Chocolate Caramel Oyster Shooter",
     ["Melt dark chocolate with a drizzle of caramel and a pinch of fleur de sel.",
      "Pour a thin layer into shot glasses and let set; top with a freshly shucked oyster.",
      "Squeeze a drop of lemon over and serve immediately; the chocolate dissolves with the brine."]),
    ("caramel","chocolate","parmesan",
     "Caramel and chocolate share furaneol and phenylacetaldehyde — Maillard sweet-roasted compounds — while Parmesan's furaneol and phenylacetaldehyde align with both through aged-dairy fermentation. The three share a remarkable compound overlap across very different ingredient categories.",
     "Dark Chocolate Caramel Parmesan Crisps",
     ["Melt dark chocolate with a drizzle of caramel and a pinch of fleur de sel.",
      "Drop small amounts onto finely grated Parmesan rounds on parchment.",
      "Let set until firm; break into irregular pieces for a sophisticated wine pairing."]),
    ("caramel","chocolate","rose",
     "Caramel and chocolate share furaneol and 2-phenylethanol — Maillard sweet-roasted and rosy-floral compounds — while rose amplifies the shared 2-phenylethanol through its dominant floral compound, creating a triple-floral sweet-roasted register. The trio defines sophisticated Turkish-European luxury confection flavor.",
     "Rose Chocolate Caramel Bonbons",
     ["Make a dark chocolate ganache with a drizzle of caramel and rose water; let set.",
      "Roll into balls; dip in tempered dark chocolate to coat completely.",
      "Decorate with a dried rose petal before the coating sets; refrigerate until firm."]),
    ("caramel","chocolate","salmon",
     "Caramel and chocolate share furaneol and dimethyl sulfide — the Maillard sweet-roasted compound pair — while salmon's dimethyl sulfide shares the sulfurous family with both. Caramel's Maillard glaze suppresses salmon's trimethylamine while chocolate adds savory mole-style depth.",
     "Chocolate Caramel Mole Salmon",
     ["Make a light mole with dark chocolate, caramel, ancho chile, and stock.",
      "Simmer until thick and glossy; adjust seasoning with salt and lime juice.",
      "Sear salmon; spoon the chocolate caramel mole over the top and serve immediately."]),
    ("caramel","chocolate","strawberry",
     "Caramel, chocolate, and strawberry share furaneol at exceptionally high concentrations — all three producing this sweet-caramel compound through Maillard, fermentation, and ripening respectively — creating the most compound-coherent sweet trio in cooking. The three together taste richer and sweeter than any combination of two.",
     "Strawberry Chocolate Caramel Tart",
     ["Make a chocolate caramel ganache; pour into a blind-baked pastry shell and set.",
      "Arrange sliced fresh strawberries across the surface in a pattern.",
      "Glaze with a strawberry-caramel reduction; the furaneol in all three amplifies itself."]),
    ("caramel","chocolate","tomato",
     "Caramel and chocolate share furaneol and dimethyl sulfide — the Maillard sweet-roasted compound pair — while tomato's furaneol aligns with both through ripening, creating a triple-furaneol sweet-savory register. Chocolate adds savory mole depth while caramel balances tomato's acidity.",
     "Chocolate Caramel Tomato Mole",
     ["Roast tomatoes until charred; blend with dark chocolate, caramel, ancho chile, and garlic.",
      "Simmer until thick and deeply flavored; finish with a cold knob of butter.",
      "Serve over chicken or as a pasta sauce with Parmesan and fresh herbs."]),
    ("caramel","chocolate","truffle",
     "Caramel, chocolate, and truffle share phenylacetaldehyde, dimethyl sulfide, and furaneol — the luxury Maillard-fermented-earthy compound set — creating an extraordinary three-way savory-sweet-roasted-earthy combination. Together they form the most complex non-herb/spice flavor combination possible.",
     "Truffle Chocolate Caramel Tart",
     ["Make a dark caramel; whisk in cream and dark chocolate; add truffle oil off heat.",
      "Pour into a blind-baked shell and refrigerate until set.",
      "Shave fresh truffle over the top generously just before serving; serve at room temperature."]),
    ("caramel","chocolate","vanilla",
     "Caramel, chocolate, and vanilla share vanillin, furaneol, and 2-phenylethanol — a nearly complete overlap of sweet lactonic, Maillard, and rosy-floral compounds — creating the most complete flavor register in confectionery. The three are so chemically aligned they form one unified super-aroma rather than three distinct notes.",
     "Vanilla Chocolate Caramel Profiteroles",
     ["Make choux pastry; fill with vanilla pastry cream; glaze with chocolate caramel sauce.",
      "Make the sauce by pouring dark caramel into hot cream with grated dark chocolate.",
      "Drizzle generously over filled profiteroles; serve immediately while contrast is vivid."]),
    ("caramel","coffee","cucumber",
     "Caramel and coffee share furfural, acetic acid, and furaneol — three major Maillard and caramelization products — while cucumber's (E)-2-nonenal provides the palate-cleansing cool freshness that resets between the rich sweet-bitter combination. The trio creates a sophisticated iced coffee canapé.",
     "Cold Brew Caramel Cucumber Canapé",
     ["Make a coffee caramel by reducing espresso with sugar to a thick syrup.",
      "Spread a thin layer on crisp cucumber rounds.",
      "Top with a tiny crystal of fleur de sel and a fresh mint leaf; serve chilled immediately."]),
    ("caramel","coffee","garlic",
     "Caramel and coffee share furfural and acetic acid — Maillard sweet-bitter compounds — while garlic's allicin-derived compounds add pungent savory depth. Caramel's sweetness softens garlic's harshness while coffee's bitterness provides a roasted crust note. The trio drives coffee-garlic marinade flavor.",
     "Coffee Caramel Garlic Glaze",
     ["Make a coffee caramel with espresso, brown sugar, garlic, and soy sauce.",
      "Reduce until syrupy; use as a glaze for pork belly, chicken, or roasted vegetables.",
      "Brush on in the last 10 minutes of cooking; broil to caramelize the surface."]),
    ("caramel","coffee","lamb",
     "Caramel and coffee share furfural and acetic acid — Maillard sweet-bitter compounds — while lamb's 4-methyloctanoic acid gaminess is suppressed by caramel's sweetness. Coffee provides the roasted-bitter crust character that seals lamb's fat-soluble aromatics. The trio drives North African-style glazed lamb.",
     "Coffee Caramel Glazed Lamb Chops",
     ["Make a coffee caramel with espresso, brown sugar, soy, and cumin.",
      "Sear lamb chops until deeply crusted; brush with the coffee caramel glaze.",
      "Broil 2 minutes until lacquered; serve with a coffee-spice yogurt sauce."]),
    ("caramel","coffee","lavender",
     "Caramel and coffee share furfural and acetic acid — Maillard sweet-bitter compounds — while lavender's linalool provides the Provençal floral counterweight that softens both the bitterness and the sweetness into a more elegant register. The trio creates a sophisticated café-patisserie flavor.",
     "Lavender Coffee Caramel Pots de Crème",
     ["Steep dried lavender in hot cream 20 minutes; strain and add espresso and caramel.",
      "Whisk into egg yolks; strain again and pour into ramekins.",
      "Bake in water bath at 325 degrees F until just set; chill 4 hours before serving."]),
    ("caramel","coffee","lemon",
     "Caramel and coffee share furfural and acetic acid — Maillard sweet-bitter compounds — while lemon's citric acid sharpens coffee's bitterness and cuts through caramel's sweetness into something more alert. The three create a sophisticated tart-sweet-bitter register.",
     "Lemon Coffee Caramel Tart",
     ["Make a coffee caramel by reducing espresso with sugar and cream until thick.",
      "Pour into a blind-baked pastry shell; cool until set.",
      "Top with lemon curd and finish with a drizzle of coffee caramel and lemon zest."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 024 done: inserted {len(TRIPLETS)} triplets.")
