#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("butter","parmesan","salmon",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while salmon's dimethyl sulfide and linalool align with both dairy ingredients through shared sulfurous-terpene chemistry. Butter mediates the dairy-fish gap while Parmesan adds savory depth.",
     "Parmesan Brown Butter Salmon",
     ["Sear salmon skin-side down in butter until deeply golden; flip and baste constantly.",
      "Immediately dust finely grated Parmesan over the hot fish to melt from the heat.",
      "Finish with lemon juice, cracked pepper, and fresh herbs; serve immediately."]),
    ("butter","parmesan","strawberry",
     "Butter and Parmesan share butyric acid and furaneol — overlapping dairy compounds — while strawberry's furaneol aligns with both dairy ingredients' shared sweet-caramel compound. Butter carries strawberry's volatile esters while Parmesan's umami creates an unexpected savory counterpoint to the fruit.",
     "Strawberry Parmesan Brown Butter Toast",
     ["Brown butter until deeply nutty; toast thick bread in the brown butter until golden.",
      "Top with shaved Parmesan and sliced fresh strawberries dressed with balsamic.",
      "Finish with cracked pepper and a drizzle of aged balsamic; the Parmesan and strawberry are precise."]),
    ("butter","parmesan","tomato",
     "Butter, Parmesan, and tomato share furaneol — the sweet-caramel compound appearing in all three through Maillard, aging, and ripening — while butter rounds tomato's acidity and Parmesan's glutamates amplify tomato's umami. The trio is the Italian trifecta: butter-Parmesan-tomato defines an entire cuisine.",
     "Butter Parmesan Tomato Risotto",
     ["Cook arborio rice with stock until creamy; remove from heat.",
      "Stir in cold butter and finely grated Parmesan vigorously — the mantecatura — until glossy.",
      "Fold in roasted cherry tomatoes just before serving; the tomato's acid brightens everything."]),
    ("butter","parmesan","truffle",
     "Butter, Parmesan, and truffle share dimethyl sulfide, phenylacetaldehyde, and furaneol — the most complete compound overlap of the luxury Italian flavor combination — while butter mediates between dairy and fungal aromatics. The trio defines the finishing of great Italian truffle pasta.",
     "Truffle Parmesan Brown Butter Tagliatelle",
     ["Brown butter until deeply nutty; toss fresh tagliatelle in the butter with pasta water.",
      "Add finely grated Parmesan and toss vigorously until a glossy sauce forms.",
      "Plate and shave generous fresh truffle over each bowl; serve immediately."]),
    ("butter","parmesan","vanilla",
     "Butter, Parmesan, and vanilla share vanillin, furaneol, and butyric acid — an unusual triple overlap of sweet-lactonic and aged-dairy compounds — while vanilla's sweetness grounds Parmesan's sharpest umami notes into something more elegant. The trio creates a sophisticated savory-sweet pasta or risotto finishing.",
     "Vanilla Parmesan Brown Butter Pasta",
     ["Brown butter until deeply nutty; add a split vanilla bean and remove from heat to steep.",
      "Remove vanilla; toss hot pasta in the vanilla brown butter with finely grated Parmesan.",
      "The vanilla subtly sweetens the Parmesan without reading as dessert."]),
    ("butter","rose","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatic compounds — while rose's 2-phenylethanol and geraniol are carried and amplified by butter's fat, suppressing salmon's trimethylamine through floral aromatic displacement. The trio creates the most aromatic possible salmon preparation.",
     "Rose Butter Salmon en Papillote",
     ["Place salmon on parchment with rose-compound butter, lemon slices, and rose petals.",
      "Fold into a sealed parcel, crimping edges tightly to trap all aromatics.",
      "Bake at 400 degrees F for 14 minutes; open at the table to release the rose perfume."]),
    ("butter","rose","strawberry",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while rose's 2-phenylethanol is carried and amplified by butter's fat, reinforcing strawberry's own floral esters through shared compound presence. The trio creates a perfumed, elegant strawberry dessert.",
     "Rose Strawberry Brown Butter Cake",
     ["Brown butter until deeply nutty; cool and mix with rose water, eggs, and sugar.",
      "Fold in flour with fresh strawberries tossed in rose sugar; bake at 350 degrees F.",
      "Drizzle with rose butter glaze while warm; scatter dried rose petals over the top."]),
    ("butter","rose","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while rose's 2-phenylethanol is carried by butter's fat, providing floral brightness that elevates slow-roasted tomatoes into a more aromatic preparation. The three create a refined Provençal tomato sauce.",
     "Rose Butter Tomato Confit",
     ["Halve cherry tomatoes; arrange in a dish with rose butter, garlic, and rose water.",
      "Roast at 250 degrees F for 2 hours until concentrated and fragrant.",
      "Use as a sauce; the rose butter perfumes the tomatoes without making them sweet."]),
    ("butter","rose","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics — while rose's 2-phenylethanol is carried by butter and aligns with truffle's phenylacetaldehyde (the same rosy compound). Together they create the most aromatic luxury compound butter possible.",
     "Rose Truffle Compound Butter",
     ["Beat softened butter with truffle paste and a few drops of rose water until smooth.",
      "Add a drizzle of truffle honey and a pinch of flaky salt; mix thoroughly.",
      "Roll in plastic wrap, refrigerate until firm; slice over warm risotto or pasta."]),
    ("butter","rose","vanilla",
     "Butter, rose, and vanilla share 2-phenylethanol and delta-decalactone — rosy-floral and lactonic compounds — while butter carries both ingredients' volatile aromatics simultaneously, creating the most complete floral-sweet butter compound. The trio defines the flavor of a perfect Paris butter cake.",
     "Rose Vanilla Brown Butter Cake",
     ["Brown butter until hazelnut-scented; cool and beat with sugar, eggs, rose water, and vanilla.",
      "Fold in flour; pour into a prepared cake pan and bake at 350 degrees F until golden.",
      "Drizzle with rose-vanilla glaze; scatter crystallized rose petals over the warm cake."]),
    ("butter","salmon","strawberry",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatics — while strawberry's furaneol sweetness creates a direct contrast to salmon's marine character, with butter mediating the gap by carrying both ingredients' volatile compounds in its fat.",
     "Strawberry Butter Glazed Salmon",
     ["Make a strawberry reduction with balsamic; finish with cold butter for a glossy glaze.",
      "Sear salmon until crispy-skinned; brush with strawberry butter glaze.",
      "Broil 2 minutes until caramelized; serve with fresh strawberry and herb salad."]),
    ("butter","salmon","tomato",
     "Butter, salmon, and tomato share furaneol and dimethyl sulfide — sweet-caramel and sulfurous compounds — while butter mediates the marine-vegetable gap. Butter rounds tomato's acidity (Marcella Hazan's principle) while suppressing salmon's trimethylamine through fat-based compound dilution.",
     "Tomato Butter Poached Salmon",
     ["Make a tomato butter sauce by simmering crushed tomatoes with butter until glossy.",
      "Add salmon fillets; poach gently in the tomato butter at a bare simmer for 10 minutes.",
      "Finish with fresh herbs and extra cold butter stirred in; serve in shallow bowls."]),
    ("butter","salmon","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics — while salmon's dimethyl sulfide aligns with truffle's sulfurous-earthy family. Butter carries truffle's volatile compounds more effectively than any other medium while suppressing salmon's trimethylamine.",
     "Truffle Butter Salmon en Croûte",
     ["Spread salmon fillets with truffle compound butter; wrap in puff pastry and seal.",
      "Brush with egg wash; bake at 400 degrees F for 20 minutes until deeply golden.",
      "Rest 5 minutes; slice and serve with a truffle beurre blanc and fresh herbs."]),
    ("butter","salmon","vanilla",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatics — while vanilla's vanillin sweetness suppresses salmon's trimethylamine and vanilla-poached salmon is a classic French technique. Butter carries vanilla's volatile aromatics into the fish's flesh.",
     "Vanilla Butter Poached Salmon",
     ["Make a court bouillon with butter, white wine, a split vanilla bean, and aromatics.",
      "Poach salmon very gently at a bare simmer for 10 minutes until just opaque.",
      "Serve with a vanilla beurre blanc and a garnish of vanilla-braised fennel."]),
    ("butter","strawberry","tomato",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while tomato's furaneol aligns with both butter's and strawberry's shared sweet compound. Butter carries strawberry's volatile esters and rounds tomato's acidity into a sweet-savory preparation.",
     "Strawberry Tomato Brown Butter Compote",
     ["Brown butter until nutty; add halved cherry tomatoes and cook until they burst.",
      "Add sliced strawberries and a pinch of sugar; cook until jammy and concentrated.",
      "Serve warm over burrata, grilled fish, or toasted sourdough."]),
    ("butter","strawberry","truffle",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while truffle's dimethyl sulfide and phenylacetaldehyde create an earthy luxury contrast. Butter mediates the sweet-earthy gap by carrying both strawberry's volatile esters and truffle's fat-soluble aromatics simultaneously.",
     "Truffle Strawberry Brown Butter Risotto",
     ["Cook arborio risotto until creamy; off heat stir in truffle butter and Parmesan.",
      "Fold in diced fresh strawberry and a drizzle of aged balsamic just before plating.",
      "Shave fresh truffle generously over each bowl; the strawberry brightens the truffle."]),
    ("butter","strawberry","vanilla",
     "Butter, strawberry, and vanilla share furaneol, 2-phenylethanol, and delta-decalactone — a nearly complete aromatic overlap of sweet-caramel, rosy-floral, and lactonic compounds — creating the most compound-coherent dessert base possible. The three reinforce each other's shared compounds without competing.",
     "Strawberry Vanilla Brown Butter Tart",
     ["Brown butter until deeply nutty; make a shortcrust pastry; blind-bake the shell.",
      "Fill with vanilla pastry cream; top with fresh sliced strawberries in a spiral.",
      "Glaze with a strawberry-vanilla reduction; serve at room temperature."]),
    ("butter","tomato","truffle",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while truffle's dimethyl sulfide and phenylacetaldehyde add the luxury earthy register. Butter rounds tomato's acidity while carrying truffle's fat-soluble aromatics to create a refined pasta sauce.",
     "Truffle Tomato Brown Butter Pasta",
     ["Brown butter until nutty; add crushed tomatoes and simmer 20 minutes until thick.",
      "Finish with cold truffle butter stirred in off heat for a glossy, earthy-sweet sauce.",
      "Toss with fresh pasta; shave truffle over each plate and serve immediately."]),
    ("butter","tomato","vanilla",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while vanilla's vanillin reinforces the shared furaneol register and its sweetness amplifies tomato's natural sweetness when slow-roasted. Butter carries vanilla's aromatics and rounds tomato's acidity.",
     "Vanilla Tomato Butter Confit",
     ["Arrange cherry tomatoes in a baking dish with butter, a split vanilla bean, and salt.",
      "Roast at 250 degrees F for 2 hours until concentrated and intensely sweet.",
      "The vanilla amplifies the tomato's natural furaneol into a sweeter, more complex preparation."]),
    ("butter","truffle","vanilla",
     "Butter, truffle, and vanilla form a three-ingredient 2-phenylethanol network — all three produce this rosy compound through entirely different pathways — while butter carries both truffle's earthy dimethyl sulfide and vanilla's sweet vanillin simultaneously. The trio creates the most refined compound butter imaginable.",
     "Truffle Vanilla Compound Butter",
     ["Beat softened butter with truffle paste, vanilla bean seeds, and a pinch of flaky salt.",
      "Add a drizzle of truffle honey; mix until smooth and fragrant.",
      "Roll in plastic wrap; refrigerate until firm. Slice over pasta, risotto, or warm brioche."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 023 done: inserted {len(TRIPLETS)} triplets.")
