#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("caramel","coffee","mint",
     "Caramel and coffee share furfural and acetic acid — Maillard sweet-bitter compounds — while mint's menthol provides the cooling contrast that prevents the warm sweet-bitter combination from feeling heavy. Together the trio creates the flavor of a sophisticated iced mint-caramel coffee drink.",
     "Mint Coffee Caramel Affogato",
     ["Make a mint caramel by cooking sugar until amber; add cream and fresh mint; strain.",
      "Scoop vanilla ice cream into chilled glasses and drizzle with the mint caramel.",
      "Pour a hot shot of espresso over each immediately before serving; the contrast is the point."]),
    ("caramel","coffee","oyster",
     "Caramel and coffee share furfural and dimethyl sulfide — the Maillard sweet-roasted compound pair — while oyster's trimethylamine and dimethyl sulfide share the sulfurous-marine family with both. Together the three create a daring sweet-bitter-brine combination for adventurous oyster preparations.",
     "Coffee Caramel Roasted Oysters",
     ["Mix coffee caramel with breadcrumbs and a pinch of smoked salt.",
      "Place a small amount on each shucked oyster in the half-shell; broil 3 minutes.",
      "The coffee caramel crust contrasts the brine; serve with lemon wedges immediately."]),
    ("caramel","coffee","parmesan",
     "Caramel and coffee share furfural and furaneol — Maillard sweet-roasted compounds — while Parmesan's furaneol and phenylacetaldehyde align with both through aged-dairy fermentation. The three share a remarkable compound network across sweet, bitter, and umami registers.",
     "Coffee Caramel Parmesan Crostini",
     ["Reduce espresso with sugar and a splash of cream to a thick coffee caramel.",
      "Toast baguette rounds; drizzle with coffee caramel while still warm.",
      "Top with shaved Parmesan; the sweet-bitter-umami combination is precise and surprising."]),
    ("caramel","coffee","rose",
     "Caramel and coffee share furfural and 2-phenylethanol — Maillard sweet-roasted and rosy-floral compounds — while rose amplifies the shared 2-phenylethanol through its dominant floral compound. Together the three create a Middle Eastern-inflected café flavor where the flower softens the bitter-sweet.",
     "Rose Coffee Caramel Panna Cotta",
     ["Warm cream with espresso and rose water; add caramelized sugar and dissolve gelatin.",
      "Pour into molds and refrigerate 4 hours until set.",
      "Unmold; drizzle with coffee caramel and scatter crystallized rose petals."]),
    ("caramel","coffee","salmon",
     "Caramel and coffee share furfural and dimethyl sulfide — the Maillard sweet-roasted compound pair — while salmon's dimethyl sulfide aligns with the sulfurous family of both. Caramel's Maillard glaze suppresses salmon's trimethylamine while coffee adds a roasted crust character.",
     "Coffee Caramel Glazed Salmon",
     ["Make a coffee caramel glaze with espresso, brown sugar, soy sauce, and ginger.",
      "Sear salmon skin-side down until crispy; brush generously with coffee caramel glaze.",
      "Broil 2 minutes until lacquered; serve with pickled cucumber and sesame."]),
    ("caramel","coffee","strawberry",
     "Caramel, coffee, and strawberry share furaneol — all three producing this sweet-caramel compound through Maillard, coffee fermentation/roasting, and fruit ripening — while coffee's bitterness provides the counterbalance to strawberry's sweetness and caramel's warmth. The trio is a sophisticated café dessert.",
     "Strawberry Coffee Caramel Pavlova",
     ["Bake a meringue base; spread with a coffee caramel cream.",
      "Macerate sliced strawberries with espresso syrup and caramel; pile generously over the cream.",
      "Finish with a drizzle of coffee caramel and dust with espresso powder."]),
    ("caramel","coffee","tomato",
     "Caramel and coffee share furfural and furaneol — the Maillard sweet-bitter compound pair — while tomato's furaneol aligns with both through ripening, creating a triple-furaneol register. Coffee's bitterness deepens tomato's savory notes into something more complex than standard tomato sauce.",
     "Coffee Caramel Tomato Sauce",
     ["Make a light caramel with sugar; add crushed tomatoes and reduce 20 minutes.",
      "Stir in a shot of espresso and finish with cold butter for a glossy, complex sauce.",
      "Serve over pasta; the coffee's bitterness deepens the tomato without being detectable."]),
    ("caramel","coffee","truffle",
     "Caramel, coffee, and truffle share dimethyl sulfide, phenylacetaldehyde, and furfural — the luxury Maillard-earthy compound set — while caramel's sweetness rounds truffle's earthiness and coffee's bitterness provides the roasted counterbalance. Together they create an extraordinary luxury sweet-savory combination.",
     "Truffle Coffee Caramel Butter",
     ["Beat softened butter with truffle paste, finely ground espresso, and a drizzle of dark caramel.",
      "Season with flaky salt; roll in plastic wrap and refrigerate until firm.",
      "Slice over hot pasta or risotto; the three compounds amplify each other."]),
    ("caramel","coffee","vanilla",
     "Caramel, coffee, and vanilla share vanillin and furaneol — sweet-lactonic and Maillard compounds — while coffee's furfural provides the bitter counterbalance to vanilla's sweetness and caramel's warmth. Caramel amplifies vanilla's sweetness and coffee's bitterness simultaneously. The trio is classic café flavor.",
     "Vanilla Coffee Caramel Crème Brûlée",
     ["Make a vanilla custard; add espresso powder and caramelized sugar to the cream base.",
      "Pour into ramekins and bake in water bath at 325 degrees F until just set.",
      "Chill 4 hours; sprinkle sugar and torch to form a crackled caramel just before serving."]),
    ("caramel","cucumber","garlic",
     "Caramel's Maillard sweetness contrasts cucumber's cool hexanal freshness and garlic's allicin pungency — three completely distinct registers — while caramel's sweetness softens garlic through sweet-savory balance and cucumber's coolness provides palate-cleansing contrast. The trio creates an unexpected summer canapé.",
     "Caramel Garlic Cucumber Bites",
     ["Slowly caramelize garlic cloves in sugar until golden and sweet; cool.",
      "Spread a thin layer of caramel on thick cucumber rounds; press a garlic confit clove into each.",
      "Finish with flaky salt; the sweet garlic contrasts the cool cucumber."]),
    ("caramel","cucumber","lamb",
     "Caramel's Maillard sweetness suppresses lamb's 4-methyloctanoic acid gaminess through sweet-savory contrast — the principle behind honey-glazed lamb — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that resets between each rich sweet-savory bite. The trio is a refined Middle Eastern lamb preparation.",
     "Caramel Glazed Lamb with Cucumber Raita",
     ["Make a caramel glaze with honey, soy, garlic, and cumin; brush over lamb chops.",
      "Grill to medium-rare; rest 3 minutes.",
      "Serve with a cooling cucumber raita; the sweet glaze and cool cucumber contrast perfectly."]),
    ("caramel","cucumber","lavender",
     "Caramel's Maillard sweetness and lavender's linalool create a sophisticated floral-sweet combination — the principle behind lavender honey — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that prevents the rich sweet-floral combination from being cloying.",
     "Lavender Caramel Cucumber Granita",
     ["Make a lavender caramel by cooking sugar until amber, adding lavender-infused cream.",
      "Blend with cucumber juice and lime; pour into a shallow freezer pan.",
      "Freeze, scraping every 30 minutes until granita; serve in chilled glasses."]),
    ("caramel","cucumber","lemon",
     "Caramel's Maillard sweetness and lemon's citric acidity create a salted-caramel tartness while cucumber's hexanal provides the palate-cleansing cool freshness that balances the rich sweet-sour combination. The trio creates a sophisticated summer dessert.",
     "Lemon Caramel Cucumber Sorbet",
     ["Make a lemon caramel by cooking sugar until dark amber; deglaze with lemon juice and cucumber juice.",
      "Adjust sweetness and acidity; churn in an ice cream maker until smooth.",
      "Freeze until firm; serve with a fresh cucumber ribbon and lemon zest."]),
    ("caramel","cucumber","mint",
     "Caramel's Maillard warmth and mint's menthol create a toffee-mint contrast while cucumber's (E)-2-nonenal provides a cool watery freshness that reinforces mint's coolness. The trio creates a refreshing summer dessert where warm-sweet and cool-herbal alternate.",
     "Mint Caramel Cucumber Granita",
     ["Make a mint caramel by cooking sugar to amber; add mint-infused cream and strain.",
      "Blend with cucumber juice; pour into a shallow pan and freeze, scraping hourly.",
      "Serve in chilled cups with a fresh mint leaf and cucumber round garnish."]),
    ("caramel","cucumber","oyster",
     "Caramel's Maillard sweetness creates a direct sweet-brine contrast with oyster's marine trimethylamine — the most direct sweet-salt pairing — while cucumber's cool freshness provides the palate-cleansing reset between each intensely flavored combination. The trio is avant-garde raw bar flavor.",
     "Caramel Cucumber Oyster Shooter",
     ["Make a light caramel; thin with cucumber juice and a splash of lime.",
      "Shuck oysters into chilled shot glasses; top with the caramel-cucumber liquid.",
      "Drop of Tabasco; serve immediately while the contrast between sweet and brine is vivid."]),
    ("caramel","cucumber","parmesan",
     "Caramel and Parmesan share furaneol — the sweet-caramel compound appearing in both Maillard reactions and aged cheese fermentation — while cucumber's (E)-2-nonenal provides the palate-cleansing coolness that resets between the rich sweet-umami combination. The trio creates an unusual cheese canapé.",
     "Caramel Parmesan Cucumber Crisps",
     ["Make Parmesan crisps with a drizzle of dark caramel mixed in before baking.",
      "Bake at 375 degrees F until golden and lacy; cool until crisp.",
      "Place each crisp on a thick cucumber round; serve immediately."]),
    ("caramel","cucumber","rose",
     "Caramel's Maillard sweetness and rose's 2-phenylethanol create a floral-sweet combination while cucumber's (E)-2-nonenal provides the cool freshness that prevents the rich floral-sweet from being cloying. Cucumber's watery cool makes rose's perfume feel lighter and more refreshing.",
     "Rose Caramel Cucumber Agua Fresca",
     ["Make a rose caramel syrup; cool and blend with cucumber juice and lime.",
      "Strain until completely clear; chill thoroughly.",
      "Serve over ice in tall glasses with rose petals and a cucumber round garnish."]),
    ("caramel","cucumber","salmon",
     "Caramel's Maillard glaze suppresses salmon's trimethylamine through sweet-savory contrast — the teriyaki principle — while cucumber's (E)-2-nonenal mirrors salmon's own marine-green aldehyde notes, creating a cool freshness that cuts through the rich caramelized crust. The trio is a refined glazed salmon preparation.",
     "Caramel Glazed Salmon with Cucumber Salad",
     ["Make a caramel glaze with soy sauce, mirin, and sugar; reduce until syrupy.",
      "Sear salmon skin-side down; flip and brush with caramel glaze; broil 2 minutes.",
      "Serve over a cool cucumber salad with rice vinegar and sesame; contrast is key."]),
    ("caramel","cucumber","strawberry",
     "Caramel and strawberry share furaneol — the sweet-caramel compound — while cucumber's hexanal provides the palate-cleansing cool freshness that prevents the double-furaneol sweet combination from being cloying. The trio creates a sophisticated summer dessert where sweetness and freshness balance.",
     "Strawberry Caramel Cucumber Gazpacho",
     ["Blend fresh strawberries with cucumber, caramel, lime juice, and a pinch of salt.",
      "Strain until smooth; adjust sweetness and acidity.",
      "Serve very cold in chilled bowls with diced strawberry and cucumber garnish."]),
    ("caramel","cucumber","tomato",
     "Caramel and tomato share furaneol — the sweet-caramel compound in both Maillard caramelization and tomato ripening — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that balances the sweet-savory tomato-caramel combination. The trio creates a refined summer gazpacho.",
     "Caramelized Tomato Cucumber Gazpacho",
     ["Roast tomatoes with a drizzle of sugar until caramelized; cool completely.",
      "Blend caramelized tomatoes with fresh cucumber, garlic, and olive oil until smooth.",
      "Season with sherry vinegar and salt; strain, chill, and serve very cold."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 025 done: inserted {len(TRIPLETS)} triplets.")
