#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("butter","cucumber","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble aromatics that butter solubilizes far more effectively than water — while cucumber's (E)-2-nonenal provides the palate-cleansing cool freshness that prevents the rich truffle butter from being overwhelming. The trio creates an elegant luxury summer canapé.",
     "Truffle Butter Cucumber Canapés",
     ["Whip truffle butter until smooth; spread onto thick cucumber rounds.",
      "Top each with a small shaving of fresh black truffle and a crystal of fleur de sel.",
      "Serve immediately chilled; the cucumber's freshness contrasts with truffle's earthiness."]),
    ("butter","cucumber","vanilla",
     "Butter and cucumber share hexanal and trace linalool — green aldehyde and herbal terpene compounds — while vanilla's vanillin and delta-decalactone provide a sweet-lactonic counterpoint to cucumber's cool freshness. Butter carries vanilla's volatile aromatics and extends cucumber's delicate aldehydes on the palate.",
     "Vanilla Cucumber Butter Gazpacho",
     ["Blend peeled cucumber with vanilla-infused cream, olive oil, and a touch of lemon.",
      "Season with white pepper and salt; chill thoroughly.",
      "Serve in chilled cups with a drizzle of vanilla oil and thin cucumber ribbons."]),
    ("butter","garlic","lamb",
     "Butter, garlic, and lamb form the classic roasting trinity: butter converts garlic's allicin into sweet cooked-garlic notes, butter's butyric acid bridges dairy fat to lamb's animal fat, and roasted garlic's dimethyl sulfide aligns with lamb's own sulfurous compound family. The trio defines the flavor of roasted leg of lamb worldwide.",
     "Garlic Butter Roast Leg of Lamb",
     ["Stud the leg of lamb with garlic slivers; rub all over with softened butter and herbs.",
      "Roast at 425 degrees F for 20 minutes, then reduce to 325 degrees F for 1.5 hours.",
      "Rest 20 minutes; make a pan sauce by deglazing with white wine and whisking in cold butter."]),
    ("butter","garlic","lavender",
     "Butter and garlic share diacetyl and dimethyl sulfide — buttery-sulfurous compounds — while lavender's linalool provides the Provençal floral counterweight that softens garlic's allicin into something more aromatic and less pungent. Butter's fat carries lavender's terpenes far longer on the palate.",
     "Lavender Garlic Compound Butter",
     ["Beat softened butter with roasted garlic paste, dried lavender, and a drizzle of lavender honey.",
      "Roll in plastic wrap to form a log; refrigerate until firm.",
      "Slice over grilled chicken, lamb chops, or warm crusty bread."]),
    ("butter","garlic","lemon",
     "Butter and garlic share dimethyl sulfide and diacetyl — buttery-sulfurous compounds that together define meunière butter — while lemon's citric acid brightens garlic's allicin into something more alert and cuts through butter's richness simultaneously. The trio drives lemon butter garlic sauce across every cuisine.",
     "Lemon Garlic Brown Butter",
     ["Brown butter until deeply nutty; add sliced garlic and cook until golden.",
      "Add a generous squeeze of lemon juice and zest; the butter will sizzle dramatically.",
      "Spoon immediately over fish, vegetables, or pasta; the acid stops the browning perfectly."]),
    ("butter","garlic","mint",
     "Butter and garlic share dimethyl sulfide and diacetyl — buttery-sulfurous compounds — while mint's menthol provides the cooling contrast that suppresses garlic's harshest allicin through olfactory competition. Butter extends mint's volatile menthol compounds far longer than water. The trio is a classic Middle Eastern lamb butter.",
     "Mint Garlic Compound Butter",
     ["Beat softened butter with roasted garlic, finely chopped fresh mint, and lemon zest.",
      "Roll in plastic wrap to form a log; refrigerate until firm.",
      "Slice over grilled lamb, new potatoes, or steamed vegetables just before serving."]),
    ("butter","garlic","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds — while garlic's dimethyl sulfide amplifies the already-sulfurous butter-oyster combination and butter converts garlic's allicin into sweet notes that complement the brine. The trio defines garlic butter baked oysters worldwide.",
     "Garlic Butter Baked Oysters",
     ["Blend softened butter with minced garlic, parsley, lemon zest, and a pinch of cayenne.",
      "Place a generous knob on each shucked oyster in its half-shell on a baking tray.",
      "Broil 4 minutes until butter is bubbling; serve immediately with crusty bread."]),
    ("butter","garlic","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while garlic's dimethyl sulfide shares the sulfurous family with both. Butter emulsifies Parmesan's fat-soluble compounds and converts garlic's allicin into sweet roasted notes. The trio is the base of garlic bread and pasta aglio e olio.",
     "Garlic Parmesan Brown Butter Pasta",
     ["Brown butter until nutty; add sliced garlic and cook until golden.",
      "Toss hot pasta in the garlic brown butter with finely grated Parmesan and pasta water.",
      "Serve immediately with more Parmesan and cracked pepper."]),
    ("butter","garlic","rose",
     "Butter and garlic share dimethyl sulfide and diacetyl — buttery-sulfurous compounds — while rose's 2-phenylethanol is carried and amplified by butter's fat, providing floral brightness that contrasts garlic's pungency. The three create an unusual but refined compound butter for special occasion dishes.",
     "Rose Garlic Compound Butter",
     ["Beat softened butter with roasted garlic paste and a few drops of rose water.",
      "Add crushed dried rose petals and a pinch of flaky salt; mix until smooth.",
      "Roll in plastic wrap; refrigerate until firm. Serve over lamb or warm brioche."]),
    ("butter","garlic","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatic compounds connecting dairy and marine fat — while garlic's dimethyl sulfide amplifies the already-sulfurous combination and butter converts garlic's allicin into sweet notes that complement salmon's richness. The trio defines classic salmon with garlic butter.",
     "Garlic Butter Basted Salmon",
     ["Heat butter in an oven-safe pan until foaming; add whole crushed garlic cloves.",
      "Sear salmon skin-side down 3 minutes; flip and baste constantly with garlic butter.",
      "Finish in the oven at 400 degrees F for 6 minutes; serve with the garlic butter pan sauce."]),
    ("butter","garlic","strawberry",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while garlic's allicin provides a pungent savory contrast that butter softens into roasted notes. Butter bridges the fruit-allium gap by carrying strawberry's volatile esters and converting garlic's harshness into something gentler.",
     "Strawberry Garlic Brown Butter Toast",
     ["Make a quick compote with strawberries, balsamic, and a clove of roasted garlic; cook until jammy.",
      "Brown butter until nutty; toast thick bread in the butter until golden.",
      "Spoon the strawberry-garlic compote over the buttered toast; finish with flaky salt."]),
    ("butter","garlic","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while garlic's dimethyl sulfide and acetic acid complete the trifecta that defines Italian soffritto. Butter rounds tomato's acidity while garlic's allicin softens into sweet savory depth. The trio is Italian cooking's most fundamental flavor base.",
     "Tomato Garlic Butter Sauce",
     ["Gently cook sliced garlic in butter until just golden and fragrant.",
      "Add crushed tomatoes and simmer uncovered 30 minutes until thickened.",
      "Finish with cold butter stirred in off heat for a glossy restaurant-quality sauce."]),
    ("butter","garlic","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics that butter amplifies far beyond any other medium — while garlic's dimethyl sulfide aligns with both, creating a triple-sulfurous luxury combination where butter acts as the carrier for truffle's most volatile compounds.",
     "Truffle Garlic Compound Butter",
     ["Beat softened butter with truffle paste, roasted garlic, and flaky salt until smooth.",
      "Roll in plastic wrap to form a log; refrigerate until very firm.",
      "Slice thickly over hot pasta, risotto, steak, or warm bread immediately before serving."]),
    ("butter","garlic","vanilla",
     "Butter and garlic share diacetyl and dimethyl sulfide — buttery-sulfurous compounds — while vanilla's vanillin sweetness contrasts garlic's pungency through sweet-savory balance. Butter bridges the gap by converting garlic's allicin into sweet roasted notes that vanilla's sweetness amplifies. The trio creates a sophisticated compound butter.",
     "Vanilla Garlic Compound Butter",
     ["Roast a whole garlic head until sweet and caramelized; squeeze cloves into softened butter.",
      "Add vanilla bean seeds, a drizzle of honey, and a pinch of flaky salt; beat smooth.",
      "Serve chilled in a crock alongside warm bread; the vanilla makes the garlic taste sweeter."]),
    ("butter","lamb","lavender",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat through shared fatty-acid and sulfurous compound families — while lavender's linalool suppresses lamb's 4-methyloctanoic acid gaminess through floral aromatic displacement. Butter carries lavender's volatile terpenes more effectively than any water-based marinade.",
     "Lavender Butter Roast Lamb",
     ["Make a compound butter with softened butter, dried lavender, garlic, and thyme.",
      "Rub generously over the lamb and under the skin where possible; rest 2 hours.",
      "Roast at 325 degrees F for 1.5 hours; the lavender butter bastes the lamb as it melts."]),
    ("butter","lamb","lemon",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while lemon's citric acid suppresses lamb's 4-methyloctanoic acid gaminess through pH modification and brightens butter's richness. The three create the classic lemon-butter finish for roasted or grilled lamb.",
     "Lemon Butter Lamb Chops",
     ["Pan-sear lamb chops in butter until deeply crusted on both sides.",
      "Add whole garlic cloves; deglaze with white wine and lemon juice; reduce.",
      "Finish with cold butter and lemon zest whisked in; spoon sauce over the chops."]),
    ("butter","lamb","mint",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while mint's menthol suppresses lamb's 4-methyloctanoic acid gaminess through olfactory cooling and butter extends mint's volatile menthol compounds far longer on the palate. The trio defines refined British-style lamb.",
     "Mint Butter Lamb Rack",
     ["Beat softened butter with finely chopped fresh mint, garlic, and lemon zest.",
      "Crust the lamb rack with the mint butter and refrigerate 30 minutes before roasting.",
      "Roast at 425 degrees F for 20 minutes to medium-rare; rest 8 minutes before carving."]),
    ("butter","lamb","oyster",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while oyster's trimethylamine and dimethyl sulfide share the marine-sulfurous compound family with both. Butter mediates the animal-marine gap by carrying both ingredients' volatile compounds in its fat.",
     "Oyster Butter Braised Lamb",
     ["Brown lamb shoulder in butter until deeply caramelized on all sides.",
      "Add oyster sauce, soy, ginger, and stock; braise covered at 300 degrees F for 3 hours.",
      "Reduce braising liquid with cold butter whisked in; serve over steamed rice."]),
    ("butter","lamb","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while lamb's butyric acid and dimethyl sulfide align with both dairy ingredients through shared fatty-acid and sulfurous chemistry. The trio creates a rich Italian-style lamb gratinée.",
     "Lamb Parmesan Butter Gratin",
     ["Layer thin-sliced cooked lamb in a buttered baking dish with a Parmesan cream sauce.",
      "Top with a thick crust of grated Parmesan and butter-toasted breadcrumbs.",
      "Bake at 375 degrees F until golden and bubbling; rest 5 minutes before serving."]),
    ("butter","lamb","rose",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while rose's 2-phenylethanol suppresses lamb's 4-methyloctanoic acid through floral aromatic displacement and butter carries rose's delicate volatile compounds far more effectively than a water-based marinade.",
     "Rose Butter Braised Lamb Shoulder",
     ["Make a compound butter with softened butter, rose water, garlic, and fresh herbs.",
      "Rub the lamb shoulder with rose butter; seal in a braising pot with wine and stock.",
      "Braise at 300 degrees F for 3 hours; the rose butter perfumes the braising liquid throughout."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 020 done: inserted {len(TRIPLETS)} triplets.")
