#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("caramel","cucumber","truffle",
     "Caramel and truffle share dimethyl sulfide and phenylacetaldehyde — the Maillard-earthy luxury compound pair — while cucumber's (E)-2-nonenal provides the palate-cleansing cool freshness that prevents the rich sweet-earthy combination from being overwhelming. The trio creates an elegant luxury canapé.",
     "Truffle Caramel Cucumber Rounds",
     ["Make a light caramel with truffle honey; spread onto thick cucumber rounds.",
      "Drizzle with truffle oil and top with a small shaving of black truffle.",
      "Finish with fleur de sel; the cool cucumber contrasts the earthy-sweet luxury."]),
    ("caramel","cucumber","vanilla",
     "Caramel and vanilla share vanillin and furaneol — the sweet-Maillard compound pair — while cucumber's (E)-2-nonenal provides the palate-cleansing cool freshness that prevents the sweet combination from being one-dimensional. Cucumber's watery green makes vanilla's sweetness feel lighter.",
     "Vanilla Caramel Cucumber Panna Cotta",
     ["Make a vanilla panna cotta with split vanilla bean and caramelized sugar; set in molds.",
      "Make a cucumber-lime coulis; keep very cold.",
      "Unmold panna cotta; spoon cold cucumber coulis around the base; the contrast is elegant."]),
    ("caramel","garlic","lamb",
     "Caramel's Maillard sweetness suppresses lamb's 4-methyloctanoic acid gaminess while garlic's dimethyl sulfide aligns with lamb's own sulfurous compounds, creating a triple-sweet-savory-allium register. Caramel's sweetness transforms both garlic and lamb into a lacquered luxury preparation.",
     "Caramel Garlic Glazed Lamb Rack",
     ["Make a caramel glaze with garlic, soy, mirin, and sugar; reduce to syrupy.",
      "Sear lamb rack until crusted; brush generously with caramel-garlic glaze.",
      "Roast at 400 degrees F 15 minutes; rest and serve sliced with remaining glaze."]),
    ("caramel","garlic","lavender",
     "Caramel's Maillard sweetness softens garlic's allicin pungency while lavender's linalool provides the Provençal floral note that makes the sweet-allium combination feel elegant. Together the three create a sophisticated glaze or sauce for chicken or vegetables.",
     "Lavender Caramel Garlic Chicken",
     ["Make a lavender caramel by cooking sugar to amber; add cream, garlic, and lavender; strain.",
      "Roast chicken thighs; brush with lavender caramel glaze in the last 15 minutes.",
      "Broil 3 minutes until lacquered; serve with the remaining lavender-garlic caramel sauce."]),
    ("caramel","garlic","lemon",
     "Caramel's Maillard sweetness and lemon's citric acidity create a sweet-sour balance while garlic's allicin adds pungent savory depth. Lemon's citric acid brightens caramel's richness and softens garlic's harshness into something more alert. The trio creates a complex teriyaki-style sauce.",
     "Lemon Caramel Garlic Sauce",
     ["Make a caramel; deglaze with lemon juice and roasted garlic paste; whisk smooth.",
      "Simmer until thick and glossy; adjust seasoning with salt and more lemon.",
      "Use as a dipping sauce or glaze for chicken, fish, or roasted vegetables."]),
    ("caramel","garlic","mint",
     "Caramel's Maillard sweetness softens garlic's allicin pungency through sweet-savory balance while mint's menthol provides the cooling aromatic contrast that suppresses both garlic's harshness and makes the caramel's warmth feel more pronounced. The trio creates a Middle Eastern-inflected glaze.",
     "Mint Caramel Garlic Lamb Kebabs",
     ["Make a mint caramel marinade with garlic, honey, and fresh mint; marinate lamb overnight.",
      "Thread onto skewers; grill over high heat, turning to char on all sides.",
      "Brush with remaining mint caramel glaze in the last 2 minutes; serve with mint yogurt."]),
    ("caramel","garlic","oyster",
     "Caramel's Maillard sweetness creates sweet-brine contrast with oyster's trimethylamine while garlic's dimethyl sulfide shares the sulfurous family with oyster's marine compounds. The three together create a Chinese-style oyster sauce-inspired preparation where caramel balances both brine and pungency.",
     "Caramel Garlic Oyster Stir-fry",
     ["Make a caramel glaze with garlic, oyster sauce, soy, and sugar; reduce to syrupy.",
      "Shuck oysters; sauté briefly in hot oil until edges begin to curl.",
      "Add caramel-garlic glaze and toss quickly; serve over steamed rice immediately."]),
    ("caramel","garlic","parmesan",
     "Caramel and Parmesan share furaneol — the sweet-caramel compound spanning Maillard and aged-dairy fermentation — while garlic's dimethyl sulfide adds allium pungency that Parmesan's glutamates amplify into a richer umami. Caramel's sweetness softens garlic while deepening Parmesan's savory notes.",
     "Caramelized Garlic Parmesan Focaccia",
     ["Make focaccia dough; dimple the surface and drizzle with olive oil before baking.",
      "Top with slowly caramelized garlic cloves and caramelized onions.",
      "Scatter finely grated Parmesan over the top; bake at 425 degrees F until golden."]),
    ("caramel","garlic","rose",
     "Caramel's Maillard sweetness and rose's 2-phenylethanol create a floral-sweet combination while garlic's allicin pungency provides the sharp savory contrast. Caramel's sweetness mediates the floral and allium extremes while rose's delicate florals soften garlic into a more aromatic register.",
     "Rose Caramel Garlic Flatbread",
     ["Make a caramel with garlic and rose water; reduce until thick and fragrant.",
      "Brush over warm flatbread and top with roasted garlic cloves.",
      "Scatter dried rose petals and flaky salt; the sweet-floral-allium combination is surprising."]),
    ("caramel","garlic","salmon",
     "Caramel's Maillard glaze suppresses salmon's trimethylamine while garlic's dimethyl sulfide shares the sulfurous family with salmon's compounds. Together caramel and garlic create a teriyaki-style preparation where the sweet-allium combination seals salmon's fat-soluble aromatics.",
     "Caramel Garlic Teriyaki Salmon",
     ["Make a caramel teriyaki sauce with garlic, soy, mirin, and sugar.",
      "Sear salmon skin-side down; flip and pour the caramel-garlic teriyaki over.",
      "Cook until glaze reduces and lacquers the salmon; serve with steamed rice and sesame."]),
    ("caramel","garlic","strawberry",
     "Caramel and strawberry share furaneol — the sweet-caramel compound — while garlic's pungency provides a sharp savory contrast. Caramel's sweetness mediates the fruit-allium tension while strawberry's fresh acidity cuts through garlic's heaviness into an unexpected sweet-savory combination.",
     "Strawberry Caramel Garlic Compote",
     ["Slowly caramelize sliced garlic until sweet and golden; add sliced strawberries.",
      "Cook with balsamic and caramel until jammy and concentrated; season with salt.",
      "Serve over burrata, grilled meats, or warm sourdough toast."]),
    ("caramel","garlic","tomato",
     "Caramel, garlic, and tomato share furaneol and dimethyl sulfide — sweet-caramel and sulfurous compounds — while caramel's Maillard sweetness deepens slow-roasted tomato and transforms caramelized garlic into sweet, round cooked-allium notes. The three create a refined Italian-style caramelized tomato sauce.",
     "Caramelized Garlic Tomato Sauce",
     ["Slowly caramelize garlic cloves in olive oil with a pinch of sugar until golden.",
      "Add crushed tomatoes and a drizzle of caramel; simmer 30 minutes until thick.",
      "Toss with pasta; the caramelized garlic and caramel deepen the tomato's sweetness."]),
    ("caramel","garlic","truffle",
     "Caramel and truffle share dimethyl sulfide and phenylacetaldehyde — the Maillard-earthy luxury compound pair — while garlic's dimethyl sulfide aligns with both, creating a triple-sulfurous register. Caramel's sweetness rounds truffle's earthiness while garlic adds allium pungency.",
     "Truffle Caramel Garlic Compound Butter",
     ["Beat softened butter with truffle paste, roasted garlic, and a drizzle of caramel.",
      "Season with flaky salt; roll in plastic wrap and refrigerate until firm.",
      "Slice over hot pasta or grilled steak; the caramel rounds the truffle and garlic."]),
    ("caramel","garlic","vanilla",
     "Caramel and vanilla share vanillin and furaneol — the sweet-Maillard compound pair — while garlic's allicin creates a sharp savory contrast. Vanilla's sweetness softens garlic's pungency while caramel's warmth amplifies both. The trio creates an unusual sweet-allium compound.",
     "Vanilla Caramel Roasted Garlic Spread",
     ["Roast whole garlic heads until caramelized and sweet; squeeze into softened butter.",
      "Add vanilla bean seeds, caramelized sugar, and a drizzle of honey; mix smooth.",
      "Spread on warm bread; the vanilla amplifies the sweetness of caramelized garlic."]),
    ("caramel","lamb","lavender",
     "Caramel's Maillard sweetness suppresses lamb's 4-methyloctanoic acid gaminess while lavender's linalool provides the Provençal floral note that softens both the caramel's richness and lamb's heavy fat. The trio creates an elegant lacquered lamb preparation.",
     "Lavender Caramel Glazed Lamb",
     ["Make a lavender caramel glaze with sugar, cream, and dried lavender; strain.",
      "Sear lamb until deeply crusted; brush with lavender caramel glaze.",
      "Roast to medium-rare; rest 5 minutes and serve with the remaining glaze."]),
    ("caramel","lamb","lemon",
     "Caramel's Maillard sweetness suppresses lamb's gaminess while lemon's citric acid provides a direct contrast to caramel's sweetness — creating a sour-sweet balance — and suppresses lamb's 4-methyloctanoic acid through pH modification. The three together create a refined lacquered lamb with citrus.",
     "Lemon Caramel Glazed Lamb Chops",
     ["Make a caramel; deglaze with lemon juice and zest; reduce to a thick glaze.",
      "Sear lamb chops until deeply crusted; brush with lemon caramel glaze.",
      "Broil 2 minutes until lacquered; serve with lemon wedges and herbs."]),
    ("caramel","lamb","mint",
     "Caramel's Maillard sweetness suppresses lamb's 4-methyloctanoic acid gaminess while mint's menthol provides cooling contrast that further reduces the perception of the gamey fatty acid through olfactory competition. Together caramel and mint are the two most effective lamb gaminess suppressors.",
     "Mint Caramel Glazed Lamb Rack",
     ["Make a mint caramel by cooking sugar to amber; add cream and fresh mint; strain.",
      "Sear lamb rack until crusted; brush with mint caramel glaze.",
      "Roast at 425 degrees F for 18 minutes to medium-rare; rest and serve sliced."]),
    ("caramel","lamb","oyster",
     "Caramel's Maillard sweetness contrasts both lamb's animal-fat richness and oyster's marine brine through sweet-savory balance — creating a dish where caramel is the unifying bridge between two very different proteins. The trio creates a bold surf-and-turf preparation.",
     "Caramel Oyster Sauce Braised Lamb",
     ["Brown lamb shoulder pieces; build a braise with caramel, oyster sauce, soy, and ginger.",
      "Braise covered at 300 degrees F for 3 hours until falling apart tender.",
      "Reduce braising liquid until glossy; serve over steamed rice with fresh herbs."]),
    ("caramel","lamb","parmesan",
     "Caramel and Parmesan share furaneol — the sweet-caramel compound — while lamb's butyric acid and dimethyl sulfide align with Parmesan's dairy-fat chemistry. Caramel's sweetness suppresses lamb's gaminess while Parmesan's glutamates amplify the savory depth.",
     "Caramel Parmesan Lamb Gratin",
     ["Layer thin-sliced braised lamb with a caramel-Parmesan cream sauce in a baking dish.",
      "Top with grated Parmesan and a drizzle of caramel; bake at 375 degrees F until bubbling.",
      "Broil 3 minutes until golden; rest 5 minutes before serving."]),
    ("caramel","lamb","rose",
     "Caramel's Maillard sweetness suppresses lamb's 4-methyloctanoic acid through sweet-savory balance while rose's 2-phenylethanol suppresses the same gamey acid through floral aromatic displacement — double-suppression of lamb's gamiest compound. The trio creates the most refined possible Persian-style lamb.",
     "Rose Caramel Braised Lamb Shoulder",
     ["Brown lamb shoulder; braise with rose water, caramel, saffron, and preserved lemon.",
      "Cook at 300 degrees F for 3 hours; the rose-caramel combination fully suppresses gaminess.",
      "Reduce braising liquid; serve with saffron rice, fresh herbs, and pomegranate."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 026 done: inserted {len(TRIPLETS)} triplets.")
