#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("butter","lemon","strawberry",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while lemon's citric acid sharpens strawberry's acidity into a brighter register and geraniol reinforces strawberry's own floral esters. Butter carries strawberry's volatile esters and emulsifies lemon's acidity into a silky sauce.",
     "Lemon Strawberry Brown Butter Tart",
     ["Brown butter until deeply nutty; make a shortcrust pastry with the browned butter.",
      "Fill with a lemon curd; arrange sliced strawberries across the top.",
      "Drizzle with browned butter caramel; the lemon acid brightens the strawberry's sweetness."]),
    ("butter","lemon","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while lemon's citric acid brightens tomato's acidity into a sharper register. Butter rounds tomato's acidity (Marcella Hazan's principle) while lemon's geraniol adds floral brightness to the finished sauce.",
     "Lemon Butter Tomato Pasta",
     ["Make a quick tomato sauce; finish with cold butter whisked in off heat until glossy.",
      "Add a generous squeeze of lemon juice and lemon zest just before tossing with pasta.",
      "The lemon brightens the butter-tomato sauce into something more vivid and alive."]),
    ("butter","lemon","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics — while lemon's citric acid cuts through truffle butter's richness and geraniol provides floral brightness that lifts truffle's earthiness into a more vertical aromatic register. The trio creates the most elegant truffle preparation.",
     "Lemon Truffle Butter Tagliolini",
     ["Cook fresh tagliolini al dente; make a sauce with truffle butter, lemon juice, and pasta water.",
      "Toss vigorously off heat until a glossy, emulsified sauce forms.",
      "Plate, shave fresh truffle over, finish with lemon zest and serve immediately."]),
    ("butter","lemon","vanilla",
     "Butter, lemon, and vanilla share geraniol and furaneol — citrus-floral and sweet-caramel compounds — creating an unusually complete aromatic overlap for a dessert preparation. Butter carries both lemon's volatile geraniol and vanilla's volatile vanillin, amplifying both simultaneously.",
     "Vanilla Lemon Butter Cake",
     ["Beat softened butter with sugar until pale; add vanilla bean seeds and lemon zest.",
      "Incorporate eggs, then flour; bake at 350 degrees F in a loaf pan until golden.",
      "Soak warm cake with lemon-vanilla syrup for maximum moisture and fragrance."]),
    ("butter","mint","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds — while mint's menthol provides the palate-cleansing cooling contrast that butter extends on the palate far longer than water. Together the three create a refreshing oyster preparation where butter mediates the marine-herb gap.",
     "Mint Butter Oyster Shooters",
     ["Make a mint butter by blending softened butter with fresh mint and lemon.",
      "Place a small knob on each shucked oyster; broil 2 minutes until just melted.",
      "Top with a tiny fresh mint leaf; serve immediately while butter is still foaming."]),
    ("butter","mint","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while mint's menthol provides the cooling contrast that butter extends on the palate, making the rich dairy combination taste lighter and more refreshing. The trio creates an Italian-style pea-mint pasta.",
     "Mint Parmesan Brown Butter Gnocchi",
     ["Cook potato gnocchi until they float; transfer to a pan with brown butter.",
      "Toss with finely grated Parmesan and freshly chopped mint; add pasta water to emulsify.",
      "Plate immediately with more Parmesan and a fresh mint garnish."]),
    ("butter","mint","rose",
     "Butter and mint share trace linalool — butter's fat carries mint's volatile terpenes — while rose's 2-phenylethanol and linalool reinforce mint's herbal terpene character. Butter carries both herbs' volatile compounds simultaneously, creating a perfumed cooling compound butter.",
     "Rose Mint Compound Butter",
     ["Beat softened butter with finely chopped fresh mint and a few drops of rose water.",
      "Add a drizzle of rose honey and a pinch of flaky salt; mix until smooth.",
      "Roll in plastic wrap, refrigerate until firm; serve on scones or lamb."]),
    ("butter","mint","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatic compounds — while mint's menthol suppresses salmon's trimethylamine through olfactory cooling and butter extends mint's volatile menthol compounds far longer on the palate. The trio creates a refined herb butter for salmon.",
     "Mint Butter Basted Salmon",
     ["Make a mint compound butter with softened butter, fresh mint, lemon, and capers.",
      "Pan-sear salmon skin-side down until crispy; flip and top with mint butter.",
      "Baste constantly with the melting mint butter; serve immediately while fragrant."]),
    ("butter","mint","strawberry",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while mint's menthol provides the cooling contrast that makes strawberry taste brighter and more intense. Butter carries both strawberry's volatile esters and mint's volatile menthol more effectively than water.",
     "Mint Strawberry Brown Butter Shortcakes",
     ["Brown butter until deeply nutty; make fluffy biscuits using the browned butter.",
      "Macerate sliced strawberries with sugar, fresh mint, and a squeeze of lemon.",
      "Split warm biscuits; fill with whipped cream and the mint-strawberry compote."]),
    ("butter","mint","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while mint's menthol provides the cooling contrast that butter extends on the palate. Butter rounds tomato's acidity while mint adds the cool herbal register to the classic Italian base.",
     "Mint Tomato Brown Butter Pasta",
     ["Brown butter until nutty; add halved cherry tomatoes and sauté until they burst.",
      "Toss with al dente pasta and a splash of pasta water to emulsify.",
      "Stir in torn fresh mint at the last moment; serve with Parmesan and pepper."]),
    ("butter","mint","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics — while mint's menthol provides a palate-cleansing cooling contrast that prevents truffle butter from becoming too dense. Butter carries both truffle's earthy compounds and mint's volatile menthol simultaneously.",
     "Truffle Mint Butter Tagliatelle",
     ["Cook fresh tagliatelle al dente; make a sauce from truffle butter with finely chopped mint.",
      "Toss pasta in the sauce with pasta water until glossy; the mint lifts the truffle.",
      "Plate immediately; shave truffle over and add a fresh mint leaf garnish."]),
    ("butter","mint","vanilla",
     "Butter, mint, and vanilla share delta-decalactone and linalool — lactonic and terpene compounds — while mint's menthol provides the cooling contrast that makes vanilla's warmth feel more pronounced by comparison. Butter carries both vanilla's volatile vanillin and mint's volatile menthol simultaneously.",
     "Vanilla Mint Butter Cookies",
     ["Cream butter with powdered sugar; add vanilla bean seeds and finely chopped fresh mint.",
      "Mix in flour to form a soft dough; roll and cut into rounds.",
      "Bake at 325 degrees F until just set; the mint and vanilla contrast in every bite."]),
    ("butter","oyster","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while oyster's dimethyl sulfide and trimethylamine share the sulfurous-marine compound family with both. Butter emulsifies Parmesan's umami and carries oyster's volatile marine compounds simultaneously.",
     "Oyster Parmesan Butter Gratin",
     ["Mix softened butter with finely grated Parmesan, breadcrumbs, and lemon zest.",
      "Place on each shucked oyster in the half-shell and broil 4 minutes until golden.",
      "Serve immediately; the Parmesan butter forms a golden crust over the briny oyster."]),
    ("butter","oyster","rose",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds — while rose's 2-phenylethanol provides the floral counterweight that suppresses oyster's trimethylamine through aromatic displacement. Butter carries rose's volatile compounds and amplifies oyster's aromatic compounds.",
     "Rose Butter Poached Oysters",
     ["Make a beurre blanc with rose water, white wine, and shallots; whisk in cold butter.",
      "Add shucked oysters to the warm rose butter and poach very gently for 1 minute.",
      "Serve in their shells with the rose butter spooned over; top with rose petals."]),
    ("butter","oyster","salmon",
     "Butter, oyster, and salmon share dimethyl sulfide, trimethylamine, and butyric acid — the marine-dairy sulfurous compound family — while butter mediates the double-seafood combination by carrying both proteins' volatile aromatics and emulsifying them into a unified sauce medium.",
     "Oyster Salmon Butter Spaghetti",
     ["Shuck oysters and reserve liquor; pan-sear salmon briefly, flake into chunks.",
      "Make a butter sauce with oyster liquor, white wine, and cold butter whisked in.",
      "Toss spaghetti in the oyster-butter sauce with the salmon and oysters; serve immediately."]),
    ("butter","oyster","strawberry",
     "Butter and strawberry share furaneol — the sweet-caramel compound — while oyster's marine brine and dimethyl sulfide create a bold contrast with the sweet-dairy combination. Butter mediates the marine-fruit gap by carrying strawberry's volatile esters and rounding oyster's sharpest notes.",
     "Strawberry Butter Oyster Canapés",
     ["Make a strawberry butter by blending softened butter with fresh strawberry and balsamic.",
      "Spread onto blini or crackers; top with a freshly shucked raw oyster.",
      "Add a drop of lemon juice and flaky salt; serve immediately while cold."]),
    ("butter","oyster","tomato",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds — while tomato's furaneol sweetness contrasts oyster's brine and butter rounds tomato's acidity. Together the three create a refined coastal pasta or stew preparation.",
     "Oyster Tomato Butter Stew",
     ["Sauté garlic in butter; add crushed tomatoes and simmer 15 minutes until thickened.",
      "Add shucked oysters with their liquor; poach gently 2 minutes until edges curl.",
      "Finish with cold butter stirred in; serve over pasta or with crusty bread."]),
    ("butter","oyster","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble luxury aromatics — while oyster's dimethyl sulfide and phenylacetaldehyde share the sulfurous-rosy compound family with truffle. Butter carries both truffle's and oyster's volatile compounds simultaneously in the most effective possible medium.",
     "Truffle Butter Roasted Oysters",
     ["Make a compound butter with softened butter, truffle paste, and lemon zest.",
      "Place a generous knob on each shucked oyster in the half-shell; broil 4 minutes.",
      "Shave fresh truffle over immediately as the butter is still bubbling; serve at once."]),
    ("butter","oyster","vanilla",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds — while vanilla's vanillin sweetness suppresses oyster's trimethylamine through sweet aromatic displacement and butter carries vanilla's volatile aromatics. The trio creates a refined vanilla beurre blanc for oysters.",
     "Vanilla Butter Oyster Beurre Blanc",
     ["Reduce white wine and shallots; add vanilla bean seeds and cold butter piece by piece.",
      "Whisk until glossy and emulsified; season with salt and white pepper.",
      "Spoon over warm broiled oysters in the half-shell; serve immediately."]),
    ("butter","parmesan","rose",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while rose's 2-phenylethanol is carried and amplified by butter's fat. Rose's 2-phenylethanol also appears in Parmesan's fermentation esters, creating a triple-floral register in a dairy context.",
     "Rose Parmesan Butter Crostini",
     ["Beat softened butter with finely grated Parmesan and a few drops of rose water.",
      "Spread on toasted baguette rounds and top with a crystallized rose petal.",
      "Drizzle with rose honey; the floral notes lift Parmesan's umami beautifully."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 022 done: inserted {len(TRIPLETS)} triplets.")
