#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","coffee","garlic",
     "Blue cheese, coffee, and garlic share dimethyl sulfide, acetic acid, and phenylacetaldehyde — pungent fermented-sulfurous compounds — creating a triple-intensity savory register where each ingredient amplifies the others. Together they form an extremely bold flavor combination best used in small amounts as a compound butter or rub for grilled meats.",
     "Blue Cheese Coffee Garlic Steak Butter",
     ["Beat softened butter with crumbled blue cheese, finely ground espresso, and roasted garlic paste.",
      "Roll into a log in plastic wrap and refrigerate until firm.",
      "Slice and place over a hot grilled steak immediately before serving; the heat melts all three flavors."]),
    ("blue cheese","coffee","lamb",
     "Blue cheese, coffee, and lamb share phenylacetaldehyde and dimethyl sulfide — the fermented-animal-roasted aromatic family — creating a dense savory depth where coffee's Maillard bitterness provides a roasted crust note and blue cheese's lactic acid brightens lamb's heavy fat. The trio drives a North African-inspired coffee-spice lamb preparation.",
     "Coffee Blue Cheese Lamb Chops",
     ["Make a spice rub from finely ground espresso, smoked paprika, crumbled blue cheese, and salt.",
      "Press firmly onto lamb chops and rest 20 minutes at room temperature.",
      "Sear hard in a very hot cast-iron pan; rest and serve with a blue cheese cream sauce."]),
    ("blue cheese","coffee","lavender",
     "Blue cheese and coffee share dimethyl sulfide and phenylacetaldehyde — the pungent fermented-roasted compound set — while lavender's linalool provides a floral aromatic counterweight that softens both the cheese's ammonia and the coffee's bitterness through olfactory displacement. The trio achieves Provençal complexity.",
     "Lavender Coffee Blue Cheese Spread",
     ["Steep dried lavender in warm espresso 5 minutes; strain and cool the coffee completely.",
      "Beat softened blue cheese with the lavender-coffee and a drizzle of lavender honey.",
      "Serve on warm crusty bread or crackers as an unusual aperitivo spread."]),
    ("blue cheese","coffee","lemon",
     "Blue cheese and coffee share acetic acid and phenylacetaldehyde — the tart-fermented-roasted compound pair — while lemon's citric acid brightens both through acid-forward contrast: lemon cuts blue cheese's heaviest fat and sharpens coffee's bitter edge into something more alert. The trio creates a sophisticated savory-bright flavor.",
     "Lemon Coffee Blue Cheese Tart",
     ["Make a filling of blue cheese, cream, espresso, and lemon zest; whisk until smooth.",
      "Pour into a blind-baked pastry shell and bake at 325 degrees F until just set.",
      "Cool; top with lemon curd and crumbled blue cheese before slicing."]),
    ("blue cheese","coffee","mint",
     "Blue cheese and coffee share dimethyl sulfide and acetic acid — pungent fermented-roasted compounds — while mint's menthol provides the palate-cleansing cooling contrast that suppresses both blue cheese's ammonia and coffee's bitterness through olfactory competition. The trio creates a sophisticated after-dinner cheese-mint-coffee experience.",
     "Mint Coffee Blue Cheese Affogato",
     ["Place a scoop of blue cheese ice cream in a chilled cup; drizzle with mint syrup.",
      "Pour a hot shot of espresso over the top and let it melt the ice cream at the edges.",
      "Serve immediately with a small crumble of blue cheese on top."]),
    ("blue cheese","coffee","oyster",
     "Blue cheese, coffee, and oyster share dimethyl sulfide, acetic acid, phenylacetaldehyde, and trimethylamine — all four pungent fermented-marine-roasted compounds — creating the most extreme savory combination from three ingredients, used carefully in avant-garde cuisine as a triple umami amplifier.",
     "Coffee Roasted Oysters with Blue Cheese",
     ["Mix crumbled blue cheese with finely ground espresso and breadcrumbs.",
      "Place a small amount on each shucked oyster in the half-shell; drizzle with olive oil.",
      "Broil 3 minutes until golden and oyster edges just begin to curl; serve immediately."]),
    ("blue cheese","coffee","parmesan",
     "Blue cheese and Parmesan share nearly identical aged-dairy compound sets — butyric acid, phenylacetaldehyde, dimethyl sulfide — while coffee's Maillard furfural and acetic acid add a roasted-bitter third register that deepens the double-dairy umami. The trio creates an intense savory triple-intensity flavor for crostini and spreads.",
     "Coffee Blue Parmesan Crostini",
     ["Reduce espresso with butter and a splash of balsamic to a thick coffee glaze.",
      "Toast baguette rounds; spread with blue cheese and drizzle with coffee glaze.",
      "Finish with finely grated Parmesan and cracked pepper; serve immediately."]),
    ("blue cheese","coffee","rose",
     "Blue cheese and coffee share phenylacetaldehyde — the rosy-floral compound linking fermented dairy and high-quality arabica — while rose amplifies this shared floral register with its dominant 2-phenylethanol, creating a triple-floral-roasted-funky combination where the flower softens both the cheese and the coffee simultaneously.",
     "Rose Coffee Blue Cheese Panna Cotta",
     ["Warm cream with espresso and a splash of rose water; add crumbled blue cheese and stir until smooth.",
      "Dissolve gelatin, pour into molds, refrigerate 4 hours until set.",
      "Unmold; serve with crystallized rose petals and a drizzle of coffee caramel."]),
    ("blue cheese","coffee","salmon",
     "Blue cheese, coffee, and salmon share dimethyl sulfide — the sulfurous compound linking all three through fermented dairy, roasted bean, and marine fat — while coffee's Maillard crust suppresses salmon's trimethylamine and blue cheese's phenylacetaldehyde creates a fermented savory depth that unifies the trio.",
     "Coffee Blue Cheese Crusted Salmon",
     ["Mix finely ground espresso, crumbled blue cheese, and breadcrumbs into a paste.",
      "Press crust onto salmon fillets and bake at 400 degrees F for 12 minutes until set.",
      "Serve with a coffee-blue cheese cream sauce and fresh herbs."]),
    ("blue cheese","coffee","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound in both — while coffee's furfural and Maillard products reinforce this shared sweet-roasted register. Strawberry's fresh acidity cuts through blue cheese's ammonia and coffee's bitterness simultaneously, making the trio taste brighter than the sum of its parts.",
     "Strawberry Coffee Blue Cheese Pavlova",
     ["Bake a meringue base and cool completely; spread with mascarpone whipped with espresso.",
      "Macerate strawberries with a touch of sugar and balsamic; pile generously over the cream.",
      "Crumble a small amount of blue cheese over the top; the sweet-funky contrast is intentional."]),
    ("blue cheese","coffee","tomato",
     "Blue cheese, coffee, and tomato share furaneol and acetic acid — sweet-caramel and tart compounds that all three produce through fermentation and ripening — creating a triple-layered savory-sweet-funky combination used in complex pizza and pasta sauce preparations where depth is the goal.",
     "Coffee Blue Cheese Tomato Pizza",
     ["Make a sauce from crushed tomatoes reduced with espresso until thick and deeply flavored.",
      "Spread on pizza dough; top with crumbled blue cheese before baking at 500 degrees F.",
      "Finish with fresh arugula and a drizzle of balsamic reduction right after baking."]),
    ("blue cheese","coffee","truffle",
     "Blue cheese, coffee, and truffle share dimethyl sulfide, phenylacetaldehyde, and anisaldehyde — the complete pungent-roasted-earthy compound triad — creating the most complex savory aromatic combination of any three non-meat ingredients. Together they form an extraordinary depth used in minute quantities for luxury preparations.",
     "Truffle Coffee Blue Cheese Butter",
     ["Beat softened butter with crumbled blue cheese, truffle paste, and finely ground espresso.",
      "Season with a pinch of flaky salt; roll in plastic wrap and refrigerate until firm.",
      "Slice thickly over hot pasta or risotto for an intensely aromatic luxury finish."]),
    ("blue cheese","coffee","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol — the rosy compound — while coffee and vanilla share vanillin — the sweet compound — creating a three-ingredient network where each pair overlaps on a different compound. Together they form a complete triangle: rosy, sweet, and bitter-funky all interconnected.",
     "Vanilla Coffee Blue Cheese Tiramisu",
     ["Make mascarpone cream with vanilla bean, a touch of blue cheese, and whipped eggs.",
      "Soak ladyfingers briefly in strong espresso; layer with the blue cheese mascarpone cream.",
      "Dust with cocoa powder and refrigerate overnight; the blue cheese deepens the dairy register."]),
    ("blue cheese","cucumber","garlic",
     "Blue cheese and garlic share dimethyl sulfide and acetic acid — sulfurous and tart compounds creating a pungent double-allium-dairy intensity — while cucumber's hexanal and (E)-2-nonenal provide the palate-cleansing freshness that resets between each bite of the funky and pungent combination. The trio creates a refined tzatziki variant.",
     "Blue Cheese Garlic Cucumber Dip",
     ["Blend room-temperature blue cheese with roasted garlic, lemon juice, and cream until smooth.",
      "Fold in finely grated cucumber that has been squeezed very dry.",
      "Season with pepper and serve chilled with crudites, crackers, and warm pita."]),
    ("blue cheese","cucumber","lamb",
     "Blue cheese and lamb share butyric acid, dimethyl sulfide, and trimethylamine — the animal-fermented sulfurous compound family — while cucumber's cool (E)-2-nonenal and hexanal provide the palate-cleansing freshness that cuts through both the rich meat and funky cheese. The trio creates a refined Greek-style lamb platter.",
     "Lamb Blue Cheese Cucumber Flatbread",
     ["Grill or roast spiced ground lamb until charred; crumble over warm flatbread.",
      "Scatter crumbled blue cheese over the warm lamb to melt slightly from the heat.",
      "Top with thin cucumber slices, drizzle with yogurt and honey, and serve immediately."]),
    ("blue cheese","cucumber","lavender",
     "Blue cheese's butyric acid funk contrasts with cucumber's cool hexanal freshness and lavender's floral linalool — three completely distinct aromatic registers — while lavender's terpenes soften blue cheese's ammonia through floral displacement and cucumber's watery coolness provides a palate reset. The trio creates a Provençal canapé flavor.",
     "Lavender Blue Cheese Cucumber Canapés",
     ["Beat blue cheese with a few drops of lavender water and a drizzle of lavender honey.",
      "Spread onto thick cucumber rounds and top with a tiny sprig of dried lavender.",
      "Add a pinch of flaky salt and serve immediately chilled on a slate board."]),
    ("blue cheese","cucumber","lemon",
     "Blue cheese and lemon share acetic acid and citric compounds — both contributing tartness — while cucumber's hexanal provides the fresh green aldehyde that resets the palate between the funky cheese and the sharp citrus. Lemon's citric acid cuts through blue cheese's heaviest fat and brightens the cucumber's delicate flavor.",
     "Lemon Blue Cheese Cucumber Soup",
     ["Blend peeled cucumber with blue cheese, lemon juice, yogurt, and garlic until smooth.",
      "Season with white pepper, a drizzle of olive oil, and adjust acidity with more lemon.",
      "Serve very cold in chilled bowls with cucumber ribbons, lemon zest, and dill."]),
    ("blue cheese","cucumber","mint",
     "Blue cheese's ammonia edge is directly suppressed by mint's menthol through olfactory competition — the strongest version of the palate-cooling mechanism — while cucumber's (E)-2-nonenal provides watery freshness that further dilutes the blue cheese's intensity. Together the three create a refined summer cheese dip.",
     "Mint Cucumber Blue Cheese Dip",
     ["Blend room-temperature blue cheese with finely chopped fresh mint and grated cucumber (squeezed dry).",
      "Add a squeeze of lemon and a drizzle of olive oil; adjust seasoning with salt and pepper.",
      "Serve chilled with vegetable crudites and warm flatbread for dipping."]),
    ("blue cheese","cucumber","oyster",
     "Blue cheese and oyster share phenylacetaldehyde, dimethyl sulfide, and trimethylamine — the pungent fermented-marine compound set — while cucumber's clean (E)-2-nonenal and hexanal provide the palate-cleansing freshness that makes each bite of the intense combination feel new. The trio creates a bold raw bar preparation.",
     "Blue Cheese Oyster Cucumber Shooter",
     ["Blend peeled cucumber with white wine vinegar and a small amount of crumbled blue cheese.",
      "Season with white pepper and strain until smooth; chill thoroughly.",
      "Shuck oysters into shot glasses; top with the blue cheese-cucumber water and serve immediately."]),
    ("blue cheese","cucumber","parmesan",
     "Blue cheese and Parmesan share butyric acid, phenylacetaldehyde, and dimethyl sulfide — doubled aged-dairy umami — while cucumber's (E)-2-nonenal freshness provides palate relief between each rich cheesy bite. The combination works as an elevated cheese-and-crudite preparation where cucumber's coolness counterbalances the dairy intensity.",
     "Blue Parmesan Cucumber Crisps",
     ["Mix finely grated Parmesan with crumbled blue cheese and a pinch of cayenne.",
      "Press small mounds onto a parchment-lined tray and bake at 375 degrees F until lacy and golden.",
      "Cool until crisp; serve over thin cucumber slices with a drizzle of honey."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 012 done: inserted {len(TRIPLETS)} triplets.")
