#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","caramel","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound in ripe strawberry that also forms in aged cheese fermentation — while caramel amplifies this shared compound with its own Maillard furaneol, creating a self-reinforcing sweet register that blue cheese's butyric acid funk makes savory and complex rather than one-dimensional.",
     "Strawberry Caramel Blue Cheese Flatbread",
     ["Bake a thin flatbread until crispy; top immediately with crumbled blue cheese to melt from residual heat.",
      "Arrange halved fresh strawberries and drizzle with warm dark caramel sauce.",
      "Add torn fresh basil or mint, a crack of pepper, and serve before the cheese resets."]),
    ("blue cheese","caramel","tomato",
     "Blue cheese and tomato share acetic acid and trace hexanal — the tart-green compound pair — while caramel's Maillard sweetness transforms roasted tomato's furaneol into a deeper, richer register where blue cheese's funk reads as sophisticated savory depth rather than sharpness. The trio creates a complex pizza or tart flavor.",
     "Caramelized Tomato Blue Cheese Tart",
     ["Roast halved cherry tomatoes with olive oil and a pinch of sugar until caramelized and jammy.",
      "Spread crumbled blue cheese across a blind-baked pastry shell as the base layer.",
      "Arrange caramelized tomatoes over the cheese and bake at 375 degrees F until bubbling."]),
    ("blue cheese","caramel","truffle",
     "Blue cheese and truffle share phenylacetaldehyde, dimethyl sulfide, and anisaldehyde — the most powerful fermented-earthy aromatic compound set — while caramel's Maillard furaneol sweetness creates the third register that balances and amplifies both luxury ingredients. The trio is the ultimate savory-sweet luxury flavor combination.",
     "Truffle Caramel Blue Cheese Pizza",
     ["Stretch pizza dough thin; brush with truffle oil and bake at 500 degrees F until crisp.",
      "Immediately top with crumbled blue cheese and drizzle with dark caramel.",
      "Shave fresh black truffle over the top and serve before the caramel hardens."]),
    ("blue cheese","caramel","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol and trace vanillin — rosy and sweet compounds at opposite ends of the funky-sweet spectrum — while caramel's furaneol bridges both, sharing a sweet lactonic overlap with vanilla while its Maillard bitterness tempers blue cheese's sharpest ammonia notes. The three create a refined cheesecake flavor.",
     "Vanilla Caramel Blue Cheese Ice Cream",
     ["Make a vanilla custard base; off heat stir in crumbled blue cheese until just melted.",
      "Cool completely, churn in an ice cream maker; drizzle salted caramel in during the last minute.",
      "Freeze until firm; serve with extra caramel and crushed walnuts."]),
    ("blue cheese","chocolate","coffee",
     "Blue cheese, chocolate, and coffee share phenylacetaldehyde, dimethyl sulfide, and acetic acid — the most complete three-way overlap of fermented-roasted aromatic compounds in cooking — creating an extraordinary triple-umami bitter-funky-rich register that is simultaneously the most intense and most harmonious combination possible.",
     "Blue Cheese Mocha Mousse",
     ["Melt dark chocolate with a shot of espresso; whisk in crumbled blue cheese off heat until smooth.",
      "Fold in whipped cream gently to keep the mousse light; pour into glasses and refrigerate.",
      "Serve topped with coffee powder, a shard of dark chocolate, and a small crumble of blue cheese."]),
    ("blue cheese","chocolate","cucumber",
     "Dark chocolate's phenylacetaldehyde and rosy fermentation esters contrast with cucumber's clean hexanal freshness — bold bitter-green contrast — while blue cheese's butyric acid funk adds a savory third register that grounds the sweet-cool combination into something more complex than either pairing alone.",
     "Blue Cheese Dark Chocolate Cucumber Canapés",
     ["Melt dark chocolate; spread thinly on parchment and let set until firm.",
      "Break into shards; top each with a small amount of crumbled blue cheese.",
      "Place on thick cucumber rounds with a drop of honey and cracked pepper; serve immediately."]),
    ("blue cheese","chocolate","garlic",
     "Dark chocolate and garlic share dimethyl sulfide — the sulfurous compound linking roasted bitterness and allium pungency — while blue cheese's phenylacetaldehyde and butyric acid add a third fermented-dairy register that grounds the bold chocolate-garlic contrast into a complex savory mole-adjacent flavor.",
     "Blue Cheese Dark Chocolate Garlic Dip",
     ["Roast a whole garlic head until sweet; squeeze cloves and blend with dark chocolate and blue cheese.",
      "Add olive oil and a splash of cream to reach a smooth, dippable consistency.",
      "Serve warm with crudites, crackers, or sliced apple for a bold cheese board centerpiece."]),
    ("blue cheese","chocolate","lamb",
     "Dark chocolate, blue cheese, and lamb share phenylacetaldehyde and dimethyl sulfide — the fermented-animal-roasted compound family — creating a three-way savory depth where each ingredient amplifies the others' umami while blue cheese's lactic acid brightens lamb's heavy fat. The trio is a refined North African mole-inspired lamb preparation.",
     "Blue Cheese Dark Chocolate Lamb Kofta",
     ["Mix ground lamb with a square of grated dark chocolate, crumbled blue cheese, and spices.",
      "Form into koftas and grill over high heat until charred on the outside but still pink inside.",
      "Serve with a yogurt sauce and a grating of dark chocolate over the top."]),
    ("blue cheese","chocolate","lavender",
     "Dark chocolate and lavender share linalool and 2-phenylethanol — chocolate's fermentation florals aligning with lavender's dominant terpenes — while blue cheese's phenylacetaldehyde reinforces the rosy-floral overlap, creating a three-register floral-funky-bitter combination used in Provençal luxury confections.",
     "Lavender Blue Cheese Dark Chocolate Bark",
     ["Melt dark chocolate; spread onto parchment and scatter crumbled blue cheese across the surface.",
      "Sprinkle with dried lavender and a pinch of flaky salt before chocolate sets.",
      "Break into irregular shards once set; serve with wine as a sophisticated cheese course alternative."]),
    ("blue cheese","chocolate","lemon",
     "Dark chocolate's acidity and lemon's citric brightness reinforce each other while blue cheese's butyric acid tartness adds a third acidic note — a triple-acid bright combination that blue cheese's fermented depth and chocolate's bitter roast ground into something coherent rather than sharp. Lemon cuts blue cheese's heaviest fat.",
     "Lemon Blue Cheese Dark Chocolate Truffles",
     ["Melt dark chocolate; stir in crumbled blue cheese and lemon zest off heat until smooth.",
      "Refrigerate until firm enough to roll; shape into balls with cool hands.",
      "Roll in cocoa powder with a pinch of lemon sugar; serve at room temperature."]),
    ("blue cheese","chocolate","mint",
     "Dark chocolate and mint share 1,8-cineole — the cooling terpene connecting menthol's refreshing quality to chocolate's minor herbal compounds — while blue cheese's phenylacetaldehyde and butyric acid add a funky savory layer that prevents the classic chocolate-mint combination from being merely confectionary. The trio is sophisticated mint-chocolate.",
     "Mint Blue Cheese Dark Chocolate Cups",
     ["Melt dark chocolate; line small molds with a thin chocolate layer and refrigerate to set.",
      "Mix crumbled blue cheese with finely chopped fresh mint and a drizzle of honey.",
      "Fill each chocolate cup with the blue cheese-mint filling; top with a thin chocolate disc to seal."]),
    ("blue cheese","chocolate","oyster",
     "Blue cheese, dark chocolate, and oyster share phenylacetaldehyde, dimethyl sulfide, and trimethylamine — the complete fermented-marine-roasted compound triad — creating the most intense savory aromatic combination possible from these three ingredients. Together they form a bold umami preparation for adventurous eaters.",
     "Dark Chocolate Blue Cheese Oyster Shooter",
     ["Make a sauce from melted dark chocolate, crumbled blue cheese, and a splash of cream; blend smooth.",
      "Shuck oysters into shot glasses; top each with a spoonful of the dark chocolate-blue cheese sauce.",
      "Add a crack of pepper and a tiny crystal of flaky salt; serve immediately as a bold amuse-bouche."]),
    ("blue cheese","chocolate","parmesan",
     "Blue cheese, dark chocolate, and Parmesan share phenylacetaldehyde, butyric acid, and dimethyl sulfide — the fermented dairy and roasted cacao compound families nearly fully overlap — creating a three-tier dairy-roast umami that is extraordinarily rich and complex. The combination is an extreme version of chocolate-cheese pairing.",
     "Three-Cheese Dark Chocolate Fondue",
     ["Melt dark chocolate into warm cream; stir in crumbled blue cheese and grated Parmesan off heat.",
      "Whisk until smooth and cohesive; keep warm over very low heat.",
      "Serve with crusty bread, apple slices, and pear for dipping into the rich fondue."]),
    ("blue cheese","chocolate","rose",
     "Blue cheese, dark chocolate, and rose share 2-phenylethanol and phenylacetaldehyde — the rosy-floral compound trio that fermented dairy, cacao, and rose petals all produce independently — creating an extraordinary triple-floral register grounded by chocolate's bitter roast and blue cheese's pungent depth.",
     "Rose Blue Cheese Dark Chocolate Bark",
     ["Melt dark chocolate; spread onto parchment and let cool until nearly set.",
      "Crumble blue cheese and scatter crystallized rose petals across the surface.",
      "Break into shards once completely set; serve as a cheese course finale with sparkling wine."]),
    ("blue cheese","chocolate","salmon",
     "Dark chocolate and salmon share dimethyl sulfide — linking roasted bitterness and marine fat — while blue cheese's phenylacetaldehyde and trimethylamine share the sulfurous-marine compound family with salmon, creating a unified savory depth. The trio works as a mole-inspired sauce where chocolate and cheese are seasoning, not centerpiece.",
     "Dark Chocolate Blue Cheese Mole Salmon",
     ["Blend toasted ancho chile, garlic, dark chocolate, and blue cheese with stock until smooth.",
      "Simmer the mole until thick and glossy; season carefully with salt and acid.",
      "Sear salmon fillets; spoon the mole over the top and serve immediately with herbs."]),
    ("blue cheese","chocolate","strawberry",
     "Dark chocolate, blue cheese, and strawberry share furaneol and phenylacetaldehyde — the sweet-caramel and rosy compounds linking all three through independent fermentation pathways — while strawberry's fresh acidity cuts through both the chocolate's bitterness and blue cheese's heaviest ammonia notes. The trio creates an indulgent dessert.",
     "Strawberry Blue Cheese Dark Chocolate Pavé",
     ["Make a ganache with dark chocolate, cream, and a small amount of blue cheese whisked in; set in a lined tray.",
      "Press halved fresh strawberries in a grid across the surface before the ganache fully firms.",
      "Cut into squares; the strawberry's acid brightens both the chocolate and the cheese."]),
    ("blue cheese","chocolate","tomato",
     "Dark chocolate and tomato share furaneol — the caramel-sweet compound present in both roasted cacao and ripe tomato — while blue cheese's acetic acid and phenylacetaldehyde add a fermented savory depth that turns the sweet-umami combination into a complex mole-style sauce.",
     "Blue Cheese Dark Chocolate Tomato Sauce",
     ["Roast tomatoes until caramelized; blend with a square of dark chocolate and crumbled blue cheese.",
      "Simmer the sauce until thick and deeply flavored; adjust seasoning with salt and vinegar.",
      "Toss with short pasta and finish with Parmesan and fresh basil."]),
    ("blue cheese","chocolate","truffle",
     "Blue cheese, dark chocolate, and truffle share phenylacetaldehyde, dimethyl sulfide, and anisaldehyde — the complete fermented-earthy-roasted aromatic triad — creating the most complex savory aromatic combination from three non-meat ingredients. Together they form the pinnacle of umami layering in haute cuisine.",
     "Truffle Blue Cheese Dark Chocolate Risotto",
     ["Make a risotto base; off heat stir in dark chocolate, blue cheese, and Parmesan.",
      "Add pasta water to achieve a flowing consistency; season precisely with salt and white pepper.",
      "Plate immediately and shave generous fresh truffle over each bowl."]),
    ("blue cheese","chocolate","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol — the rosy compound that both aged dairy fermentation and vanilla curing produce — while dark chocolate's 2-phenylethanol reinforces this shared floral register. Together all three ingredients produce the same rosy-floral compound, creating a triple-source 2-phenylethanol combination unique in cooking.",
     "Vanilla Blue Cheese Dark Chocolate Pots de Creme",
     ["Steep vanilla in warm cream; add crumbled blue cheese and dark chocolate off heat; blend smooth.",
      "Whisk into egg yolks with a touch of sugar; strain and pour into ramekins.",
      "Bake in water bath at 325 degrees F until just set; refrigerate 4 hours before serving."]),
    ("blue cheese","coffee","cucumber",
     "Blue cheese and coffee share dimethyl sulfide, acetic acid, and phenylacetaldehyde — the roasted-fermented pungent compound set — while cucumber's hexanal and (E)-2-nonenal provide a clean palate-resetting freshness between the two intensities. The trio creates a sophisticated contrast where cucumber performs its cleansing function between powerful flavors.",
     "Coffee Blue Cheese Cucumber Bruschetta",
     ["Brush toasted sourdough with a thin espresso reduction; spread with room-temperature blue cheese.",
      "Top with thin cucumber slices and a drizzle of good honey.",
      "Finish with cracked pepper and a sprinkle of coffee grounds for aroma; serve immediately."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 011 done: inserted {len(TRIPLETS)} triplets.")
