#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","cucumber","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — the fermented-rosy compound pair — while cucumber's (E)-2-nonenal provides a cool watery freshness that dilutes blue cheese's heaviest ammonia notes and lets rose's delicate floral register come forward. Together the three create an elegant summer cheese preparation.",
     "Rose Cucumber Blue Cheese Canapés",
     ["Beat room-temperature blue cheese with a few drops of rose water until smooth.",
      "Spread onto thick cucumber rounds and top with a crystallized rose petal.",
      "Finish with a drizzle of rose honey and serve immediately chilled."]),
    ("blue cheese","cucumber","salmon",
     "Blue cheese, cucumber, and salmon share (E)-2-nonenal and dimethyl sulfide — marine-sulfurous and green aldehyde compounds that span fermented dairy, watery vegetable, and fatty fish — while cucumber's cooling freshness suppresses both blue cheese's ammonia and salmon's trimethylamine. The trio creates a refined Scandinavian platter flavor.",
     "Blue Cheese Cucumber Salmon Roulade",
     ["Lay thin slices of smoked salmon flat; spread with whipped blue cheese and place cucumber strips.",
      "Roll tightly, wrap in cling film, and refrigerate until firm.",
      "Slice into rounds and serve on a platter with lemon zest and fresh dill."]),
    ("blue cheese","cucumber","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound — while cucumber's hexanal coolness provides the palate-resetting freshness between each bite of funky cheese and sweet fruit. The trio creates a sophisticated summer salad where each ingredient performs a distinct flavor role: funky, sweet, and cool.",
     "Strawberry Blue Cheese Cucumber Salad",
     ["Slice strawberries and cucumber thinly; arrange on a platter alternating the two.",
      "Crumble blue cheese generously over the top.",
      "Dress with white balsamic, olive oil, and fresh mint; serve immediately."]),
    ("blue cheese","cucumber","tomato",
     "Blue cheese and tomato share acetic acid — both contributing tartness that reinforces a sour-funky-sweet balance — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that resets between the dense umami of cheese and tomato. The trio creates a Balkan-style salad flavor.",
     "Blue Cheese Cucumber Tomato Salad",
     ["Dice ripe tomatoes and cucumber; toss with olive oil, red wine vinegar, and salt.",
      "Add crumbled blue cheese and torn fresh herbs; toss gently to preserve the cheese chunks.",
      "Rest 5 minutes; the tomato juices will create a natural dressing with the cheese."]),
    ("blue cheese","cucumber","truffle",
     "Blue cheese and truffle share phenylacetaldehyde, dimethyl sulfide, and anisaldehyde — the luxury fermented-earthy compound pair — while cucumber's clean (E)-2-nonenal provides the palate-cleansing freshness between each bite of the intense dual-luxury ingredients. The trio creates an elegant avant-garde canapé.",
     "Truffle Blue Cheese Cucumber Rounds",
     ["Spread whipped blue cheese onto thick cucumber rounds.",
      "Drizzle each with truffle oil and top with a tiny shaving of fresh black truffle.",
      "Finish with a crystal of flaky salt; serve immediately as a passed appetizer."]),
    ("blue cheese","cucumber","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol and trace vanillin — the rosy-sweet compound pair — while cucumber's hexanal provides cool watery freshness that dilutes blue cheese's heaviest ammonia and lets vanilla's subtle sweetness soften the funk into something approachable. The trio is unusual but precise.",
     "Vanilla Blue Cheese Cucumber Soup",
     ["Blend peeled cucumber with blue cheese, a touch of vanilla bean paste, and cream until smooth.",
      "Season with white pepper, lemon, and adjust with cold water to a pourable consistency.",
      "Serve cold in chilled cups with a blue cheese crumble and cucumber ribbon garnish."]),
    ("blue cheese","garlic","lamb",
     "Blue cheese, garlic, and lamb share dimethyl sulfide, butyric acid, and trimethylamine — the animal-allium-fermented sulfurous compound family at maximum intensity — creating a triple-savory depth where blue cheese's lactic acid brightens lamb's fat and garlic's allicin suppresses the heaviest gamey notes. The trio defines bold Mediterranean lamb.",
     "Blue Cheese Garlic Stuffed Lamb Leg",
     ["Stud the lamb leg with garlic slivers and pockets of blue cheese pressed deep inside.",
      "Rub the outside with garlic oil and fresh herbs; roast at 325 degrees F for 2 hours.",
      "Rest 20 minutes; the blue cheese melts into the meat creating an interior richness."]),
    ("blue cheese","garlic","lavender",
     "Blue cheese and garlic share dimethyl sulfide and acetic acid — pungent fermented-allium compounds — while lavender's linalool softens blue cheese's ammonia through floral aromatic displacement and garlic's harsh allicin through a terpene-based olfactory competition. The trio achieves Provençal sophistication by balancing extreme savory with extreme floral.",
     "Lavender Garlic Blue Cheese Spread",
     ["Roast a whole garlic head until sweet; squeeze cloves and blend with blue cheese.",
      "Add a few drops of lavender water and a drizzle of lavender honey; mix smooth.",
      "Serve on warm crusty bread with fresh thyme and flaky salt."]),
    ("blue cheese","garlic","lemon",
     "Blue cheese and garlic share dimethyl sulfide and acetic acid — pungent compounds — while lemon's citric acid cuts through blue cheese's heaviest fat and softens garlic's allicin into something brighter. Together the three create the base of a bold aioli-style blue cheese sauce with acid-allium brightness.",
     "Lemon Garlic Blue Cheese Aioli",
     ["Blend blue cheese with roasted garlic, lemon juice, lemon zest, and olive oil until smooth.",
      "Adjust consistency with a little warm water; season with white pepper and flaky salt.",
      "Serve as a dipping sauce with fries, artichokes, or grilled vegetables."]),
    ("blue cheese","garlic","mint",
     "Blue cheese and garlic share dimethyl sulfide and acetic acid — pungent fermented-allium compounds — while mint's menthol suppresses blue cheese's ammonia through olfactory cooling and softens garlic's allicin through competitive aromatic displacement. The trio creates a bold-refreshing dip.",
     "Mint Garlic Blue Cheese Dressing",
     ["Blend room-temperature blue cheese with roasted garlic, fresh mint, and buttermilk.",
      "Season with white wine vinegar, black pepper, and salt; adjust thickness with more buttermilk.",
      "Serve over wedge salads or as a bold dip for buffalo wings and crudites."]),
    ("blue cheese","garlic","oyster",
     "Blue cheese, garlic, and oyster share dimethyl sulfide, acetic acid, and trimethylamine — the complete pungent fermented-marine-allium compound set — creating an extreme savory combination where garlic's aromatics suppress both blue cheese's ammonia and oyster's fishy notes into a powerful but unified flavor.",
     "Garlic Blue Cheese Gratin Oysters",
     ["Mix crumbled blue cheese with roasted garlic paste, breadcrumbs, and lemon zest.",
      "Place a generous amount on each shucked oyster in the half-shell.",
      "Broil 4 minutes until golden and bubbling; serve with crusty bread to mop the juices."]),
    ("blue cheese","garlic","parmesan",
     "Blue cheese and Parmesan share butyric acid, phenylacetaldehyde, and dimethyl sulfide — nearly identical aged-dairy compound sets — while garlic's dimethyl sulfide creates a triple-sulfurous overlap that amplifies all three ingredients' savory intensity. The trio is the flavor of the world's most powerful cheesy garlic bread.",
     "Blue Cheese Parmesan Garlic Bread",
     ["Beat softened butter with blue cheese, grated Parmesan, and roasted garlic until smooth.",
      "Spread generously on a sliced sourdough loaf; wrap in foil and bake at 375 degrees F for 20 minutes.",
      "Unwrap, broil 3 minutes until the top is golden and crispy; serve immediately."]),
    ("blue cheese","garlic","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — the fermented-rosy compound pair — while garlic's sulfurous allicin creates a bold contrast with rose's delicate florals that blue cheese bridges: the cheese's funk sits between garlic's sharpness and rose's sweetness in a three-register balance.",
     "Rose Garlic Blue Cheese Flatbread",
     ["Brush flatbread dough with garlic oil; bake at 500 degrees F until golden and charred.",
      "Top immediately with crumbled blue cheese and drizzle with rose water honey.",
      "Scatter dried rose petals and a pinch of flaky salt before serving."]),
    ("blue cheese","garlic","salmon",
     "Blue cheese, garlic, and salmon share dimethyl sulfide, trimethylamine, and acetic acid — the sulfurous-marine-allium compound family — while garlic's allicin suppresses salmon's trimethylamine and blue cheese's lactic acid brightens the fatty fish. The trio creates a bold Scandinavian-influenced baked salmon preparation.",
     "Garlic Blue Cheese Baked Salmon",
     ["Blend blue cheese with roasted garlic, lemon zest, and chopped dill into a paste.",
      "Spread over salmon fillets and bake at 400 degrees F for 12 minutes until set.",
      "Broil the last 2 minutes until the blue cheese crust is golden and bubbling."]),
    ("blue cheese","garlic","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound — while garlic's sulfurous allicin creates a bold contrast with strawberry's sweetness that blue cheese mediates: the cheese connects fruit sweetness and allium pungency through its shared compound presence with both. The trio creates a daring appetizer.",
     "Strawberry Garlic Blue Cheese Crostini",
     ["Make a quick strawberry-garlic jam by cooking sliced strawberries with garlic and balsamic until thick.",
      "Toast baguette rounds and spread with room-temperature blue cheese.",
      "Top with a spoonful of strawberry-garlic jam and cracked pepper; serve immediately."]),
    ("blue cheese","garlic","tomato",
     "Blue cheese, garlic, and tomato share acetic acid and dimethyl sulfide — the tart-sulfurous compound pair driving Italian cooking — while blue cheese's phenylacetaldehyde deepens the classic garlic-tomato combination with a fermented savory layer that elevates bruschetta into something more complex than the standard.",
     "Blue Cheese Garlic Tomato Bruschetta",
     ["Sauté garlic in olive oil until golden; add crushed tomatoes and reduce until jammy.",
      "Spread room-temperature blue cheese on toasted sourdough while still warm.",
      "Spoon the garlic-tomato mixture over the cheese; the heat melts the edges."]),
    ("blue cheese","garlic","truffle",
     "Blue cheese, garlic, and truffle share dimethyl sulfide and phenylacetaldehyde — the complete pungent-fermented-earthy compound set — creating a triple-luxury savory combination where each ingredient amplifies the others' aromatic intensity. The trio is used in high-end compound butters and pasta sauces.",
     "Truffle Garlic Blue Cheese Pasta",
     ["Cook pasta al dente; make a sauce by melting blue cheese into truffle butter with roasted garlic.",
      "Toss pasta in the sauce with a splash of pasta water to emulsify until glossy.",
      "Shave fresh truffle over the top and finish with cracked pepper and Parmesan."]),
    ("blue cheese","garlic","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol — the rosy compound — while garlic's allicin creates a pungent contrast that vanilla's vanillin sweetness directly softens through sweet-savory balance. Together the three create a sophisticated roasted garlic-vanilla-blue cheese combination for elevated cheese spreads.",
     "Vanilla Garlic Blue Cheese Spread",
     ["Roast a whole garlic head until caramelized and sweet; squeeze out all the cloves.",
      "Beat with blue cheese, vanilla bean seeds, and a drizzle of honey until smooth.",
      "Spread on warm crusty bread; the vanilla's sweetness makes the blue cheese approachable."]),
    ("blue cheese","lamb","lavender",
     "Blue cheese, lamb, and lavender share butyric acid and trace linalool — the fatty-acid and floral terpene compounds — while lavender's linalool softens both blue cheese's ammonia and lamb's gamey 4-methyloctanoic acid through floral aromatic displacement. The trio creates a refined Provençal lamb preparation.",
     "Lavender Blue Cheese Stuffed Lamb Chops",
     ["Butterfly thick lamb chops; stuff with a mixture of crumbled blue cheese and dried lavender.",
      "Secure with a toothpick; season outside with salt, pepper, and lavender salt.",
      "Sear hard on both sides in a hot pan; rest 5 minutes before serving."]),
    ("blue cheese","lamb","lemon",
     "Blue cheese, lamb, and lemon form a three-corner acid-fat-funk triangle: lemon's citric acid cuts lamb's 4-methyloctanoic acid gaminess through pH modification, lemon brightens blue cheese's heaviest fat, and blue cheese adds fermented savory depth to the classic lamb-lemon pairing. The trio defines Greek-influenced lamb.",
     "Lemon Blue Cheese Lamb Burgers",
     ["Mix ground lamb with crumbled blue cheese, lemon zest, garlic, and oregano; form into patties.",
      "Grill to medium-rare; top immediately with more crumbled blue cheese to melt.",
      "Serve in pita with lemon-yogurt sauce, cucumber, and fresh herbs."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 013 done: inserted {len(TRIPLETS)} triplets.")
