#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","oyster","tomato",
     "Blue cheese and oyster share dimethyl sulfide and phenylacetaldehyde — the pungent fermented-marine compound set — while tomato's furaneol sweetness and acetic acid provide the sweet-tart contrast that grounds both the funky and briny extremes into a coherent savory preparation. The trio creates a sophisticated coastal pasta or baked dish.",
     "Blue Cheese Oyster Tomato Bruschetta",
     ["Sauté garlic in olive oil; add cherry tomatoes until they burst; remove from heat.",
      "Add crumbled blue cheese and let melt from the residual heat; stir in shucked oysters.",
      "Cook gently 1 minute until oysters just curl; spoon over toasted sourdough immediately."]),
    ("blue cheese","oyster","truffle",
     "Blue cheese, oyster, and truffle form a complete triangle of luxury fermented-marine-earthy compounds: phenylacetaldehyde, dimethyl sulfide, trimethylamine, and anisaldehyde all appear across the three ingredients, creating the most complex savory aromatic combination in haute cuisine.",
     "Truffle Blue Cheese Oyster Tartare",
     ["Finely chop freshly shucked oysters; mix with crumbled blue cheese and truffle oil.",
      "Season with white pepper and fleur de sel; arrange in oyster half-shells.",
      "Shave fresh black truffle generously over each; serve immediately over crushed ice."]),
    ("blue cheese","oyster","vanilla",
     "Blue cheese and oyster share phenylacetaldehyde — the rosy-fermented compound — while vanilla's vanillin sweetness provides a counterpoint that softens both ingredients' harshest notes simultaneously. Vanilla suppresses blue cheese's ammonia and oyster's trimethylamine through sweet aromatic displacement. The trio creates an elegant avant-garde preparation.",
     "Vanilla Blue Cheese Baked Oysters",
     ["Make a beurre blanc with vanilla bean, white wine, and shallots; reduce until syrupy.",
      "Whisk in cold butter and a small amount of crumbled blue cheese off heat.",
      "Spoon over shucked oysters on the half-shell and bake at 400 degrees F for 5 minutes."]),
    ("blue cheese","parmesan","rose",
     "Blue cheese and Parmesan create a doubled dairy umami base — butyric acid and phenylacetaldehyde at different intensities — while rose's 2-phenylethanol amplifies Parmesan's own fermentation-derived 2-phenylethanol and softens blue cheese's ammonia through floral displacement. The trio is the most elegant possible cheese board flavor.",
     "Rose Blue Parmesan Cheese Crostini",
     ["Mix crumbled blue cheese with finely grated Parmesan and a few drops of rose water.",
      "Spread on toasted baguette rounds while still warm from the toaster.",
      "Drizzle with rose honey and scatter crystallized rose petals; serve immediately."]),
    ("blue cheese","parmesan","salmon",
     "Blue cheese, Parmesan, and salmon share dimethyl sulfide and butyric acid — the sulfurous-fatty compound family spanning two cheeses and fatty fish — while Parmesan's glutamates amplify salmon's umami and blue cheese's lactic acid brightens the preparation. The trio creates a sophisticated baked salmon with cheese crust.",
     "Blue Parmesan Crusted Salmon",
     ["Mix crumbled blue cheese with finely grated Parmesan, breadcrumbs, and lemon zest.",
      "Press firmly onto salmon fillets and bake at 400 degrees F for 12 minutes until set.",
      "Broil 2 minutes until the cheese crust is golden and bubbling; serve immediately."]),
    ("blue cheese","parmesan","strawberry",
     "Blue cheese and Parmesan share furaneol and butyric acid — sweet-caramel and fatty-acid compounds — while strawberry's furaneol aligns with both cheeses' shared sweet compound, creating a triple-furaneol register where strawberry's fresh acidity cuts through the combined dairy richness. The trio creates an unexpected but precise flavor.",
     "Strawberry Blue Parmesan Bruschetta",
     ["Dice ripe strawberries; toss with a drizzle of aged balsamic and a pinch of pepper.",
      "Toast sourdough; spread with blue cheese while still warm from the toaster.",
      "Spoon strawberries over and shave Parmesan generously on top; serve immediately."]),
    ("blue cheese","parmesan","tomato",
     "Blue cheese, Parmesan, and tomato share furaneol and acetic acid — the sweet-caramel and tart compound pair — creating a triple-layer dairy-umami-sweet-acid flavor that is simultaneously the richest and most complex version of the classic Italian cheese-tomato preparation. The three define the flavor of a sophisticated cheese pizza.",
     "Blue Parmesan Tomato Tart",
     ["Layer sliced ripe tomatoes in a blind-baked tart shell; season with salt and pepper.",
      "Crumble blue cheese over the tomatoes and scatter finely grated Parmesan on top.",
      "Bake at 375 degrees F until the cheeses melt and bubble; serve with fresh herbs."]),
    ("blue cheese","parmesan","truffle",
     "Blue cheese, Parmesan, and truffle create the most complete luxury savory flavor combination: phenylacetaldehyde, dimethyl sulfide, and anisaldehyde span all three ingredients in overlapping compound families, producing an extraordinary triple-umami preparation. The combination defines high-end Italian pasta finishing.",
     "Truffle Blue Parmesan Pasta",
     ["Cook fresh pasta; make a sauce from truffle butter, blue cheese, and Parmesan over low heat.",
      "Toss pasta in sauce with pasta water; adjust to a glossy, flowing texture.",
      "Plate and shave generous fresh truffle over; finish with more Parmesan and cracked pepper."]),
    ("blue cheese","parmesan","vanilla",
     "Blue cheese and Parmesan share 2-phenylethanol and butyric acid — the rosy-fatty compound pair — while vanilla's vanillin sweetness softens both cheeses' most intense notes simultaneously and its own 2-phenylethanol reinforces their shared rosy register. The trio creates a surprising but precise savory-sweet cheese preparation.",
     "Vanilla Blue Parmesan Cheesecake",
     ["Make a savory cheesecake filling with blue cheese, Parmesan, cream cheese, eggs, and vanilla bean.",
      "Pour over a savory cracker crust and bake in water bath at 300 degrees F until set.",
      "Cool completely; serve in thin slices with honey and fresh fruit as a cheese course finale."]),
    ("blue cheese","rose","salmon",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — the fermented-rosy compound pair — while salmon's dimethyl sulfide shares the sulfurous family with blue cheese's compounds, and rose's geraniol provides floral brightness that suppresses salmon's trimethylamine. The trio creates a delicate, aromatic salmon preparation.",
     "Rose Blue Cheese Salmon Carpaccio",
     ["Slice sushi-grade salmon paper-thin and arrange on chilled plates.",
      "Crumble a small amount of blue cheese over the salmon and drizzle with rose water oil.",
      "Scatter dried rose petals and flaky salt; serve immediately with lemon on the side."]),
    ("blue cheese","rose","strawberry",
     "Blue cheese, rose, and strawberry all produce 2-phenylethanol through independent pathways — fermented dairy, flower, and ripening fruit — creating a triple-source rosy compound register where each ingredient reinforces the same floral note while contributing its own distinct base flavor (funky, perfumed, sweet).",
     "Rose Strawberry Blue Cheese Pavlova",
     ["Bake a meringue base; spread with mascarpone cream flavored with rose water.",
      "Arrange sliced fresh strawberries macerated with a touch of rose water over the cream.",
      "Crumble a small amount of blue cheese over the top; the funk makes the sweet more interesting."]),
    ("blue cheese","rose","tomato",
     "Blue cheese and tomato share acetic acid — both contributing tartness — while rose's 2-phenylethanol provides a floral counterweight that softens blue cheese's ammonia and elevates tomato's furaneol sweetness into a more refined register. The trio creates a sophisticated Mediterranean appetizer flavor.",
     "Rose Tomato Blue Cheese Salad",
     ["Slice ripe heirloom tomatoes; arrange on a platter and season with flaky salt.",
      "Crumble blue cheese generously over; drizzle with rose water-honey vinaigrette.",
      "Scatter fresh rose petals and torn basil over the top; serve immediately."]),
    ("blue cheese","rose","truffle",
     "Blue cheese, rose, and truffle share phenylacetaldehyde and anisaldehyde — the rosy-anise compound pair that fermented dairy, rose petals, and earthy fungus all produce — creating a triple-luxury aromatic combination where each ingredient reinforces the others' most refined compounds while contributing its own base (funky, floral, earthy).",
     "Rose Truffle Blue Cheese Compound Butter",
     ["Beat softened butter with crumbled blue cheese, truffle paste, and a few drops of rose water.",
      "Add a drizzle of rose honey and a pinch of flaky salt; mix until smooth.",
      "Roll in plastic wrap, refrigerate until firm; slice over warm risotto or steak."]),
    ("blue cheese","rose","vanilla",
     "Blue cheese, rose, and vanilla all produce 2-phenylethanol — the rosy compound that fermented dairy, rose petals, and cured vanilla beans generate through entirely separate biochemical pathways — creating a rare triple-source rosy register where vanilla's vanillin sweetness grounds the floral-funky combination into something elegant.",
     "Rose Vanilla Blue Cheese Ice Cream",
     ["Make a vanilla custard base with rose water; churn in ice cream maker until creamy.",
      "Add crumbled blue cheese in the last 2 minutes of churning; keep the pieces chunky.",
      "Freeze until firm; serve with crystallized rose petals and a honey drizzle."]),
    ("blue cheese","salmon","strawberry",
     "Blue cheese and salmon share dimethyl sulfide and butyric acid — the sulfurous-fatty compound family — while strawberry's furaneol sweetness provides direct contrast to both ingredients' savory depth and its fresh acidity cuts through blue cheese's fat and salmon's richness simultaneously. The trio creates a bold Nordic-inspired preparation.",
     "Strawberry Blue Cheese Salmon Tartare",
     ["Finely dice sushi-grade salmon; mix with diced fresh strawberry and crumbled blue cheese.",
      "Add lemon juice, shallot, and a drizzle of olive oil; season with flaky salt.",
      "Serve immediately in chilled bowls with rye crackers and a strawberry balsamic drizzle."]),
    ("blue cheese","salmon","tomato",
     "Blue cheese, salmon, and tomato share furaneol and acetic acid — the sweet-caramel and tart compound pair — creating a balanced sweet-savory-marine preparation where tomato's sweetness suppresses salmon's trimethylamine and blue cheese's lactic acid brightens the overall flavor. The trio creates a sophisticated coastal pasta.",
     "Blue Cheese Salmon Tomato Pasta",
     ["Sauté cherry tomatoes until they burst; add flaked smoked salmon and crumbled blue cheese.",
      "Toss with al dente pasta and a splash of pasta water; the blue cheese creates a creamy sauce.",
      "Finish with fresh herbs and cracked pepper; serve immediately."]),
    ("blue cheese","salmon","truffle",
     "Blue cheese, salmon, and truffle share dimethyl sulfide — the sulfurous compound linking fermented dairy, marine fat, and earthy fungus — while blue cheese's phenylacetaldehyde and truffle's anisaldehyde create a luxury fermented-earthy double compound that salmon's richness grounds into a complete savory preparation.",
     "Truffle Blue Cheese Salmon Wellington",
     ["Spread salmon fillets with blue cheese and truffle paste; wrap in spinach and puff pastry.",
      "Brush with egg wash and bake at 400 degrees F for 20 minutes until deeply golden.",
      "Rest 5 minutes; slice cleanly and serve with truffle cream sauce and fresh herbs."]),
    ("blue cheese","salmon","vanilla",
     "Blue cheese and salmon share dimethyl sulfide and butyric acid — the sulfurous-fatty compound pair — while vanilla's vanillin sweetness suppresses salmon's trimethylamine and blue cheese's ammonia simultaneously through sweet aromatic displacement. The trio creates a refined poached salmon preparation.",
     "Vanilla Blue Cheese Poached Salmon",
     ["Make a court bouillon with white wine, vanilla bean, and aromatics.",
      "Poach salmon at a gentle simmer for 10 minutes; serve with a warm blue cheese-vanilla beurre blanc.",
      "The vanilla's sweetness bridges the dairy and marine registers seamlessly."]),
    ("blue cheese","strawberry","tomato",
     "Blue cheese, strawberry, and tomato all produce furaneol — the sweet-caramel compound — through three independent biochemical pathways (fermentation, fruit ripening, and vegetable ripening), creating a rare triple-furaneol register. Blue cheese's lactic tartness, strawberry's fresh sweetness, and tomato's umami balance naturally.",
     "Strawberry Tomato Blue Cheese Bruschetta",
     ["Dice ripe tomatoes and fresh strawberries; toss together with olive oil, salt, and balsamic.",
      "Toast sourdough and spread with room-temperature blue cheese while still warm.",
      "Pile the tomato-strawberry mixture on top with torn fresh herbs; serve immediately."]),
    ("blue cheese","strawberry","truffle",
     "Blue cheese, strawberry, and truffle share phenylacetaldehyde — the rosy compound spanning fermented dairy, ripe fruit fermentation esters, and earthy fungus — while truffle's dimethyl sulfide adds earthy luxury depth and blue cheese's butyric acid grounds the sweet-funky-earthy combination. The trio is an avant-garde luxury dessert.",
     "Truffle Strawberry Blue Cheese Tart",
     ["Make a filling from blue cheese, cream, and a drizzle of truffle honey; set in a tart shell.",
      "Top with sliced fresh strawberries macerated in a touch of truffle honey.",
      "Shave fresh truffle over the strawberries just before serving; serve at room temperature."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 016 done: inserted {len(TRIPLETS)} triplets.")
