#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("butter","coffee","mint",
     "Butter and coffee share diacetyl and furfural — the buttery-roasted compound pair — while mint's menthol provides cooling contrast that butter extends on the palate far longer than in a water-based preparation. Together the trio creates a sophisticated iced coffee confection flavor.",
     "Mint Coffee Butter Truffles",
     ["Heat cream with fresh mint until steaming; steep 20 minutes and strain.",
      "Add espresso powder and pour over chopped white chocolate; stir in cold salted butter.",
      "Refrigerate until firm; roll into balls and dust with cocoa and crushed espresso beans."]),
    ("butter","coffee","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds linking dairy fat and marine brine — while coffee's furfural and Maillard compounds provide a roasted-bitter dimension that grounds the marine-butter combination. Butter amplifies oyster's aromatic compounds while coffee adds crust-like depth.",
     "Coffee Butter Roasted Oysters",
     ["Mix softened butter with finely ground espresso, lemon zest, and flaky salt.",
      "Place a small knob on each shucked oyster in the half-shell on a baking tray.",
      "Broil 4 minutes until butter is bubbling and the espresso crust forms; serve with lemon."]),
    ("butter","coffee","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while coffee's phenylacetaldehyde and acetic acid add a roasted-tart dimension to the dairy-fat richness. Butter carries both Parmesan's umami and coffee's volatile aromatics. The trio creates a sophisticated savory pastry base.",
     "Coffee Parmesan Butter Crisps",
     ["Mix finely grated Parmesan with cold butter, espresso powder, flour, and a pinch of pepper.",
      "Press into small rounds on parchment and bake at 375 degrees F until golden and lacy.",
      "Cool until crisp; serve with wine as a savory-bitter-salty aperitivo snack."]),
    ("butter","coffee","rose",
     "Butter and coffee share diacetyl and furfural — the buttery-roasted Maillard compound pair — while rose's 2-phenylethanol is carried and amplified by butter's fat, creating a perfumed coffee preparation where butter bridges the roasted-floral gap. The trio defines a sophisticated café-patisserie flavor.",
     "Rose Coffee Butter Madeleines",
     ["Brown butter until deeply nutty; cool and mix with espresso, rose water, eggs, and sugar.",
      "Fold in flour; rest batter 1 hour in the refrigerator for maximum dome.",
      "Bake in madeleine molds at 400 degrees F for 11 minutes; dust with coffee-rose sugar."]),
    ("butter","coffee","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatic compounds connecting dairy and marine fat — while coffee's Maillard compounds provide the roasted-bitter crust that suppresses salmon's trimethylamine when used as a dry rub. Butter carries coffee's volatile compounds into the salmon's flesh.",
     "Coffee Butter Basted Salmon",
     ["Mix espresso powder with brown butter; brush generously over salmon fillets.",
      "Sear crust-side down in a hot pan for 3 minutes until a coffee crust forms.",
      "Flip and baste with more coffee butter; finish in the oven at 400 degrees F for 6 minutes."]),
    ("butter","coffee","strawberry",
     "Butter and coffee share diacetyl and furfural — the buttery-roasted Maillard compound pair — while strawberry's furaneol aligns with both butter's and coffee's shared sweet-caramel compound. Together the three create a sophisticated tart or cake flavor where roasted bitterness and fresh sweetness balance precisely.",
     "Strawberry Coffee Butter Tart",
     ["Brown butter until deeply nutty; make a shortcrust pastry with the browned butter.",
      "Fill the blind-baked shell with espresso pastry cream; top with sliced fresh strawberries.",
      "Glaze with a strawberry-espresso reduction; the coffee's bitterness balances the fruit."]),
    ("butter","coffee","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while coffee's Maillard furaneol and acetic acid add a roasted-tart dimension that deepens slow-cooked tomato preparations. Butter's fat rounds tomato's acidity while coffee adds savory complexity.",
     "Coffee Tomato Butter Sauce",
     ["Sauté garlic in butter until golden; add crushed tomatoes and a shot of espresso.",
      "Simmer uncovered 30 minutes until thick and deeply flavored; season carefully.",
      "Finish with cold butter stirred in off heat for a glossy, rich pasta sauce."]),
    ("butter","coffee","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble aromatics that butter solubilizes far more effectively than water — while coffee's furfural and Maillard compounds add the roasted-bitter register that rounds truffle's earthiness into a more complex flavor. The trio creates the ultimate luxury savory butter.",
     "Truffle Coffee Compound Butter",
     ["Beat softened butter with truffle paste, finely ground espresso, and flaky salt.",
      "Roll in plastic wrap to form a log; refrigerate until very firm.",
      "Slice over hot pasta, risotto, or steak; the heat releases all three aromatics at once."]),
    ("butter","coffee","vanilla",
     "Butter, coffee, and vanilla share vanillin and diacetyl — sweet-creamy Maillard compounds — while coffee's furfural provides the roasted-bitter contrast to vanilla's lactonic sweetness. Butter carries both vanilla's and coffee's volatile aromatics as fat-soluble compounds. The trio defines the best coffee ice cream bases.",
     "Vanilla Coffee Butter Ice Cream",
     ["Make a vanilla custard base with split vanilla bean; add espresso powder off heat.",
      "Stir in cold brown butter and a pinch of salt; churn in an ice cream maker.",
      "Freeze until firm; serve with a coffee toffee shard and a drizzle of vanilla caramel."]),
    ("butter","cucumber","garlic",
     "Butter and cucumber share hexanal and trace linalool — green aldehyde and herbal terpene compounds — while garlic's allicin is transformed by butter's fat into sweet cooked-garlic notes that complement cucumber's cool freshness. Butter emulsifies garlic's pungency while extending cucumber's delicate volatile aldehydes.",
     "Garlic Butter Cucumber Sauté",
     ["Melt butter over medium heat; add sliced garlic and cook until barely golden.",
      "Add halved cucumbers and sauté briefly until just warmed through but still crisp.",
      "Finish with a squeeze of lemon and fresh dill; the garlic butter perfumes the cucumber."]),
    ("butter","cucumber","lamb",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that cuts through both ingredients' richness. Butter carries lamb's fat-soluble aromatics and amplifies cucumber's delicate volatile compounds.",
     "Butter Braised Lamb with Cucumber Raita",
     ["Braise lamb shoulder in butter, stock, and aromatics at 300 degrees F for 3 hours until tender.",
      "Make a raita with grated cucumber, yogurt, mint, and a touch of butter-toasted cumin.",
      "Serve the lamb over rice with raita on the side; the cucumber cools the rich buttery lamb."]),
    ("butter","cucumber","lavender",
     "Butter and cucumber share hexanal and trace linalool — green aldehyde and terpene compounds — while lavender's linalool and linalyl acetate reinforce this shared terpene, creating a floral-herbal-cool combination carried by butter's fat. The trio creates a refined summer compound butter.",
     "Lavender Cucumber Butter Canapés",
     ["Infuse softened butter with dried lavender 30 minutes at room temperature; strain out buds.",
      "Spread the lavender butter onto thick cucumber rounds.",
      "Top with a tiny lavender bud and a crystal of flaky salt; serve immediately chilled."]),
    ("butter","cucumber","lemon",
     "Butter and cucumber share hexanal and trace geraniol — green aldehyde and citrus-adjacent terpene — while lemon's geraniol reinforces this connection and citric acid brightens cucumber's cool freshness. Butter emulsifies lemon's acidity and extends cucumber's delicate volatile aldehydes on the palate.",
     "Lemon Butter Cucumber Linguine",
     ["Cook linguine al dente; make a sauce with butter, lemon juice, zest, and blanched cucumber strips.",
      "Toss pasta with sauce and a splash of pasta water to emulsify until glossy.",
      "Finish with more lemon zest, cracked pepper, and fresh herbs."]),
    ("butter","cucumber","mint",
     "Butter and cucumber share hexanal and linalool — green aldehyde and herbal terpene compounds — while mint's menthol provides the cooling contrast that butter extends on the palate far longer than in a water-based preparation. Together the three create a refined summer canapé flavor.",
     "Mint Cucumber Butter Canapés",
     ["Beat softened butter with finely chopped fresh mint and a pinch of flaky salt.",
      "Spread generously onto thick cucumber rounds.",
      "Top with a small mint leaf and a drop of lemon juice; serve immediately chilled."]),
    ("butter","cucumber","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds linking dairy fat and marine brine — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that resets between each rich buttery-briny bite. The trio creates a sophisticated compound for baked oysters.",
     "Cucumber Butter Baked Oysters",
     ["Make a compound butter with softened butter, finely grated cucumber (squeezed dry), and dill.",
      "Place a small knob on each shucked oyster in the half-shell; broil 3 minutes.",
      "Serve immediately with cucumber ribbons and lemon on the side."]),
    ("butter","cucumber","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while cucumber's (E)-2-nonenal provides the palate-cleansing freshness that cuts through the combined dairy richness. Butter carries Parmesan's umami while cucumber's cool provides contrast.",
     "Parmesan Butter Cucumber Pasta",
     ["Cook pasta al dente; toss with brown butter and finely grated Parmesan until coated.",
      "Add blanched thin cucumber strips and a splash of pasta water to emulsify.",
      "Finish with more Parmesan, cracked pepper, and fresh herbs."]),
    ("butter","cucumber","rose",
     "Butter and cucumber share hexanal and trace linalool — green aldehyde and terpene compounds — while rose's 2-phenylethanol is carried and amplified by butter's fat far more effectively than in water. Together the three create an elegant floral-cool-rich compound butter for canapés.",
     "Rose Cucumber Butter Toast",
     ["Beat softened butter with a few drops of rose water and a pinch of flaky salt.",
      "Spread onto thin slices of toasted brioche; layer with thin cucumber rounds.",
      "Scatter crystallized rose petals over the top; serve as a delicate afternoon tea canapé."]),
    ("butter","cucumber","salmon",
     "Butter and salmon share dimethyl sulfide and linalool — fat-soluble aromatic compounds connecting dairy and marine fat — while cucumber's (E)-2-nonenal mirrors salmon's own marine-green aldehyde notes, creating a coherent cool-marine-dairy flavor. The trio defines the flavor of salmon with cucumber dill butter sauce.",
     "Salmon with Cucumber Butter Sauce",
     ["Make a butter sauce by reducing white wine with shallots; whisk in cold butter piece by piece.",
      "Add finely diced cucumber and fresh dill to the warm sauce just before serving.",
      "Pan-sear salmon to medium; plate and spoon the cucumber butter sauce over the top."]),
    ("butter","cucumber","strawberry",
     "Butter and strawberry share furaneol — the sweet-caramel compound that browned butter and ripe strawberries both produce — while cucumber's hexanal provides the palate-cleansing cool freshness that makes the rich butter-strawberry combination feel lighter. The trio creates a sophisticated summer dessert.",
     "Strawberry Brown Butter Cucumber Tart",
     ["Brown butter until deeply nutty; use for a rich shortcrust pastry base.",
      "Fill with a vanilla cream; arrange thin cucumber ribbons and sliced strawberries over top.",
      "Drizzle with browned butter caramel; the unusual cucumber-strawberry contrast is intentional."]),
    ("butter","cucumber","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while cucumber's hexanal reinforces tomato's own green aldehyde freshness, creating a compound cool-sweet-savory register that butter rounds and amplifies. The trio creates a refined summer gazpacho flavor.",
     "Tomato Cucumber Brown Butter Pasta",
     ["Brown butter until deeply nutty; add halved cherry tomatoes and sauté until they burst.",
      "Add blanched cucumber strips and toss with al dente pasta; splash with pasta water.",
      "Season with flaky salt, lemon juice, and fresh basil; serve immediately."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 019 done: inserted {len(TRIPLETS)} triplets.")
