#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","lemon","oyster",
     "Blue cheese, lemon, and oyster form a three-corner sour-funky-brine triangle: lemon's citric acid cuts through blue cheese's fat and suppresses oyster's trimethylamine simultaneously, blue cheese's phenylacetaldehyde connects to oyster's marine-fermented register, and together the three create the most refreshing possible oyster preparation.",
     "Lemon Blue Cheese Oyster Gratin",
     ["Mix crumbled blue cheese with lemon zest, breadcrumbs, and a drizzle of olive oil.",
      "Place on each shucked oyster in the half-shell and broil 3 minutes until golden.",
      "Squeeze fresh lemon over immediately before serving; the acid wakes everything up."]),
    ("blue cheese","lemon","parmesan",
     "Blue cheese and Parmesan create doubled dairy umami — butyric acid and phenylacetaldehyde at different intensities — while lemon's citric acid cuts through the combined fat of both cheeses and brightens the fermentation esters into a cleaner, more vivid register. The trio creates the most complete cheese-acid balance.",
     "Lemon Blue Parmesan Caesar Dressing",
     ["Blend blue cheese, finely grated Parmesan, lemon juice, lemon zest, and anchovy paste.",
      "Emulsify with olive oil; adjust with more lemon and season with white pepper and salt.",
      "Toss with romaine, croutons, and extra Parmesan for a bold Caesar variation."]),
    ("blue cheese","lemon","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — the fermented-rosy compound pair — while lemon's geraniol reinforces rose's floral character through citrus-floral terpene overlap. Lemon's citric acid cuts through blue cheese's fat, making the funky-floral-bright combination unexpectedly light.",
     "Rose Lemon Blue Cheese Tart",
     ["Make a filling of blue cheese, cream, lemon juice, lemon zest, and a drop of rose water.",
      "Pour into a blind-baked tart shell and bake at 325 degrees F until barely set.",
      "Cool and top with a thin layer of rose-lemon curd and crystallized rose petals."]),
    ("blue cheese","lemon","salmon",
     "Blue cheese, lemon, and salmon create a triple acid-fat-marine preparation: lemon's citric acid suppresses salmon's trimethylamine, blue cheese's lactic acid adds a second acidic dimension, and blue cheese's phenylacetaldehyde bridges the dairy-marine gap. Together the three create a sophisticated Nordic salmon preparation.",
     "Lemon Blue Cheese Salmon Tartare",
     ["Finely dice sushi-grade salmon; mix with crumbled blue cheese, lemon juice, and zest.",
      "Add capers, shallot, and a drizzle of olive oil; season with white pepper and flaky salt.",
      "Serve on rye crackers with cucumber and a lemon-blue cheese cream on the side."]),
    ("blue cheese","lemon","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound — while lemon's citric acid sharpens strawberry's own natural acidity and brightens blue cheese's fat into something cleaner. Together the three create the sophisticated sweet-tart-funky balance of elevated cheese boards.",
     "Lemon Strawberry Blue Cheese Pavlova",
     ["Bake a meringue base; spread with lemon curd mixed with a small amount of blue cheese.",
      "Top with fresh strawberries macerated in lemon juice and a pinch of sugar.",
      "Crumble a small amount of blue cheese over the fruit just before serving."]),
    ("blue cheese","lemon","tomato",
     "Blue cheese, lemon, and tomato share acetic acid — all three contributing tartness through fermentation and citric pathways — while blue cheese's phenylacetaldehyde deepens the classic tomato-lemon combination with a fermented savory layer that elevates simple salads into something more complex.",
     "Lemon Blue Cheese Tomato Salad",
     ["Slice ripe heirloom tomatoes; arrange on a platter and season with flaky salt.",
      "Crumble blue cheese generously over the tomatoes; drizzle with lemon juice and olive oil.",
      "Add fresh herbs, cracked pepper, and serve immediately while the tomatoes are at room temperature."]),
    ("blue cheese","lemon","truffle",
     "Blue cheese and truffle share phenylacetaldehyde, dimethyl sulfide, and anisaldehyde — the luxury fermented-earthy compound set — while lemon's citric brightness cuts through both ingredients' heaviest fat and aromatic density, lifting the intense combination into a cleaner, more vertical register. The trio produces a refined luxury preparation.",
     "Lemon Truffle Blue Cheese Pasta",
     ["Cook fresh pasta al dente; make a sauce from blue cheese, truffle butter, and lemon juice.",
      "Toss pasta in sauce with pasta water; the lemon brightens the truffle and blue cheese.",
      "Plate and shave fresh truffle over; finish with lemon zest and cracked pepper."]),
    ("blue cheese","lemon","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol — the rosy compound — while lemon's geraniol bridges vanilla's floral-citrus character and blue cheese's fermented-rosy register. Lemon's citric acid cuts through blue cheese's heaviest fat, making the funky-sweet combination unexpectedly clean and elegant.",
     "Vanilla Lemon Blue Cheese Cheesecake",
     ["Make a filling with blue cheese, cream cheese, vanilla bean, lemon zest, and juice.",
      "Pour over a graham cracker crust and bake in water bath at 325 degrees F until set.",
      "Cool; glaze with lemon curd and serve with a vanilla-lemon cream on the side."]),
    ("blue cheese","mint","oyster",
     "Blue cheese and oyster share phenylacetaldehyde, dimethyl sulfide, and trimethylamine — the pungent fermented-marine compound set — while mint's menthol suppresses both blue cheese's ammonia and oyster's fishy trimethylamine through olfactory cooling, making both ingredients taste cleaner and more vibrant.",
     "Mint Blue Cheese Oyster Shooter",
     ["Blend fresh mint leaves with white wine vinegar, shallot, and a touch of blue cheese.",
      "Strain until clean and bright green; season with white pepper and salt.",
      "Shuck oysters into shot glasses; top with the mint-blue cheese liquid and serve immediately."]),
    ("blue cheese","mint","parmesan",
     "Blue cheese and Parmesan create doubled dairy umami while mint's menthol provides the cooling contrast that resets the palate between each rich cheesy bite. Menthol also suppresses blue cheese's ammonia specifically, making the combination taste cleaner than blue cheese alone while Parmesan provides the savory depth.",
     "Mint Blue Parmesan Gnocchi",
     ["Make potato gnocchi; toss in brown butter with finely grated Parmesan and crumbled blue cheese.",
      "Add a handful of finely chopped fresh mint just as the cheese begins to melt.",
      "Plate with more Parmesan and a fresh mint garnish; the mint lifts both cheeses."]),
    ("blue cheese","mint","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — fermented-rosy compounds — while mint's linalool and menthol provide cooling contrast that suppresses blue cheese's ammonia through olfactory competition and lets rose's delicate floral register come forward. The trio creates an unexpectedly elegant summer cheese preparation.",
     "Rose Mint Blue Cheese Dip",
     ["Beat room-temperature blue cheese with finely chopped fresh mint and a few drops of rose water.",
      "Add a drizzle of rose honey and lemon zest; mix until smooth.",
      "Serve chilled with fresh strawberries, grapes, and crackers."]),
    ("blue cheese","mint","salmon",
     "Blue cheese, mint, and salmon all benefit from menthol's trimethylamine-suppressing mechanism — mint's cooling compounds reduce the perception of both blue cheese's ammonia and salmon's fishy notes through olfactory competition — while blue cheese's phenylacetaldehyde bridges the dairy-marine gap through shared sulfurous compounds.",
     "Mint Blue Cheese Salmon Rillettes",
     ["Poach salmon gently; flake and mix with softened blue cheese, chopped fresh mint, and lemon.",
      "Season with white pepper and adjust with more lemon; spread onto a slate board.",
      "Serve with rye crackers, cucumber slices, and fresh mint as a sophisticated starter."]),
    ("blue cheese","mint","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound — while mint's menthol suppresses blue cheese's ammonia, making the funky-sweet combination taste cleaner and letting strawberry's freshness come forward. Strawberry's sweetness simultaneously balances both blue cheese and mint's intensities.",
     "Mint Blue Cheese Strawberry Flatbread",
     ["Bake flatbread until crispy; top immediately with crumbled blue cheese to melt slightly.",
      "Arrange halved fresh strawberries and scatter torn fresh mint leaves over the cheese.",
      "Drizzle with wildflower honey and balsamic reduction; serve immediately."]),
    ("blue cheese","mint","tomato",
     "Blue cheese and tomato share acetic acid — both contributing tartness — while mint's menthol provides the cooling contrast that suppresses blue cheese's ammonia and refreshes the palate between each acidic-funky bite of tomato. The trio creates a sophisticated salad reminiscent of Middle Eastern herb-cheese preparations.",
     "Mint Blue Cheese Tomato Salad",
     ["Slice ripe tomatoes and arrange on a platter; scatter crumbled blue cheese over generously.",
      "Tear fresh mint leaves over the top and add thinly sliced cucumber.",
      "Dress with olive oil, red wine vinegar, salt, and cracked pepper; serve immediately."]),
    ("blue cheese","mint","truffle",
     "Blue cheese and truffle share phenylacetaldehyde, dimethyl sulfide, and anisaldehyde — the luxury fermented-earthy compound set — while mint's menthol provides the palate-cleansing cooling contrast that suppresses blue cheese's ammonia between each bite of the intense truffle preparation. The trio creates a complex luxury flavor.",
     "Truffle Mint Blue Cheese Scrambled Eggs",
     ["Beat eggs with crumbled blue cheese and finely chopped fresh mint; season well.",
      "Scramble slowly in butter over the lowest heat, stirring constantly until just barely set.",
      "Plate immediately and shave fresh truffle generously over the creamy eggs."]),
    ("blue cheese","mint","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol — the rosy compound — while mint's menthol suppresses blue cheese's ammonia through olfactory cooling and vanilla's vanillin sweetness softens the funk into something elegant. Mint's cool makes vanilla's warmth feel more pronounced in contrast.",
     "Vanilla Mint Blue Cheese Ice Cream",
     ["Make a vanilla custard base with split vanilla bean; churn until thick and creamy.",
      "Add crumbled blue cheese and finely chopped fresh mint in the last 2 minutes of churning.",
      "Freeze until firm; serve with a honey drizzle and a fresh mint leaf garnish."]),
    ("blue cheese","oyster","parmesan",
     "Blue cheese, oyster, and Parmesan share phenylacetaldehyde, dimethyl sulfide, and butyric acid — spanning fermented dairy, marine bivalve, and aged cheese in the same sulfurous-rosy compound family — creating a triple-umami combination where each ingredient amplifies the others' savory intensity to an extraordinary degree.",
     "Oyster Parmesan Blue Cheese Gratin",
     ["Place shucked oysters in their half-shells; top each with a mixture of blue cheese and Parmesan.",
      "Add breadcrumbs, garlic butter, and a crack of pepper; broil 4 minutes until golden.",
      "Serve immediately with crusty bread to capture all the intensely savory juices."]),
    ("blue cheese","oyster","rose",
     "Blue cheese and oyster share phenylacetaldehyde — the rosy-fermented compound — while rose amplifies this shared floral note with its dominant 2-phenylethanol, creating a triple-floral-marine-funky combination where the flower's perfume softens both blue cheese's ammonia and oyster's brine into something elegant.",
     "Rose Blue Cheese Oyster Mignonette",
     ["Mix red wine vinegar with minced shallot, crumbled blue cheese, and rose water.",
      "Add cracked white pepper and a pinch of sugar; rest 10 minutes to meld.",
      "Spoon over freshly shucked raw oysters on ice; the rose lifts the brine beautifully."]),
    ("blue cheese","oyster","salmon",
     "Blue cheese, oyster, and salmon share trimethylamine, dimethyl sulfide, and butyric acid — the complete marine-animal-fermented sulfurous compound triad — creating the most intensely oceanic-savory combination possible. Together they form a triple-seafood-cheese preparation of extraordinary depth.",
     "Blue Cheese Oyster Salmon Gratin",
     ["Layer thin slices of smoked salmon in a buttered baking dish; top with shucked oysters.",
      "Pour a blue cheese cream sauce over everything; top with Parmesan and breadcrumbs.",
      "Bake at 375 degrees F until bubbling and golden; serve with lemon and crusty bread."]),
    ("blue cheese","oyster","strawberry",
     "Blue cheese, oyster, and strawberry create a three-corner sweet-funky-brine triangle: strawberry's furaneol sweetness contrasts oyster's brine and blue cheese's funk, while blue cheese's phenylacetaldehyde bridges the dairy-marine gap. The trio creates a sophisticated avant-garde raw bar experience.",
     "Strawberry Blue Cheese Oyster on Ice",
     ["Make a strawberry-balsamic mignonette with diced strawberry, vinegar, and shallot.",
      "Stir in a small amount of crumbled blue cheese; rest 5 minutes.",
      "Spoon over freshly shucked raw oysters on crushed ice; serve immediately."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 015 done: inserted {len(TRIPLETS)} triplets.")
