#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","strawberry","vanilla",
     "Blue cheese, strawberry, and vanilla all produce 2-phenylethanol and furaneol through independent pathways — a double-compound overlap spanning fermented dairy, ripe fruit, and cured spice — while vanilla's vanillin sweetness suppresses blue cheese's ammonia and lets strawberry's fresh fragrance come forward. The trio is a sophisticated dessert cheese preparation.",
     "Strawberry Vanilla Blue Cheese Tart",
     ["Make a filling from blue cheese and mascarpone with vanilla bean seeds; set in a tart shell.",
      "Macerate sliced strawberries with vanilla and a touch of sugar; arrange over the set filling.",
      "Finish with a drizzle of aged balsamic and serve at room temperature."]),
    ("blue cheese","tomato","truffle",
     "Blue cheese, tomato, and truffle share dimethyl sulfide and furaneol — the sulfurous and sweet-caramel compounds — while truffle's anisaldehyde earthy luxury deepens the classic blue cheese-tomato combination into something more complex. Together the three create a sophisticated pizza or pasta preparation with luxury depth.",
     "Truffle Blue Cheese Tomato Flatbread",
     ["Brush flatbread with truffle oil; scatter sliced cherry tomatoes across the surface.",
      "Crumble blue cheese generously and bake at 500 degrees F until crispy and bubbling.",
      "Shave fresh truffle over the top right out of the oven; serve immediately."]),
    ("blue cheese","tomato","vanilla",
     "Blue cheese and tomato share furaneol and acetic acid — sweet-caramel and tart compounds — while vanilla's vanillin reinforces the shared furaneol register and its sweetness suppresses blue cheese's harshest ammonia notes. The trio creates a surprisingly coherent slow-roasted tomato-cheese preparation.",
     "Vanilla Tomato Blue Cheese Bruschetta",
     ["Slow-roast cherry tomatoes with a split vanilla bean and olive oil at 250 degrees F for 2 hours.",
      "Toast sourdough; spread with room-temperature blue cheese while warm.",
      "Spoon the vanilla-roasted tomatoes over the cheese; the vanilla amplifies the tomato's sweetness."]),
    ("blue cheese","truffle","vanilla",
     "Blue cheese, truffle, and vanilla form a rare three-ingredient 2-phenylethanol triangle — all three produce this rosy compound through fermentation, fungal metabolism, and curing — while truffle's anisaldehyde earthiness and vanilla's vanillin sweetness create opposite poles that blue cheese's funk mediates. The trio produces an extraordinarily refined compound butter.",
     "Truffle Vanilla Blue Cheese Butter",
     ["Beat softened butter with crumbled blue cheese, truffle paste, and vanilla bean seeds.",
      "Add a pinch of flaky salt and a drizzle of truffle honey; beat until smooth.",
      "Roll in plastic wrap, refrigerate until firm; slice over hot pasta or warm bread."]),
    ("butter","caramel","chocolate",
     "Butter and chocolate share dimethyl sulfide and furaneol — fat-soluble Maillard compounds — while caramel amplifies these shared sweet-roasted compounds with its own Maillard furaneol, creating a self-reinforcing triple sweet-roasted register where butter acts as the fat medium carrying all volatile aromatics. The trio is the base of every great chocolate cake.",
     "Chocolate Caramel Butter Lava Cake",
     ["Make a caramel center: pour dark caramel into ice cube molds and freeze until solid.",
      "Fold frozen caramel cubes into chocolate butter cake batter; pour into buttered ramekins.",
      "Bake at 425 degrees F for 11 minutes until edges set; the caramel center stays molten."]),
    ("butter","caramel","coffee",
     "Butter, caramel, and coffee share furfural, diacetyl, and acetic acid — three major Maillard and fermentation products — creating a triple-roasted sweet-bitter register where butter's fat carries and amplifies coffee's volatile aromatics and caramel's sweetness rounds the bitterness. The trio defines sophisticated café pastry flavor.",
     "Coffee Caramel Butter Cookies",
     ["Cream butter with brown sugar; add a tablespoon of espresso and a drizzle of caramel.",
      "Mix in flour and a pinch of salt to form a soft dough; chill 30 minutes.",
      "Roll into balls, bake at 350 degrees F until golden; drizzle with coffee caramel while warm."]),
    ("butter","caramel","cucumber",
     "Butter's fat amplifies caramel's furaneol sweetness while cucumber's hexanal provides the palate-cleansing green freshness that balances the rich sweet combination. The three create an unusual savory-sweet contrast where cucumber's coolness makes caramel's warmth feel more pronounced.",
     "Caramel Cucumber Butter Canapés",
     ["Make a light caramel; cool until thick but pourable; drizzle onto parchment to set.",
      "Spread softened butter onto crisp cucumber rounds; top with a small caramel shard.",
      "Finish with flaky salt and fresh dill; serve immediately as a refined summer canapé."]),
    ("butter","caramel","garlic",
     "Butter and caramel share diacetyl and furaneol — the buttery-sweet Maillard compounds — while garlic's allicin is transformed by butter's fat into sweet, round cooked-garlic notes that caramel's sweetness amplifies further. Together the three create the flavor of slow-caramelized garlic confit in butter.",
     "Caramel Garlic Butter Sauce",
     ["Slowly cook sliced garlic in butter until deeply golden and sweet, about 15 minutes.",
      "Add brown sugar and cook until caramelized; deglaze with white wine and cream.",
      "Reduce until glossy and thick; serve over chicken, pork, or roasted vegetables."]),
    ("butter","caramel","lamb",
     "Butter and lamb share butyric acid and dimethyl sulfide — connecting dairy fat to animal fat through shared sulfurous-rich compound families — while caramel's Maillard sweetness provides the glazing medium that seals lamb's fat-soluble aromatics and suppresses its 4-methyloctanoic acid gaminess. The trio drives sweet-lacquered lamb preparations.",
     "Caramel Butter Glazed Lamb Chops",
     ["Make a caramel with brown sugar and butter; add rosemary, garlic, and a splash of red wine.",
      "Sear lamb chops hard in a hot pan until crusted on both sides.",
      "Brush generously with caramel glaze and finish under the broiler 2 minutes until lacquered."]),
    ("butter","caramel","lavender",
     "Butter and caramel share diacetyl and furaneol — buttery-sweet Maillard compounds — while lavender's linalool and linalyl acetate provide the floral-herbal counterweight that prevents the rich butter-caramel from tasting cloying. Butter's fat carries lavender's volatile aromatics far longer than a water-based preparation.",
     "Lavender Caramel Butter Tart",
     ["Make a caramel flavored with dried lavender; strain and pour into a blind-baked tart shell.",
      "Whisk in cold salted butter piece by piece until the caramel is glossy and set.",
      "Garnish with dried lavender buds and a pinch of fleur de sel before serving."]),
    ("butter","caramel","lemon",
     "Butter and caramel share diacetyl and furaneol — the buttery-sweet compound pair — while lemon's citric acid creates the sour counterpoint that defines classic lemon caramel sauce. Butter's fat emulsifies lemon's acidity into the caramel's sweetness, rounding the sharp-sweet balance into something silky.",
     "Lemon Caramel Butter Tart",
     ["Make a dry caramel; deglaze with lemon juice and cream, whisking over low heat until smooth.",
      "Beat in cold salted butter piece by piece until the sauce is glossy and emulsified.",
      "Pour into a blind-baked tart shell; cool until set, then top with lemon curd."]),
    ("butter","caramel","mint",
     "Butter and caramel share diacetyl and furaneol — the buttery-sweet Maillard compounds — while mint's menthol provides a cooling contrast that makes the warm rich butter-caramel taste brighter and cleaner. Butter's fat carries mint's volatile menthol compounds longer and more intensely than a water-based preparation.",
     "Mint Caramel Butter Sauce",
     ["Make a salted caramel; stir in cold salted butter piece by piece until glossy.",
      "Off heat, add finely chopped fresh mint and stir to wilt slightly; the heat releases the oils.",
      "Serve warm over vanilla ice cream with extra fresh mint leaves as a garnish."]),
    ("butter","caramel","oyster",
     "Butter and oyster share dimethyl sulfide and acetic acid — sulfurous and tart compounds linking dairy fat to marine brine — while caramel's Maillard sweetness provides a direct contrast that suppresses oyster's trimethylamine through sweet aromatic displacement. The trio creates a sweet-brine lacquered oyster preparation.",
     "Caramel Butter Roasted Oysters",
     ["Make a light caramel with butter, brown sugar, and soy sauce; reduce to a glaze.",
      "Place a small amount on each shucked oyster in the half-shell; broil 3 minutes.",
      "Serve immediately while the caramel-butter glaze is still bubbling over the oyster."]),
    ("butter","caramel","parmesan",
     "Butter and Parmesan share butyric acid, furaneol, and dimethyl sulfide — overlapping dairy compound sets — while caramel's furaneol and Maillard sweetness amplifies the shared sweet compound, creating a triple-tier dairy-sweet-umami register. Together they form the base of a sophisticated savory caramel-Parmesan sauce.",
     "Caramel Parmesan Butter Sauce",
     ["Make a light caramel with butter and brown sugar; add cream and reduce until glossy.",
      "Stir in finely grated Parmesan off heat until melted into the caramel sauce.",
      "Serve over gnocchi or risotto; the savory-sweet balance is unexpected but precise."]),
    ("butter","caramel","rose",
     "Butter and caramel share diacetyl and furaneol — the buttery-sweet Maillard compounds — while rose's 2-phenylethanol and linalool provide the floral counterweight that elevates the rich sweet combination into a perfumed, elegant register. Butter's fat carries rose's volatile aromatics far longer than water.",
     "Rose Caramel Butter Madeleines",
     ["Brown butter to a hazelnut color; cool, then mix with eggs, sugar, rose water, and honey.",
      "Fold in flour; rest the batter 1 hour in the refrigerator for the best dome.",
      "Bake in madeleine molds at 400 degrees F for 11 minutes; dust with rose petal sugar."]),
    ("butter","caramel","salmon",
     "Butter and salmon share dimethyl sulfide, linalool, and acetic acid — fat-soluble aromatic compounds connecting dairy and marine fat — while caramel's Maillard glaze seals salmon's skin and suppresses trimethylamine through sweet-savory contrast. The trio drives teriyaki-style lacquered salmon preparations.",
     "Caramel Butter Glazed Salmon",
     ["Make a caramel glaze with butter, brown sugar, soy sauce, and ginger; reduce to syrupy.",
      "Sear salmon skin-side down until crispy; flip and brush with caramel-butter glaze.",
      "Finish under the broiler 2 minutes until lacquered; serve with sesame and scallion."]),
    ("butter","caramel","strawberry",
     "Butter, caramel, and strawberry share furaneol at unusually high concentrations — all three ingredients producing this sweet-caramel compound — while butter's fat amplifies strawberry's delicate esters and carries caramel's warmth longer on the palate. The trio creates the most compound-coherent dessert flavor possible.",
     "Strawberry Caramel Brown Butter Tart",
     ["Brown butter until deeply nutty; use it to make a rough puff pastry base.",
      "Make a caramel; fold in sliced strawberries with a pinch of salt and let cool.",
      "Pour strawberry caramel into the pastry shell; bake at 400 degrees F until golden."]),
    ("butter","caramel","tomato",
     "Butter and tomato share furaneol and trace hexanal — sweet-caramel and green aldehyde compounds — while caramel's Maillard sweetness deepens the roasted tomato's natural furaneol into something richer. Butter's fat, famously demonstrated by Marcella Hazan, rounds tomato's acidity into silk.",
     "Caramel Tomato Butter Sauce",
     ["Make a light caramel with sugar in a wide pan; add crushed tomatoes carefully.",
      "Add a large knob of cold butter and a halved onion; simmer uncovered 45 minutes.",
      "Remove onion, season, and toss with pasta; the caramel deepens the tomato's sweetness."]),
    ("butter","caramel","truffle",
     "Butter and truffle share dimethyl sulfide and phenylacetaldehyde — fat-soluble aromatics that butter solubilizes and carries far more effectively than water — while caramel's Maillard furaneol sweetness creates the third register that rounds truffle's earthiness into a sweet-savory luxury compound. The trio is the flavor of truffle caramel sauce.",
     "Truffle Caramel Butter Sauce",
     ["Make a dark salted caramel; whisk in cold truffle butter piece by piece until glossy.",
      "Add a few drops of truffle oil and a pinch of fleur de sel; stir to combine.",
      "Serve warm over vanilla ice cream or drizzle over aged Parmesan for a luxury pairing."]),
    ("butter","caramel","vanilla",
     "Butter, caramel, and vanilla share vanillin, furaneol, diacetyl, and delta-decalactone — a complete overlap of sweet lactonic and Maillard aromatic compounds — creating the most coherent flavor register in dessert cooking. The three are so chemically similar that they amplify each other rather than contrasting, producing a deep, unified sweetness.",
     "Vanilla Caramel Butter Sauce",
     ["Split a vanilla bean and scrape seeds into cream with sugar; heat until steaming.",
      "Make a dry caramel separately; deglaze with the hot vanilla cream; whisk smooth.",
      "Finish with cold salted butter piece by piece until glossy; serve warm over everything."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 017 done: inserted {len(TRIPLETS)} triplets.")
