#!/usr/bin/env python3
import sqlite3, json, os

DB = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "flavorgraph.db"))

TRIPLETS = [
    ("blue cheese","butter","oyster",
     "Blue cheese and oyster share phenylacetaldehyde, dimethyl sulfide, and trimethylamine — the pungent fermented-marine compound set — while butter's fat rounds both ingredients' sharpest volatile compounds and carries them longer on the palate. The trio creates an intensely savory umami combination used in baked oyster preparations.",
     "Blue Cheese Butter Baked Oysters",
     ["Mix softened butter with crumbled blue cheese, minced garlic, and lemon zest.",
      "Place a generous knob on each shucked oyster in its half-shell on a baking tray.",
      "Broil 4 minutes until bubbling and oyster edges just curl; serve with crusty bread."]),
    ("blue cheese","butter","parmesan",
     "Blue cheese and Parmesan share butyric acid, acetic acid, phenylacetaldehyde, and dimethyl sulfide — nearly identical aged-dairy compound sets at different intensities — while butter's fat emulsifies both cheeses into a single rich compound, creating three-tier dairy umami. Together they form the most intense cheese butter possible.",
     "Blue Parmesan Compound Butter",
     ["Beat softened butter with crumbled blue cheese and finely grated Parmesan until smooth.",
      "Add cracked pepper and a touch of lemon zest; roll in plastic wrap and refrigerate.",
      "Slice over hot pasta, risotto, or a grilled T-bone steak immediately before serving."]),
    ("blue cheese","butter","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — fermented-rosy compounds — while butter's fat carries rose's delicate volatile floral compounds far longer on the palate and rounds blue cheese's ammonia into a gentler, more floral register. The trio creates an elegantly perfumed compound butter for cheese boards.",
     "Rose Blue Cheese Compound Butter",
     ["Beat softened butter with crumbled blue cheese and a few drops of rose water until smooth.",
      "Add a pinch of flaky salt and crushed dried rose petals; roll in plastic wrap to chill.",
      "Serve sliced on warm toast or honey-drizzled crackers alongside a cheese board."]),
    ("blue cheese","butter","salmon",
     "Blue cheese, butter, and salmon share dimethyl sulfide, trimethylamine, and butyric acid — the sulfurous-marine-fatty compound family spanning fermented dairy, fat, and fish — while butter's fat acts as an emulsifier that bridges the dairy and marine registers into a single cohesive compound butter.",
     "Blue Cheese Butter Poached Salmon",
     ["Melt butter with crumbled blue cheese until just incorporated; season with lemon and pepper.",
      "Poach salmon pieces gently in the blue cheese butter over lowest heat for 8 minutes.",
      "Serve immediately in shallow bowls with crusty bread and fresh dill or chives."]),
    ("blue cheese","butter","strawberry",
     "Blue cheese and strawberry share furaneol — the caramel-sweet compound in ripe strawberry that also appears in aged cheese fermentation — while butter's fat amplifies strawberry's delicate esters and rounds blue cheese's sharpest ammonia notes into a sophisticated sweet-funky balance.",
     "Strawberry Blue Cheese Butter Toast",
     ["Macerate sliced strawberries with a drizzle of balsamic and a pinch of fleur de sel.",
      "Beat softened butter with crumbled blue cheese until smooth; spread on warm toasted brioche.",
      "Top with macerated strawberries and a final drizzle of wildflower honey."]),
    ("blue cheese","butter","tomato",
     "Blue cheese and tomato share acetic acid and trace hexanal — tart and green compounds — while butter's fat rounds blue cheese's ammonia and amplifies tomato's volatile furaneol sweetness over a longer palate duration. The trio creates a sophisticated savory tomato preparation where blue cheese replaces standard cream.",
     "Blue Cheese Butter Tomato Pasta",
     ["Simmer cherry tomatoes in butter until they burst and caramelize into a thick sauce.",
      "Crumble blue cheese into the sauce off heat and stir until just melted and creamy.",
      "Toss with al dente pasta, finish with cracked pepper and fresh thyme or basil."]),
    ("blue cheese","butter","truffle",
     "Blue cheese and truffle share phenylacetaldehyde, dimethyl sulfide, and anisaldehyde — the most powerful fermented-earthy aromatic compound set in cooking — while butter's fat solubilizes and amplifies truffle's volatile sulfurous compounds far more effectively than any other medium. The trio creates the ultimate luxury savory compound butter.",
     "Truffle Blue Cheese Compound Butter",
     ["Beat softened butter with blue cheese, truffle paste, and a pinch of flaky salt until smooth.",
      "Roll in plastic wrap to form a tight log; refrigerate until very firm.",
      "Slice thickly over hot steak, pasta, or risotto; the heat releases all three aromatics at once."]),
    ("blue cheese","butter","vanilla",
     "Blue cheese and vanilla share 2-phenylethanol and trace vanillin — rosy and sweet compounds — while butter's butyric acid and diacetyl bridge the two extremes, sitting naturally between dairy funk and lactonic sweetness. Together vanilla suppresses blue cheese's harshest ammonia notes into a surprisingly elegant compound.",
     "Vanilla Blue Cheese Honey Butter",
     ["Beat softened butter with crumbled blue cheese, vanilla bean seeds, and a drizzle of honey.",
      "Mix until smooth and cohesive; taste for seasoning and add flaky salt if needed.",
      "Serve chilled in a crock alongside apple slices, walnuts, and warm crusty bread."]),
    ("blue cheese","caramel","chocolate",
     "Blue cheese and chocolate share phenylacetaldehyde and dimethyl sulfide — the rosy-fermented compound pair that fermented cacao and aged dairy produce independently — while caramel's furaneol and Maillard sweetness creates a three-way sweet-funky-roasted balance where each element deepens the others' complexity.",
     "Blue Cheese Caramel Chocolate Tart",
     ["Pour salted caramel into a blind-baked dark chocolate tart shell; let set 20 minutes.",
      "Top with a dark chocolate ganache layer; refrigerate until set completely.",
      "Crumble blue cheese across the top and drizzle with caramel; serve at room temperature."]),
    ("blue cheese","caramel","coffee",
     "Blue cheese, caramel, and coffee share acetic acid, phenylacetaldehyde, and dimethyl sulfide — all three ingredients producing roasted-fermented-pungent compounds through Maillard, fermentation, and aging pathways — creating a dense triple-umami bitter-sweet-funky register.",
     "Blue Cheese Coffee Caramel Bruschetta",
     ["Reduce espresso with brown sugar to a thick coffee caramel glaze; cool slightly.",
      "Toast thick sourdough and drizzle with the coffee caramel while still warm.",
      "Spread room-temperature blue cheese over the caramel and serve immediately."]),
    ("blue cheese","caramel","cucumber",
     "Caramel's intense Maillard sweetness contrasts cucumber's clean (E)-2-nonenal freshness — sweet-roasted against cool-watery — while blue cheese's phenylacetaldehyde and butyric acid add a funky savory layer that bridges the extremes into a sophisticated three-register canapé flavor.",
     "Blue Cheese Caramel Cucumber Bites",
     ["Make a light dry caramel, cool until amber syrup; pour onto parchment to set into shards.",
      "Pipe room-temperature blue cheese onto cucumber rounds; top with a small caramel shard.",
      "Drizzle with wildflower honey and a crack of pepper; serve immediately."]),
    ("blue cheese","caramel","garlic",
     "Caramel's Maillard sweetness mirrors sweet vinyl compounds from slowly caramelized garlic — both involve sugar transformation — while blue cheese's butyric acid funk adds a savory fermented depth that balances the sweet-allium register. The trio creates the flavor logic behind caramelized onion and blue cheese tarts.",
     "Caramelized Garlic Blue Cheese Tart",
     ["Slowly cook whole garlic cloves in butter and sugar until golden and sweet, about 20 minutes.",
      "Arrange in a blind-baked tart shell; whisk blue cheese into cream and pour over garlic.",
      "Bake at 350 degrees F until just set; drizzle with caramel and serve warm with dressed greens."]),
    ("blue cheese","caramel","lamb",
     "Caramel's Maillard sweetness suppresses lamb's gamey 4-methyloctanoic acid through sweet-savory contrast — the principle behind Moroccan lamb with sweet spices — while blue cheese's butyric acid and phenylacetaldehyde add a funky depth that amplifies lamb's umami. The trio is bold and rich.",
     "Caramel Blue Cheese Glazed Lamb Rack",
     ["Make a caramel glaze with brown sugar, soy, and blue cheese whisked in off heat.",
      "Sear lamb rack in a hot pan until crusted; brush generously with glaze.",
      "Roast at 400 degrees F for 12 minutes to medium-rare; rest and serve sliced with remaining glaze."]),
    ("blue cheese","caramel","lavender",
     "Lavender's linalool and linalyl acetate soften blue cheese's harsh ammonia through floral aromatic displacement — a more elegant version of honey with cheese — while caramel's Maillard sweetness creates the sweet counterpoint that makes the funky-floral-sweet combination read as a refined dessert cheese preparation.",
     "Lavender Caramel Blue Cheese Cheesecake",
     ["Make a cheesecake filling with blue cheese, cream cheese, lavender sugar, and eggs.",
      "Pour over a gingersnap crust and bake in water bath at 325 degrees F until just set.",
      "Cool and refrigerate overnight; drizzle with lavender caramel before serving."]),
    ("blue cheese","caramel","lemon",
     "Caramel's diacetyl sweetness and lemon's citric brightness combine with blue cheese's butyric acid funk in a three-way sour-sweet-savory register where each element defines one corner of the flavor triangle. Lemon's acidity cuts through blue cheese's fat while caramel softens its sharpest fermented notes.",
     "Lemon Caramel Blue Cheese Tart",
     ["Make a salted caramel; swirl into a creamy blue cheese filling with lemon zest and juice.",
      "Pour into a pre-baked tart shell and bake at 325 degrees F until barely set with a slight wobble.",
      "Cool completely; finish with lemon curd and flaky salt before slicing."]),
    ("blue cheese","caramel","mint",
     "Caramel's warmth and mint's menthol create the classic toffee-mint contrast while blue cheese adds a savory fermented depth that prevents the combination from reading as candy. Menthol's cooling directly suppresses blue cheese's ammonia perception through olfactory competition, making the funk more approachable.",
     "Mint Caramel Blue Cheese Flatbread",
     ["Stretch flatbread thin; brush with a thin layer of dark caramel mixed with cream.",
      "Crumble blue cheese across the surface and bake at 450 degrees F until crispy and bubbling.",
      "Remove from oven, scatter fresh mint leaves and a drizzle of honey before serving."]),
    ("blue cheese","caramel","oyster",
     "Caramel's intense Maillard sweetness directly contrasts oyster's marine brine and blue cheese's fermented funk — three completely distinct flavor registers — while caramel's sweetness acts as a balancing agent that softens both the briny and the funky into a unified complex flavor.",
     "Caramel Blue Cheese Oyster Gratin",
     ["Mix crumbled blue cheese with a drizzle of dark caramel and breadcrumbs.",
      "Place a small amount on each shucked oyster in its half-shell on a baking tray.",
      "Broil 3 minutes until bubbling and golden; the caramel-cheese crust softens the marine punch."]),
    ("blue cheese","caramel","parmesan",
     "Blue cheese and Parmesan share butyric acid, phenylacetaldehyde, and dimethyl sulfide — creating a doubled aged-dairy umami stack — while caramel's furaneol and Maillard sweetness provides the sweet counterpoint that balances the concentrated cheese intensity. The trio appears in refined cheese fondues and savory caramel-cheese preparations.",
     "Caramel Blue Parmesan Fondue",
     ["Melt blue cheese and Parmesan into warm cream with a splash of dry white wine.",
      "Stir in a spoonful of dark caramel and season with white pepper and nutmeg.",
      "Keep warm in a fondue pot; serve with bread, apple slices, and roasted vegetables."]),
    ("blue cheese","caramel","rose",
     "Blue cheese and rose share 2-phenylethanol and phenylacetaldehyde — fermented-rosy aromatic overlap — while caramel's furaneol sweetness bridges the floral and funky registers into a sophisticated three-way flavor where each element softens the others' extremes. Rose suppresses blue cheese's ammonia; caramel rounds both.",
     "Rose Caramel Blue Cheese Crostini",
     ["Reduce rose water with sugar to a floral caramel syrup; cool until thick.",
      "Toast baguette rounds; spread with room-temperature blue cheese while still warm.",
      "Drizzle with rose caramel, add a crystallized rose petal, and serve immediately."]),
    ("blue cheese","caramel","salmon",
     "Caramel's Maillard glaze suppresses salmon's trimethylamine while amplifying its natural fat-sweetness — the teriyaki logic — while blue cheese's phenylacetaldehyde and dimethyl sulfide share the sulfurous-marine compound family with salmon, creating a unified savory depth. The trio is a bold Scandinavian-inspired preparation.",
     "Caramel Blue Cheese Glazed Salmon",
     ["Whisk crumbled blue cheese into a dark caramel with a splash of soy sauce; strain smooth.",
      "Sear salmon skin-side down until crisp; flip and brush with caramel-blue cheese glaze.",
      "Finish under the broiler 2 minutes until lacquered; serve with pickled cucumber."]),
]

conn = sqlite3.connect(DB)
c = conn.cursor()
for (a, b, cc, desc, title, steps) in TRIPLETS:
    c.execute(
        "INSERT OR REPLACE INTO triplet_info (ing_a, ing_b, ing_c, description, recipe_title, recipe_steps) VALUES (?,?,?,?,?,?)",
        (a, b, cc, desc, title, json.dumps(steps))
    )
conn.commit()
conn.close()
print(f"Batch 010 done: inserted {len(TRIPLETS)} triplets.")
